<!DOCTYPE HTML PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "http://www.wapforum.org/DTD/xhtml-mobile10.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>开开，基于位置的真实社交网络</title>
</head><body><p align="left">
开开：与朋友分享位置的社交网络<br>
【软件下载】<br>
<a href="http://k.ai/mobile/tools/phone?bid=26">苹果</a> <a href="http://k.ai/mobile/tools/phone?bid=1">诺基亚</a> <a href="http://k.ai/mobile/tools/phone?bid=7">多普达/HTC</a> <a href="http://k.ai/mobile/tools/phone?bid=2">摩托罗拉</a> <a href="http://k.ai/mobile/tools/phone?bid=6">三星</a> <a href="http://k.ai/mobile/tools/phone?bid=27">索尼爱立信</a> <a href="http://k.ai/mobile/tools/phone?bid=28">联想</a> <a href="http://k.ai/mobile/tools/phone?bid=25">华为</a> <a href="http://k.ai/mobile/tools/chooseos?os=bb">黑莓</a><br>
<br>        
<img src="/images/wap.jpg"  width="240" height="320"><br>
功能介绍：<br>
开开——开开是与朋友分享位置的社交网络，打开手机开开，一键签到，就可以告诉朋友“我在哪里”。在开开，你还可以轻松结识与在附近的志趣相投的朋友，享受各种签到优惠！<br/>
1. 用手机签到check-in，告诉朋友们“我在这里”<br/>
2. 记录你的城市探索之旅，写下一部自己的行者日记<br/>
3. 在去过的地点留下贴士tips，和朋友们分享自己的发现或心得<br/>
4. 通过吼吼Shout，随时随地发表点滴思绪<br/>
5. 搜集神秘勋章，成为不同地点的掌门，享受尊荣与特别优惠，体会小小惊喜<br/>
6. 和附近的人一起玩寻宝游戏，并有机会兑换实物<br/>
7. 将你的开开动态同步分享到其他热门站点<br/>
活在当下，就告诉朋友我在哪里！尽情享受开开带来的新生活吧！<br/>
</p><p align="left">
【软件下载】<br>
<a href="http://k.ai/mobile/tools/phone?bid=26">苹果</a> <a href="http://k.ai/mobile/tools/phone?bid=1">诺基亚</a> <a href="http://k.ai/mobile/tools/phone?bid=7">多普达/HTC</a> <a href="http://k.ai/mobile/tools/phone?bid=2">摩托罗拉</a> <a href="http://k.ai/mobile/tools/phone?bid=6">三星</a> <a href="http://k.ai/mobile/tools/phone?bid=27">索尼爱立信</a> <a href="http://k.ai/mobile/tools/phone?bid=28">联想</a> <a href="http://k.ai/mobile/tools/phone?bid=25">华为</a> <a href="http://k.ai/mobile/tools/chooseos?os=bb">黑莓</a><br>
<br/>
本软件不收取任何费用。<br>
</p><p align="left">
		合作联络邮箱：<a href='mailto:contact@k.ai'>contact@k.ai</a>  <br>
	
	<do type="prev" name="Prev" label="返回"><prev></prev><br><br><a href="http://m.k.ai/">开开主页</a></do></p>		</body></html>