<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns:lift="http://liftweb.net" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
    <meta content="width=320" name="viewport" />   
     <title>开开，记录城市足迹</title>
      <?php include_once(dirname(__FILE__).'/../include/textcss.phtml');?>
</head>
<body>
   
	<div id='category'>
	<?php 		
		echo $this->pagemenu."<br/>";
	?>
	</div>
	<div id='content'>
	<?php 
		echo $this->message."<br/>";
		echo $this->menuos;
	?></div>
			
	<a href='javascript:history.go(-1);'>返回</a>
</body>
</html>  
  