<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
<body id="index">

<?php include_once(dirname(__FILE__).'/../include/newheader.phtml');?>	

<div id="content">
  <div class="mid">

	  <div id="half_left">
			<div class="tabs">
	            <ul class="tabNavigation">
	                <li class="title"><?php echo $this->lang->global->venue->cregister; ?></li>
	            </ul>
	            <div id="venue_box">	            
	          <?php 
	         	if(!$this->poiInfo['poi_id']){	         		
	          ?>
	        <div id="search_poi_div" style='margin-top:15px;'>
	        	<div class='venue_about_title'>
					<div class='left'>查找你要登记的店铺</div>
					<div class='venue_about_title_sanjiao'></div>
		        </div> 
		        <div style='margin:13px 0;'>
		            <table  />
		            	<tr>
		            		<td style='padding-left: 10px;'><input type="text" id="poi_keyword" value="<?php echo $this->lang->javascript->global->checkin->poi_search->tips;?>" size="40" style='color: #999; width: 225px;height: 15px;padding-top:4px;line-height:15px;'/></td>
		            		<td width='5'>
		            			<input type="hidden" id="checkin_poi_search_range" value="50000" />
		            		</td>
		            		<td align="right">
		            		<div class='venue_special_submit venue_button'><a href='javascript:void(0)' id='searchpoi_button'>搜索</a></div>
		            		
		            			            	</tr>
		            </table>
		            </div>
	            	<div id='search_pois_result' class='hide' style='padding-left:10px;'>搜索结果</div>
	            </div>
	            
	            <div id="search_pois" class='hide' style='padding-left:10px;'>
		            <form>
		            
		            	<table class="blog_table">
		            	<div id="tbl_search_pois">		            	
						 </div>					 
						</table>
					</form>
					
					
					
					<table class='pager'>
							<tr>
							<td>
								<div  id='pager_search_pois' class='hide'></div>
							</td>
							</tr>
					</table>
					<div id='check_lotspoi'><input type="checkbox" id="havelotspoi" value="1" name="havelotspoi" checked='checked'/>我拥有多家店铺（<span style='color:#999'>连锁店长只需提交一家店铺，通过审核后，我们会为您添加其他店铺</span>）</div>
					<a id="choose_poi" href="javascript: void(0);"  >确认信息</a>
				</div>
	          <?php }?>
		        
		         <div class='venue_about_title'>
					<div class='left'>身份认证</div>
					<div class='venue_about_title_sanjiao'>		           		
		           	</div>
		         </div> 
				<div id='venue-owner'>
				
				
				<div id='require_form'>
				<form action="/venue/step2" method="post" id="venue_reg_form"> 
					
					<div class="row">					 
					  <div class="field">					  
					   <label for="poi_name">商铺名称：</label>					 
						<span id='err_poi' class='err'></span>
						<span id='venue-poiname'></span>
					  </div>
					</div>	  
					<div class="row">
					 
					  <div class="field">					  
					   <label for="company">公司全称：</label>
					  	 <input type="text" id="company" name="company" value="<?php echo $this->lang->javascript->venue->require->company;?>" size="35" style="color: #999;" /><span class='err'>*</span><span id='ok_email'></span>		  	 		  	 
					     <span id='err_company' class='err'><?php echo $this->err['err_email'];?></span>
					  </div>
					</div>
					<div class="row">
					  
					  <div class="field">
					  <label for="company">业主姓名：</label>
					  	 <input type="text" id="ownername" name="ownername" value="<?php echo $this->lang->javascript->venue->require->name;?>" size="35" style="color: #999;" /><span class='err'>*</span><span id='ok_email'></span>		  	 		  	 
					     <span id='err_ownername' class='err'><?php echo $this->err['err_email'];?></span>
					  </div>
					</div>
					<div class="row">
					  
					  <div class="field">
					  <label for="company">联系电话：</label>
					  	 <input type="text" id="phone" name="phone" value="<?php echo $this->lang->javascript->venue->require->phone;?>"  size="35" style="color: #999;" /><span class='err'>*</span><span id='ok_email'></span>		  	 		  	 
					     <span id='err_phone' class='err'><?php echo $this->err['err_email'];?></span>
					  </div>
					</div>
					<div class="row">
					  
					  <div class="field">
					  <label for="company">电子邮件：</label>
					  	 <input type="text" id="email" name="email" value="<?php echo $this->lang->javascript->venue->require->email;?>"  size="35" style="color: #999;" /><span id='ok_email'></span>		  	 		  	 
					     <span id='err_email' class='err hide'><?php echo $this->err['err_email'];?></span>
					  </div>
					</div>
					<div class="row">	
					  <label for='agree'></label>	 
					  <div class="field">
					  	<input type="checkbox" id="ownertype" value="1" name="ownertype" /> 我是广告或者公关公司代为客户验证信息					    				<span class='err' id='err_agree'><?php echo $this->err['err_agree'];?></span>
					    	</div>
					</div>
					<input type="hidden" id="poi_id" name="poi_id" value="" />	
					<input type="hidden" id="hadlotspoi" name="hadlotspoi" value="0" />							
				</form>
				<div class='venue_submit' style='float:left;margin-left:100px;!margin-left:70px;'><a href='javascript:void(0)' id='venue_reg_submit'><div class='venue_botton' >提交信息</div></a></div>		
				
				</div>	
				</div>  
				<div class='venue_from_mess'>为了验证您是店长，请提供以下基本信息。登记后，我们的工作人员会在72小时内与您取得联系，并与您商讨最佳的推广方案。
如果您在商户认证申请中遇到任何问题，欢迎通过以下方式与我们联系。 
<br/>
电话： 0512-62888255 转市场 （周一至周五 9:00~17:00）
<br/>
EMAIL：contact@k.ai
				
				</div>		
	              <div class="clearfix"></div>
	              
	            </div>
	        </div><!--#tabs-->
        
	  </div><!--#half_left-->
	  <div id="half_right">
	    <div id="venue_step" class="right_nav">
	      <h2><?php echo $this->lang->global->venue->title; ?></h2>
	      <ul>	     
	        <li>	         
	         <?php echo $this->lang->global->venue->about; ?>	         
	        </li>
	      	<li class='on'>	         
	         <?php echo $this->lang->global->venue->step1; ?>        
	        </li>
	        <li>	        
	          <?php echo $this->lang->global->venue->step2; ?>	         
	        </li>
	        <li>	         
	          <?php echo $this->lang->global->venue->sucess; ?>	         
	        </li>
	      </ul>
	       <div class="clearfix"></div>
	    </div>
	    
	    <div class="right_nav" id="venue_right_back">
	      <ul class="button"><li>
	        <a href="/venue">返回第一页</a>
	        </li>
	      </ul>
	    </div>
	  </div><!--#half_right-->
	  <div class="clearfix"></div>
  </div><!--#mid-->
</div> <!--#content-->


<!-- //------------------------------------------------------------- -->
<!-- 创建新地点 -->
<?php if($this->uid){?>
<div style="display: none;" id='global_create_div'>
<div id="createdlg" style="width: 500px; height: 560px;" >
	<form>
	<div class="left" style="margin-left:10px;">
		<img src="images/checkin.gif" alt=""  />
	</div>
	<div class='dialog_title'><?php echo $this->lang->global->include->dmessage->creatpoi; ?></div>
	<a href="javascript:void(0);" id="close_create" style="float: right; display: block; margin-top: 8px;"><img src="images/close_button.png" /></a>
	<div class='clearfix'></div>

	<div class="map">
	<div id="create_map" style="width: 500px; height: 150px;margin: 0;border:1px solid #ddd;" class='map'></div>
	<input type="hidden" value="" id="create_location_lat" />
	<input type="hidden" value="" id="create_location_lon" />
	</div>
		   
	<div id="creatpoi_tip" style="background-color:#dee5ee; margin-top: 8px; font-size: 14px; font-weight: bold; text-align: center; padding: 7px 0; color: #555555;">
		<span><?php echo $this->lang->global->include->dmessage->creatpoi_tip; ?></span>	
	</div>
	
	<div class="create_div">
		<table width="100%" height="100%">
			<tr>
				<td width="15%"><?php echo $this->lang->javascript->home->add_poi->name; ?></td>
				<td><input type="text" name="add_poi_name" id="add_poi_name" maxlength="25" size="40"/></td>
			</tr>
			<tr>
				<td><?php echo $this->lang->javascript->home->add_poi->address; ?></td>
				<td><input type="text" name="add_poi_address" id="add_poi_address" maxlength="30" size="40"/></td>
			</tr>
			<tr>
				<td><?php echo $this->lang->javascript->home->add_poi->phone; ?></td>
				<td><input type="text" name="add_poi_phone" id="add_poi_phone" maxlength="30" size="40"/></td>
			</tr>
			<tr>
				<td><?php echo $this->lang->javascript->home->add_poi->category; ?></td>
				<td>
					<select id="add_poi_category" name="add_poi_category">
						<?php //foreach($this->categories as $row){?>
							<!-- <option value="<?php echo $row['category_id']; ?>"><?php echo $row['category_name']; ?></option>  -->
						<?php //}?>
						<?php for($i=1; $i<=11; $i++){ ?>
							<option value="<?php echo $i; ?>"><?php eval('echo $this->lang->javascript->home->add_poi->category'.$i.' ;'); ?></option>
						<?php }?>
					</select>
					<input type="hidden" id="add_poi_category_hide" value="1" />
				</td>
			</tr>
			<tr>
				<td><?php echo $this->lang->javascript->home->add_poi->city; ?></td>
				<td>
					<input type="text" name="add_poi_city" id="add_poi_city" maxlength="10" />
					<?php echo $this->lang->javascript->home->add_poi->province; ?>
					<input type="text" name="add_poi_province" id="add_poi_province" maxlength="10"/>
					<?php echo $this->lang->javascript->home->add_poi->country; ?>
					<input type="text" name="add_poi_country" id="add_poi_country" maxlength="10"/>
				</td>
			</tr>
			<tr>
				<td colspan="2" align="right">
					<a href="javascript: void(0);" class="blue_btn" id="create_poi_btn"><?php echo $this->lang->javascript->home->add_poi->btn; ?></a>
				</td>
			</tr>
		</table>
	</div>
	
	
	</form>
</div>
</div>
<?php }?>


<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>
<?php echo $tmpb;?>
</body>
</html>
<?php $this->Gz();?>