<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>开开 - 记录足迹 分享城事</title>
<meta name="keywords" content="开开, 位置, 社交网络, 游戏, 签到, 掌门, 寻宝, Kai, location, SNS, check-in, Mayor, Geocaching"  />
<meta name="description" content="开开K.ai是新一代的位置网络，也是真实的白领社交网络。在开开签到，你能够找到朋友、分享贴士，并用全新的方法探索身边的城市。同时还可以争掌门、赢勋章" /> 
<!--[if lt IE 7]>
<meta http-equiv='X-UA-Compatible' content='IE=EmulateIE7' />
<script src="../js/iepngfix_tilebg.js" type='text/javascript'></script>
<style type="text/css">
 .zoompng{ behavior: url("../js/iepngfix.htc") }
</style>
<![endif]-->
<script src="../js/jquery/jquery-1.4.2.min.js" type='text/javascript'></script>
<script src="../js/index.js" type='text/javascript'></script>
<link rel="stylesheet" type="text/css" href="../css/default.css?ver=20110506000007" />
<link rel="shortcut icon" href="http://k.ai/favicon.ico?v=1" />

</head>
<body>
<div id='header'>
	<div class='mid'>
		<img src='../images/logo.jpg' id='logo'  />
	</div>
</div>
<div class='content mid'>
	<div><img src='../images/top.jpg' /></div>	
	<div id='majors'>
		<div class="left">
   			<div style="text-align: center;" class="left">
   				<img class="zoompng" src="/images/crown.png"><br>
   				<span style="font-size: 14px; font-weight: bold;">附近掌门</span>
   			</div>
   			   	<div class="left majoruser">
   					<a href="http://k.ai/janice930"><img height="48" width="48" src="http://k.ai/files/avatar/41/29/01/thumb_405661.197090.jpg"></a><br>
   					<a href="http://k.ai/janice930">钱闵</a><br>
   					<a href="http://k.ai/poi/5939646">东环时代广场</a>
   				</div>
   			   	<div class="left majoruser">
   					<a href="http://k.ai/kai128733"><img height="48" width="48" src="http://k.ai/files/avatar/11/40/96/thumb_128733.96200.jpg"></a><br>
   					<a href="http://k.ai/kai128733">破衣裳</a><br>
   					<a href="http://k.ai/poi/125248">iLost Cafounge</a>
   				</div>
   			   	<div class="left majoruser">
   					<a href="http://k.ai/babyfish"><img height="48" width="48" src="http://k.ai/files/avatar/38/48/11/thumb_174490.14643.jpg"></a><br>
   					<a href="http://k.ai/babyfish">babyfish</a><br>
   					<a href="http://k.ai/poi/19074351">苏安商业中心</a>
   				</div>
   			   	<div class="left majoruser">
   					<a href="http://k.ai/kai448623"><img height="48" width="48" src="http://k.ai/files/avatar/06/03/58/thumb_448623.263638.jpg"></a><br>
   					<a href="http://k.ai/kai448623">丧尸</a><br>
   					<a href="http://k.ai/poi/122835">麦克风ktv</a>
   				</div>
   			   	<div class="left majoruser">
   					<a href="/kai493835"><img height="48" width="48" src="http://k.ai/files/avatar/65/70/91/thumb_493835.159390.jpg"></a><br>
   					<a href="http://k.ai/kai493835">飞翔73</a><br>
   					<a href="http://k.ai/poi/126178">夏园新村</a>
   				</div>
   			   	<div class="left majoruser">
   					<a href="http://k.ai/kai90048"><img height="48" width="48" src="http://k.ai/files/avatar/03/39/97/thumb_90048.205590.jpg"></a><br>
   					<a href="http://k.ai/kai90048">Benjamin.M</a><br>
   					<a href="http://k.ai/poi/122762">猫的天空之城概念书店(平江路店)</a>
   				</div>
				<div class="left majoruser">
   					<a href="/kai448623"><img height="48" width="48" src="http://k.ai/files/avatar/06/03/58/thumb_448623.263638.jpg"></a><br>
   					<a href="/kai448623">丧尸</a><br>
   					<a href="/poi/122835">麦克风ktv</a>
   				</div>
   			   	<div class="left majoruser">
   					<a href="/kai493835"><img height="48" width="48" src="http://k.ai/files/avatar/65/70/91/thumb_493835.159390.jpg"></a><br>
   					<a href="/kai493835">飞翔73</a><br>
   					<a href="/poi/126178">夏园新村</a>
   				</div>
   			   	<div class="left majoruser">
   					<a href="/kai90048"><img height="48" width="48" src="http://k.ai/files/avatar/03/39/97/thumb_90048.205590.jpg"></a><br>
   					<a href="/kai90048">Benjamin.M</a><br>
   					<a href="/poi/122762">猫的天空之城概念书店(平江路店)</a>
   				</div>
   			   		</div>
	</div>
	<div class='box_bottom'>
		<div id='kai_account'>
			<div id='reg_kaikai'><img src='../images/tab1.png' class='zoompng' /></div>
			<div id='third_kaikai'><img src='../images/tab2.png' class='zoompng' /></div>
		</div>
	</div>
	<div id='account'>
		<div id='reg_to_kaikai'>
			<div id='regform'>
			<form id="signup_form" method="post" action="/signup/do">  	   
				<div class="row">
				  <label for="email">Email：</label>(你常用的email邮箱)
				  <div class="field">
					 <input type="text" value="" name="email" id="email"><span id="ok_email"></span>		  	 		  	 
					 <span class="err" id="err_email"></span>
				  </div>
				</div>
				<div class="row">
				  <label for="nickname">昵称：</label>(5-20个字符之间)
				  <div class="field">
					 <input type="text" value="" name="nickname" id="nickname"><span id="ok_nickname"></span>	
					 <span class="err" id="err_nickname"></span>	    
					
				  </div>
				</div>  
				<div class="row">
				  <label for="password">密码：</label>(6-20个字符)
				  <div class="field">
					 <input type="password" value="" name="password" id="password">
				  
					<span id="ok_password"></span>
					<span class="err" id="err_password"></span>
				  </div>
				</div> 
				
				<div class="row">
				  <label for="repassword">确认密码：</label>(6-20个字符)
				  <div class="field">
					<input type="password" value="" name="repassword" id="repassword">
				  
					<span id="ok_repassword"></span>
					<span class="err" id="err_repassword"></span>
				  </div>
				</div> 		
				
				
				<div class="row">	
				  <label for="agree"></label>	 
				  <div class="field">
					<input type="checkbox" checked="checked" name="agree" value="1" id="agree">  我已阅读并同意<a class="blank" href="/signup/terms" target="_blank">服务条款</a>
									<span id="err_agree" class="err"></span>
						</div>
				</div>	
				<div class="row">	
				  <label for="agree"></label>	 
				  <div class="field">		
									<input type="button" value="立即注册" class="btn" id="signup_btn" style="text-align: center;">
						   <input type="hidden" value="0" id="formIsValid" name="formIsValid">
						   <input type="hidden" value="zh-cn" name="language">
						   <input type="hidden" value="local" name="login_type">
						   <input type="hidden" value="" name="ref_uid">
				  </div>
				</div> 
		    	
		    </form>
			
			
			
			</div>
		</div>
		<div id='third_to_kaikai'><div style="" id="login_third_guide_list">		
				 	<a id="loginfromsina" href="http://k.ai/login?login_from=sina"><img src="images/t-sina.png"></a>
				 	<br><br>
				 	<a id="loginfromqq" href="http://k.ai/login/thirdqq"><img src="images/t-qq.png"></a>
				 	<br><br>
				 	<a id="loginfromsohu" href="http://k.ai/login?login_from=sohu"><img src="images/t-sohu.png"></a>
				 	<br><br>
				 	<a id="loginfromkaixin001" href="http://k.ai/login?login_from=kaixin001"><img src="images/t-kaixin001.png"></a>
				 	<br><br>
				 	<a id="loginfrom163" href="http://k.ai/login/third163"><img src="images/t-163.png"></a>
				 	<br><br>
				 	<a id="loginfromrenren" href="http://k.ai/login/thirdrenren"><img src="images/t-renren.png"></a>
			 	</div>
		
		
		
		</div>
	</div>
	<div id='invitation_title'>
		<img src='../images/tab3.png'  class='zoompng'/>
	</div>
	<div id='invitation_content'>
		<div id='invitation_mess'>
		截止5月25日下午15:00,邀请好友注册开开成功次数最多的人将获得iPad2大奖一部！
		<br/>
		<div id='invitation_img'>
			<img src='../images/button.png' class='zoompng' />
		</div>
		<div id='invitation_link'>
			<input type="text" class="button" name="better_name" id="linkurl" value="http://k.ai/signup?ref=175630" size="32">
		</div>
		
		<br/>
		<br/>
	邀请好友注册开开，邀请成功次数最多的前20名各获得开开纪念T恤一件！
		
		</div>
	</div>
	<div id='paihang_title'>
		<img src='../images/tab4.png'  class='zoompng'/>
	</div>
	<div id='paihang_content'>
	</div>
	<div id="footer">
	</div>
</div>

</body>
</html>
