<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta name="viewport" content="width=device-width; initial-scale=1.4; minimum-scale=1.0; maximum-scale=2.0"/>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><?php echo $this->lang->global->meta->title;?></title>
	<?php include_once(dirname(__FILE__).'/../include/textcss.phtml');?>
</head>
<body>
	<?php include_once(dirname(__FILE__)."/../include/logo.phtml")?>
	<div id="headinfo">		
		<a href="/polo/user?uid=<?php echo($this->userInfo["uid"])?>" ><?php echo($this->userInfo["nickname"])?></a>
		<?php echo "->".$this->lang->user->checkins;?>
		<hr/>
	</div>
	
	<div id="content">
		<table>
			<?php for($i=0; $i < count($this->checkins); $i++){?>
			<tr>
				<td><?php echo ($i+$this->start)."."?></td><td><a href="/polo/place?pid=<?php echo $this->checkins[$i]['poi']['poi_id'];?>"><?php echo $this->checkins[$i]['poi']['name']; ?></a>
				<?php if ($this->checkins[$i]['message']) { ?> : <?php echo $this->checkins[$i]['message'];?><?php }?>
				<?php if ($this->checkins[$i]['attach']) { ?>
				<br />
				<img src="<?php echo $this->checkins[$i]['attach_tiny'];?>" />
				<?php }?>
				</td>
			</tr>
			<tr>
				<td></td>
				<td><?php echo $this->checkins[$i]['poi']['city']." ".Better_Functions::compareTime($this->checkins[$i]['dateline']);
				if($this->checkins[$i]['priv_blog']==0 && $this->checkins[$i]['uid']!=$this->user['uid']){
					echo "<a href=\"/polo/user/shout?cat=".$this->checkins[$i]['type']."&upbid=".$this->checkins[$i]['bid']."\">".$this->lang->javascript->global->blog->rt."</a> ";
				}
				if($this->checkins[$i]['uid']==$this->user['uid'])
				{
					echo "  <a href=\"/polo/user/delblog?id=".$this->checkins[$i]['bid']."\">".$this->lang->javascript->global->blog->delete_it."</a> ";
				}
				?></td>
			</tr>
			<?php }?>
		</table>
		<?php
			echo $this->urlNext." ".$this->urlPrev;
		?>
		<?php 
		if(strlen($this->errorinfo)>0){
		?>
	<div id="error"><?php echo $this->errorinfo;?></div>
	<?php 
		} else if( count($this->checkins) < 1 ){
		 		echo("<p>".$this->lang->global->not_checkin_yet."</p>"); 
		}
		 ?>
	</div>
	<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>
</body>
</html>