<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta name="viewport" content="width=device-width; initial-scale=1.4; minimum-scale=1.0; maximum-scale=2.0"/>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><?php echo $this->lang->global->meta->title;?></title>
	<?php include_once(dirname(__FILE__).'/../include/textcss.phtml');?>
</head>
<body>
	<?php include_once(dirname(__FILE__)."/../include/logo.phtml")?>
	<div id="headinfo">		
		<a href="/polo/user?uid=<?php echo($this->userInfo["uid"])?>" ><?php echo($this->userInfo["nickname"])?></a>
		<?php echo "->".$this->lang->user->favorites;?>
		<hr/>
	</div>
	<div id="content">
		<?php 
			echo $this->favoritemenu;
			if ( "poi" == $this->category ) {			
			echo "<table>";
			for($i=0; $i < count($this->favorite); $i++)				
				echo "<tr><td valign=\"top\">".($i+$this->start).".</td><td><a href=\"/polo/place?pid=".$this->favorite[$i]['poi_id']."\">".$this->favorite[$i]['name']."</a> <a href=\"/polo/user/delfavorite?cat=place&id=".$this->favorite[$i]['poi_id']."\">".$this->lang->javascript->global->favorite->cancel."</a></td></tr>";
			echo "</table>";
		
		}else{			
			echo "<table>";
			for($i=0; $i < count($this->favorite); $i++) {
				//<!-- author and place -->
				echo "<tr valign=\"top\"><td>".($this->start+$i).".</td>";
				echo "<td>";				
				$author = ""; 
				$author = $author."<a href=\"/polo/user?uid=".$this->favorite[$i]['uid']."\">".$this->favorite[$i]['nickname']."</a>";
				if( $this->favorite[$i]['poi']['poi_id'] ){							
					$author = $author."@<a href=\"/polo/place?pid=".$this->favorite[$i]['poi']['poi_id']."\">".$this->favorite[$i]['poi']['name']."</a>:";
				}else{
					$author = $author.":";
				}
				echo $author;				
				echo $this->favorite[$i]['message'];
	               
	           	switch( $this->timeline[$i]['type'] ){
	           		case "normal":
	           			//echo "[".$this->lang->sidebar->shouts."]";
	           			break;
	           		case "tips":
	           			//echo "[贴士]";
	           			break;
	           		case "checkin":
	           			//echo "[".$this->lang->sidebar->checkins."]";
	           			echo $this->lang->sidebar->checkins;
	           			break;
	           	} 
	           
	           	
	           //	<!-- reply and delete button -->
	           
	            
	           	echo " <a href=\"/polo/user/delfavorite?cat=".$this->favorite[$i]['type']."&id=".$this->favorite[$i]['bid']."\">".$this->lang->javascript->global->favorite->cancel."</a></td></tr>";
	           		
	           	//<!-- attached image if there is -->	 
	           	/*          		
	           	if($this->favorite[$i]['attach_tiny']){
	           		echo "<tr><td></td><td>";
	               	echo "<img src=\".$this->timeline[$i]['attach_tiny']\" />";
	               	echo "</td></tr>";
	           	}
	           		*/	           			           		
	           	//<!-- publication time -->
	           	echo "<tr><td></td><td>";
	            echo Better_Functions::compareTime($this->favorite[$i]['dateline']);
	            $source = $this->favorite[$i]['source'];
	            echo $this->lang->user->from.Better_Functions::source($source)."<br/><br/>";
	            echo "</td></tr>";	        	
			}
			echo "</table>";
		}?>
		<?php 
			if( count($this->favorite) < 1 ) 
				echo("<p>".$this->lang->javacript->global->favorite->havent_favorites.$this->lang->global->favorite_reject."</p>");
			else
				echo $this->urlNext." ".$this->urlPrev;
		?>
	</div>
	<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>
</body>
</html>