<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta name="viewport" content="width=device-width; initial-scale=1.4; minimum-scale=1.0; maximum-scale=2.0"/>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><?php echo $this->lang->global->meta->title;?></title>
	<?php include_once(dirname(__FILE__).'/../include/textcss.phtml');?>
</head>
<body>
	<?php include_once(dirname(__FILE__)."/../include/logo.phtml")?>
	<div id="headinfo">		
		<a href="/polo/user?uid=<?php echo($this->userInfo["uid"])?>" ><?php echo($this->userInfo["nickname"])?></a>
		<?php echo "->".$this->lang->mobile->global->footprint;?>
		<hr/>
	</div>
	<div id="content">
		<table>
	   	<?php 
	   		for($i=0; $i < count($this->timeline); $i++) {
	   			echo "<tr valign=\"top\">";
	   			echo "<td>".($this->start + $i).".</td>";
	   			echo "<td>";
	           		
	   			$checktype = ("checkin" == $this->timeline[$i]['type'])? 0:1;	 
           		if( $this->timeline[$i]['message'] ) 
           			echo $this->timeline[$i]['message'];
    				if($this->timeline[$i]['attach_tiny'] && $checktype){
               			echo "<br/><img src=\"".$this->timeline[$i]['attach_tiny']."\"/><br/>";
               		}
	           	else{
	           		switch( $this->timeline[$i]['type'] ){
	           			case Polo_UserController::$STATUS_NORMAL:
	           				echo "[".$this->lang->global->shout->text."]";
	           				break;
	           			case Polo_UserController::$STATUS_TIPS:
	           				echo "[".$this->lang->global->tips->text."]";
	           				break;
	           			case Polo_UserController::$STATUS_CHECKIN:
	           				echo "[".$this->lang->javascript->global->global->checkin->title."]";
	           				break;
	           		} 
	           	}
	           	// original messge if there is 
	           		$upbid = $this->timeline[$i]['upbid'];
	           		$upblog = $this->retwitter[$upbid];
	           		if($this->timeline[$i]['showrt'] && $this->timeline[$i]['upbid'] && $upblog){	           			
	           			$senderinfo = "//<a href=\"/polo/user?uid=".$upblog['uid']."\">".$upblog['nickname']."</a>";
	           			if( $upblog['poi']['poi_id'] ){
	           				$senderinfo .= "@<a href=\"/polo/place?pid=".$upblog['poi']['poi_id']."\">".$upblog['poi']['name']."</a>:";
	           			} else {
	           				$senderinfo = $senderinfo.":";
	           			}
	           			if( strlen($upblog['message']) >0 ){
	           				$senderinfo .="<br/>".$upblog['message'];
	           			}
	           			if($upblog['attach_tiny']){	           			
	               			$senderinfo .= "<br/><img src=\"".$upblog['attach_tiny']."\"/><br/>";
	               		} 
	           			if( strcmp($upblog['type'], "checkin")==0 ){
	           				$senderinfo .= "[".$this->lang->javascript->global->checkin->title."]";
	           			}
	           			echo $senderinfo;
	           		}     		
	           		// original end	
	   			
	           	echo "</td></tr>";  
	           	echo "<tr><td></td><td><a href=\"/polo/place?pid=".$this->timeline[$i]['poi']['poi_id']."\">".$this->timeline[$i]['poi']['name']."</a> ".Better_Functions::compareTime($this->timeline[$i]['dateline']);
	   		
	        	if($this->timeline[$i]['uid']!=$this->user['uid'])
	        	{
	           		if($checktype && $this->timeline[$i]['priv_blog']==0){
	           			echo "<a href=\"/polo/user/shout?cat=".$this->timeline[$i]['type']."&upbid=".$this->timeline[$i]['bid']."\">".$this->lang->javascript->global->blog->rt."</a> ";
	           		}
	        	}
	       	 	else
	        	{
	           		echo "<a href=\"/polo/user/delblog?id=".$this->timeline[$i]['bid']."\">".$this->lang->javascript->global->blog->delete_it."</a> ";
	        	}
	        	if($checktype) {
	           		echo "<a href=\"/polo/user/addfavorite?cat=".$this->timeline[$i]['type']."&id=".$this->timeline[$i]['bid']."&fid=".$this->timeline[$i]['uid']."\">".$this->lang->javascript->global->favorite->title."</a> ";	       
	        	}
	           	echo "</td></tr>";
	    	}?>	           
		</table>
		 <?php
			echo $this->urlNext." ".$this->urlPrev;
		?>
	</div>
		
	<div id="visitors">
	</div>
	<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>
</body>
</html>