	<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
	
	<body>
	<form id="new_special" enctype="multipart/form-data" action="/admin/activity/donewactivity" method="post">
	<div id="list">
		<table class="kai_table">
			<tr>
				<th colspan='4' style="text-align:center;">新增活动信息</th>
			</tr>
			<tr>
				<td>POI LIST</td>
				<td colspan='3'>
					<textarea id='poi_str' name='poi_str' cols='50' rows='4'><?php echo $this->activity_poi;?></textarea>(用英文“,”分割，比如122707,1002这样)
				</td>
			</tr>
			<tr>
				<td>标题</td>
				<td colspan='3'>
					<input type='text' name='title' />
				</td>
			</tr>
			<tr>
				<td>活动信息：</td>
				<td colspan='3'>
					<textarea id='content' name='content' cols='50' rows='4'><?php echo $this->specialDetail['content'];?></textarea>
				</td>
			</tr>
			<tr>
				<td>图片（480）Banner：</td>
				<td colspan='3'>
				<input type='file' name='banner_480' />
				</td>
			</tr>
			<tr>
				<td>图片（360）：</td>
				<td colspan='3'>
		<input type='file' name='banner_360' />
				</td>
			</tr>
			<tr>
				<td>图片（240）：</td>
				<td colspan='3'>
		<input type='file' name='banner_240' />
				</td>
			</tr>
			<tr>
				<td>图片（480）附件：</td>
				<td colspan='3'>
				<input type='file' name='attach_480' />
				</td>
			</tr>
			<tr>
				<td>图片（360）：</td>
				<td colspan='3'>
		<input type='file' name='attach_360' />
				</td>
			</tr>
			<tr>
				<td>图片（240）：</td>
				<td colspan='3'>
		<input type='file' name='attach_240' />
				</td>
			</tr>
		<tr>
				<td>开始时间：</td>
				<td colspan='3'>
				<input id="begintm" type="text" name="begintm" >
					
				</td>
			</tr>
			<tr>
				<td>结束时间：</td>
				<td colspan='3'>
					<input id="endtm" type="text" name="endtm" >
				</td>
			</tr>
				
			<tr>
				
				<td colspan='4'>
					<input type="checkbox" id="ownertype" value="1" name="ownertype" checked='checked'/> 同时复制到优惠
				</td>
			</tr>			
			<tr>
				<td colspan='4' style="text-align:center;">
					<input type='button' id='special_new' name='special_new' value="新增" />
				</td>
			</tr>
		</table>
		</div>
		</form>
		
	<?php include dirname(__FILE__).'/../include/footer.phtml';?>