	<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
	
	<body>
	<form id="update_special" enctype="multipart/form-data" action="/admin/activity/doupdateactivity" method="post">
	<div id="list">	
		<table class="kai_table">
			<tr>
				<th colspan='4' style="text-align:center;">修改活动信息</th>
			</tr>
			<tr>
				<td>POI LIST</td>
				<td colspan='3'>
					<input type='hidden' name='act_id' value="<?php echo $this->activity['act_id'];?>" />
					<textarea id='poi_str' name='poi_str' cols='50' rows='4'><?php echo $this->activity_poi;?></textarea>
					
				</td>
			</tr>
			<tr>
				<td>标题</td>
				<td colspan='3'>
					<input type='text' name='title' value="<?php echo $this->activity['title'];?>"/>
				</td>
			</tr>
			<tr>
				<td>活动信息：</td>
				<td colspan='3'>
					<textarea id='content' name='content' cols='50' rows='4'><?php echo $this->activity['content'];?></textarea>
				</td>
			</tr>
			<tr>
				<td>图片（480）Banner：</td>
				<td colspan='3'>
				<input type='file' name='banner_480' />
				<input type='hidden' name='h_banner_480' value="<?php echo $this->activity['image_url'];?>" />
				</td>
			</tr>
			<tr>
				<td>图片（360）：</td>
				<td colspan='3'>
		<input type='file' name='banner_360' />
				</td>
			</tr>
			<tr>
				<td>图片（240）：</td>
				<td colspan='3'>
		<input type='file' name='banner_240' />
				</td>
			</tr>
			<tr>
				<td>图片（480）附件：</td>
				<td colspan='3'>
				<input type='file' name='attach_480' />
				</td>
			</tr>
			<tr>
				<td>图片（360）：</td>
				<td colspan='3'>
		<input type='file' name='attach_360' />
				</td>
			</tr>
			<tr>
				<td>图片（240）：</td>
				<td colspan='3'>
		<input type='file' name='attach_240' />
		<input type='hidden' name='h_attach_240' value="<?php echo $this->activity['attach_url'];?>" />
				</td>
			</tr>
		<tr>
				<td>开始时间：</td>
				<td colspan='3'>
				<input id="begintm" type="text" name="begintm" value="<?php echo $this->activity['begintm'] ?  date('Y-m-d H:i', $this->activity['begintm']+BETTER_8HOURS) : 0;?>" >
					
				</td>
			</tr>
			<tr>
				<td>结束时间：</td>
				<td colspan='3'>
					<input id="endtm" type="text" name="endtm" value="<?php echo $this->activity['endtm'] ?  date('Y-m-d H:i', $this->activity['endtm']+BETTER_8HOURS) : 0;?>">
				</td>
			</tr>
				
				
			<tr>
				<td colspan='4' style="text-align:center;">
					<input type='button' id='special_update' name='special_update' value="修改" />
				</td>
			</tr>
		</table>
		</div>
		</form>
		
	<?php include dirname(__FILE__).'/../include/footer.phtml';?>