<div id='learnmore'>
	<div id='learnmore-menu'>
		<div>
				<img src='/images/learnmore-os.png' border="0" usemap="#Map" class='zoompng'>
<map name="Map">
  <area shape="rect" coords="26,138,95,191" href="/tools/blackberrydownload">
  <area shape="rect" coords="100,138,169,191" href="/tools/wmdownload">
  <area shape="rect" coords="176,138,245,191" href="http://m.k.ai">
  <area shape="rect" coords="176,80,245,133" href="/tools/androiddownload">
  <area shape="rect" coords="100,80,169,133" href="/tools/s60download">
  <area shape="rect" coords="26,80,95,133" href="/tools/iphonedownload">
</map>
			<div style='margin-top:-10px;!margin-top:-15px;'><img src='/images/learnmore-bottom.png'></div>	
		</div>
		<div id='learnmore-text' >
		<div id='learnmore-message'>下载开开到你的手机上
开开已经支持iPhone, Android，Windows Mobile, Blackberry, Symbian系列等智能手机系统。找不到适用平台？你也可以访问我们的手机WAP网站m.k.ai。</div></div>
	</div>
	<div id='learnmore-checkin' class='learnmore_backup' message='在你去的每一个地点签到吧，不管是你频繁光顾的餐厅、商场、剧院，还是偶尔到此一游的天涯海角、雪山戈壁！记录自己的足迹，并让朋友们分享你的发现。'>签到：我在这里</br><img src='/images/learnmore-checkin.png' class='pngfix'></div>
	<div id='learnmore-tips' class='learnmore_backup' message='如果对你停留的地点有经验，秘诀，甚至心情，想分享给你的朋友和同来此地的其他人，就用手机留下一句小贴士吧。从现在起，用自己的视角和发现，为城市增加注脚！'>贴士：分享我的发现</br><img src='/images/learnmore-tips.png' class='pngfix'></div>	
	<div id='learnmore-special' class='learnmore_backdown' message='如果你在某个地点的签到次数比其他人多，你就能成为那儿的“掌门”，所有在那签到的人都将仰望你。当然，一旦别人签的比你多，你的掌门就会被夺走。想成为掌门，必须有自己的真实头像。'>成为掌门、享受优惠</br><img src='/images/learnmore-special.png' class='pngfix'></div>
	<div id='learnmore-karma' class='learnmore_backdown' message='在开开社区里，越受欢迎的用户，Karma就会越高。开开希望每一位成员热情、友善、乐于分享：当你登陆、签到/吼吼/发贴士、关注别人、邀请/增加好友时，你的karma就会上升。'>积累Karma值</br><img src='/images/learnmore-karma.png' class='pngfix'></div>
	<div id='learnmore-remark' class='hide'>下载开开到你的手机上
开开已经支持iPhone, Android，Windows Mobile, Blackberry, Symbian系列等智能手机系统。找不到适用平台？你也可以访问我们的手机WAP网站m.k.ai。
	</div>
</div>