<h2>1、把“分享到开开”添加到鼠标右键菜单</h2>
	    	    <div class='shareContent'>点此直接运行<a href='/html/share.reg'>分享到开开</a>脚本，或下载<a href='/html/share.zip'>zip</a>文件再点击运行压缩包内的reg文件。</div>
	    	    <h2>2、在浏览器中添加“分享到开开”按钮</h2>
	    	    <div class='shareContent'>
	    	    <a href="javascript:var d=document,w=window,f='{BETTER_BASE_URL}/share',l=d.location,e=encodeURIComponent,p='?status_text='+e(w.getSelection?w.getSelection().toString():d.getSelection?d.getSelection():d.selection.createRange().text);a=function(){if(!w.open(f+p,'sharer','toolbar=0,status=0,resizable=0,width=550,height=320'))l.href=f+p};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else{a()}void(0)"><img src='images/kailogo.png' alt='分享到开开' /></a>
	    	    IE浏览器：右键单击本按钮，选择“添加到收藏夹” <br />
火狐浏览器：右键单击本按钮，选择“将此链接加为书签” <br />
谷歌浏览器&火狐浏览器：左键拖动本按钮到书签栏
	    	    </div>
	    	    <h2>3、在Blog上添加“分享到开开”按钮</h2>
	    	    <div class='shareContent'>通过将我们提供的以下代码复制并粘贴到你的博客文章或者模板，就可以轻松实现同步分享到开开。
	    	    
	    	    <div class='shareIcons'>
	    	    <div class='label'>图标</div>
		    	    <div class='shareIcon'>
		    	    	<a href="javascript:var d=document,w=window,f='{BETTER_BASE_URL}/share',l=d.location,e=encodeURIComponent,p='?status_text='+e(w.getSelection?w.getSelection().toString():d.getSelection?d.getSelection():d.selection.createRange().text);a=function(){if(!w.open(f+p,'sharer','toolbar=0,status=0,resizable=0,width=550,height=320'))l.href=f+p};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else{a()}void(0)"><img src='images/kailogo.png' alt='分享到开开' /></a>
		    	    </div>
		    	    <div class='shareLinks'>
		    	    	<input type='text' class='iShareLink' value="&lt;a href=&quot;javascript:var d=document,w=window,f='{BETTER_BASE_URL}/share',l=d.location,e=encodeURIComponent,p='?status_text='+e(w.getSelection?w.getSelection().toString():d.getSelection?d.getSelection():d.selection.createRange().text);a=function(){if(!w.open(f+p,'sharer','toolbar=0,status=0,resizable=0,width=550,height=320'))l.href=f+p};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else{a()}void(0)&quot;&gt;&lt;img src='{BETTER_BASE_URL}/images/kailogo.png' alt='分享到开开' /&gt;&lt;/a&gt;" />
		    	    </div>
	    	    
	    	    <div class='label'>文字链接</div>
		    	    <div class='shareIcon'>
		    	    	<a href="javascript:var d=document,w=window,f='{BETTER_BASE_URL}/share',l=d.location,e=encodeURIComponent,p='?status_text='+e(w.getSelection?w.getSelection().toString():d.getSelection?d.getSelection():d.selection.createRange().text);a=function(){if(!w.open(f+p,'sharer','toolbar=0,status=0,resizable=0,width=550,height=320'))l.href=f+p};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else{a()}void(0)">分享到开开</a>
		    	    </div>
		    	    <div class='shareLinks'>
		    	    	<input type='text' class='iShareLink' value="&lt;a href=&quot;javascript:var d=document,w=window,f='{BETTER_BASE_URL}/share',l=d.location,e=encodeURIComponent,p='?status_text='+e(w.getSelection?w.getSelection().toString():d.getSelection?d.getSelection():d.selection.createRange().text);a=function(){if(!w.open(f+p,'sharer','toolbar=0,status=0,resizable=0,width=550,height=320'))l.href=f+p};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else{a()}void(0)&quot;&gt;分享到开开&lt;/a&gt;" />
		    	    </div>
	    	    
	    	    <div class='label'>图标和文字链接</div>
		    	    <div class='shareIcon'>
		    	    	<a href="javascript:var d=document,w=window,f='{BETTER_BASE_URL}/share',l=d.location,e=encodeURIComponent,p='?status_text='+e(w.getSelection?w.getSelection().toString():d.getSelection?d.getSelection():d.selection.createRange().text);a=function(){if(!w.open(f+p,'sharer','toolbar=0,status=0,resizable=0,width=550,height=320'))l.href=f+p};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else{a()}void(0)"><img src='images/kailogo.png' alt='分享到开开' />分享到开开</a>
		    	    </div>
		    	    <div class='shareLinks'>
		    	    	<input type='text' class='iShareLink' value="&lt;a href=&quot;javascript:var d=document,w=window,f='{BETTER_BASE_URL}/share',l=d.location,e=encodeURIComponent,p='?status_text='+e(w.getSelection?w.getSelection().toString():d.getSelection?d.getSelection():d.selection.createRange().text);a=function(){if(!w.open(f+p,'sharer','toolbar=0,status=0,resizable=0,width=550,height=320'))l.href=f+p};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else{a()}void(0)&quot;&gt;&lt;img src='{BETTER_BASE_URL}/images/kailogo.png' alt='分享到开开' /&gt;分享到开开&lt;/a&gt;" />
		    	    </div>
	    	    <div class='clearfix'></div>
	    	    <div class='label' class="">图片链接</div>
	    	    	<div class='shareIcon'>
						<a href="javascript:var d=document,w=window,f='{BETTER_BASE_URL}/share',l=d.location,e=encodeURIComponent,p='?status_text='+e(w.getSelection?w.getSelection().toString():d.getSelection?d.getSelection():d.selection.createRange().text);a=function(){if(!w.open(f+p,'sharer','toolbar=0,status=0,resizable=0,width=550,height=320'))l.href=f+p};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else{a()}void(0)"><img src='images/share-button1.png' alt='分享到开开' /></a>
					</div>
		    	    <div class='shareLinks'>
		    	    <input type='text' class='iShareLink' value="&lt;a href=&quot;javascript:var d=document,w=window,f='{BETTER_BASE_URL}/share',l=d.location,e=encodeURIComponent,p='?status_text='+e(w.getSelection?w.getSelection().toString():d.getSelection?d.getSelection():d.selection.createRange().text);a=function(){if(!w.open(f+p,'sharer','toolbar=0,status=0,resizable=0,width=550,height=320'))l.href=f+p};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else{a()}void(0)&quot;&gt;&lt;img src='{BETTER_BASE_URL}/images/share-button1.png' alt='分享到开开' /&gt;&lt;/a&gt;" />
		    	    </div>	    	 	 <br />
		    	    	<div class='shareIcon'>
						<a href='javascript:window.open("{BETTER_BASE_URL}/{USERNAME}");void(0);''><img src='{BETTER_BASE_URL}/images/share-button2.png' alt='在开开上关注我' /></a>
					</div>
		    	    <div class='shareLinks'>
		    	    	<input type='text' class='iShareLink' value="&lt;a href='javascript:window.open(&quot;{BETTER_BASE_URL}/{USERNAME}&quot;);void(0);''&gt;&lt;img src='{BETTER_BASE_URL}/images/share-button2.png' alt='在开开上关注我' /&gt;&lt;/a&gt;" />
		    	    </div>	        	    	    	    
	    	    </div>
	    	    
	    	    <div class='clearfix'></div>
			</div>