<div class='left' style='width: 45%;'>
<h3 style='border-bottom:1px solid #CC3366'>关于我们</h3>
<p style='margin-top:10px;!margin-top:5px;'>苏州贝多科技有限公司是国内领先的手机应用软件开发商之一，致力开发基于位置的无线互联网服务。公司主要产品包括新一代位置网络(开开www.k.ai)，基于位置的手机社交网络服务（贝多www.bedo.cn），以及网络定位服务平台（驴博士www.lbs.org.cn）。公司及旗下产品曾先后获得硅谷红鲱鱼杂志2008年私有未上市最有潜力的科技全球百强公司（2008 Red Herring Global 100）、2008中国手机客户端软件十强、中国移动互联网应用十佳、索尼爱立信金枝奖最佳Mobile 2.0应用等多项业内荣誉。</p>
<p style='margin-top:10px;!margin-top:5px;'>我们的详细联络方式是：</p>
<p>苏州贝多科技有限公司</p>
<p>江苏苏州工业园区金鸡湖大道1355号</p>
<p>国际科技园151A，215021</p>
<p>联络email为：<a href='mailto:contact@k.ai'>contact@k.ai</a></p>
<p>公司电话：0512-62888255</p>
</div>

<div class='right'  style='width: 45%;'>
<h3 style='border-bottom:1px solid #CC3366'>什么是开开</h3>
<p>开开k.ai是新一代的位置网络，开开帮助你与朋友们分享位置、交流心得，并用全新的方法探索身边的城市。</p>
<p style='margin-top:10px;!margin-top:5px;'>通过签到，你可以向朋友们分享当前的位置，让他们知道在哪里可以找到你，或者给你各种各样的贴士和建议。也可以用贴士分享自己在此时此地的心得感触。勋章给你游历城市的小小惊喜。如果你成为了某地点的掌门，掌柜很可能会送你一份神秘礼物。</p>
</div>