<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta name="viewport" content="width=device-width; initial-scale=1.4; minimum-scale=1.0; maximum-scale=2.0"/>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><?php echo $this->lang->global->meta->title;?></title>
	<meta name="description" content="开开K.ai是新一代的位置网络，也是真实的白领社交网络。在开开签到，你能够找到朋友、分享贴士，并用全新的方法探索身边的城市。同时还可以争掌门、赢勋章、玩寻宝" /> 
	<?php include_once(dirname(__FILE__).'/../include/textcss.phtml');?>
</head>
<body>
<?php include_once(dirname(__FILE__).'/../include/header.php')?>
<?php if(Better_Config::getAppConfig()->market->polo->wapswitch){?>
<a href='<?php echo $this->poloacturl;?>'><img src='/images/polo/wap_top.png' border='0' /></a>
<?php }?>
<div class="content">
		
	<div id="activities">
			     <?php echo $this->lang->mobile->index->aboutkai;?>
			     <div class='tline'></div>
			     <?php echo $this->lang->mobile->index->joinkai;?>
	</div>
</div>
<div id='havenotkaiacount'><?php echo $this->lang->mobile->wap->havenotkaiacount; ?></div>
<?php include_once(dirname(__FILE__).'/../include/loginfooter.phtml');?>
</body>
</html>