	<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
	
	<body>
		<div class='content_wraper'><div id="list">
			<div style='width: 100%; text-align:left; background-color:#D3DCE3;'>[<a href='/admin/publish' class='left'>客户端产品管理</a>] [<a href='/admin/publish/phone' class='left'>手机机型管理</a>] </div>
		<div style="margin: 10px auto;">
			<form action="<?php echo $this->admin_url;?>/publish/phone" id="search_form">
			<table class='kai_table'>
			<tr><th colspan='6' class='center'>搜索</th></tr>
			<tr>
				<td>名称关键字:</td>
				<td><input type="text" name="name_keyword" id="name_keyword" value="<?php echo $this->params['name_keyword'];?>" /></td>
				<td>品牌:</td>
				<td>
					<select name="brand" id="brand">
						<option value="0">所有</option>
						<?php foreach($this->brands as $brand){?>
							<option value="<?php echo $brand['bid']; ?>" <?php echo $brand['bid']==$this->params['brand']? "selected":"" ;?> ><?php echo $brand['name']?></option>
						<?php }?>
					</select>
				</td>
				<td>操作系统:</td>
				<td>
					<select name="os" id="os">
						<option value="0">所有</option>
						<?php foreach($this->oss as $os){?>
							<option value="<?php echo $os['oid']; ?>" <?php echo $os['oid']==$this->params['os']? "selected":"" ;?> ><?php echo $os['name']?></option>
						<?php }?>
					</select>
				</td>
			</tr>
			<tr>
				<td colspan='6' class='center'>
					<input type='submit' value='搜索(s)' accesskey='s' />
					<input type='button' value='清空搜索结果(r)' accesskey='r'  id='btnReset' />
					<input type='hidden' name='page' id='page' value='<?php echo $this->params['page'];?>' />
					<input type='hidden' name='reload' id='reload' value='0' />
				</td>
			</tr>

			</table>		
			</form>
		</div> 
		
		<div style="margin: 10px auto;">
			<form action="" id="add_form">
			<table class='kai_table'>
			<tr><th colspan='6' class='center'>添加新机型</th></tr>
			<tr>
				<td>名称:</td>
				<td><input type='text' name='name' id='name' value='' /></td>
				<td>描述:</td>
				<td><input type='text' name='desc' id='desc' value='' /></td>
				<td>操作系统:</td>
				<td>
					<select name="oid" id="oid">
						<?php foreach($this->oss as $os){?>
							<option value="<?php echo $os['oid']; ?>"><?php echo $os['name']?></option>
						<?php }?>
					</select>
				</td>
			</tr>	
			<tr>	
				<td>品牌:</td>
				<td>
					<select name="bid" id="bid">
						<?php foreach($this->brands as $brand){?>
							<option value="<?php echo $brand['bid']; ?>"><?php echo $brand['name']?></option>
						<?php }?>
					</select>
				</td>
				<td>图片:</td>
				<td><input type="text" name="img" id="img" value="" /></td>
				<td colspan="3"></td>
			</tr>				
				
			<tr>
				<td colspan='6' class='center'>
					<input type='button' id="btnAddPhone" value='添加'/>
					<input type='reset' value='重置'/>
				</td>
			</tr>
			</table>		
			</form>
		</div> 
		
		

			<table cellspacing="0" class='kai_table'>	
				<tr>
					<td colspan='10' class='pager'>
					<?php echo $this->paginator();?>
					</td>
				</tr>					
				<tr>
					<th></th>
					<th>名称</th>
					<th>描述</th>
					<th>品牌</th>
					<th>操作系统</th>
					<th>图片</th>
				</tr>
		
				<?php if ($this->count>0) { ?>
				<?php $i = 0; ?>
				<?php foreach ($this->rows as $row) {?>
				<tr class='<?php echo fmod($i++,2)==0 ? 'light' : 'dark';?> message_row'>
					<td><input type='checkbox' name='pids[]'  value='<?php echo $row['pid'];?>' /></td>
					<td class='center' id="<?php echo $row['pid']?>_name"><?php echo $row['name']?></td>
					<td class='center' id="<?php echo $row['pid']?>_desc"><?php echo $row['desc']?></td>
					<td class='center' id="<?php echo $row['pid']?>_bid"><?php echo $row['bname']?></td>
					<td class='center' id="<?php echo $row['pid']?>_oid" oid='<?php echo $row['oid'];?>'><?php echo $row['oname']?></td>
					<td class='center' id="<?php echo $row['pid']?>_img"><img src="/files/download/images/<?php echo $row['img'];?>" /></td>
				</tr>
				<?php } ?>
				<tr>
					<td colspan='10' class='center'>
					<input type='button' id='chooseAll' name='chooseAll'  value='全选(a)' accesskey='a' />
					<input type='button' id='chooseNone' name='chooseNone' value='全不选(n)' accesskey='n' />
					<input type='button' id='chooseReverse' name='chooseReverse' value='反选(v)' accesskey='v' />
				</td></tr>
				<tr><td colspan='10'>
					<input type='button' id='btnDelPhone' name='btnDelPhone' value='删除所选(d)' accesskey='d' />
					</td>
				</tr>					
				<?php } else {  ?>
				<tr>
					<td colspan='10' class='error center'>
					没有找到任何数据
					</td>
				</tr>				
				<?php } ?>
				<tr>
					<td colspan='10' class='pager'>
					<?php echo $this->paginator();?>
					</td>
				</tr>
			</table>	
		</div>
		
	</div> 
	<?php include dirname(__FILE__).'/../include/footer.phtml';?>