<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta name="viewport" content="width=device-width; initial-scale=1.4; minimum-scale=1.0; maximum-scale=2.0"/>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><?php echo $this->lang->global->meta->title;?></title>
	<?php include_once(dirname(__FILE__).'/../include/textcss.phtml');?>
</head>
<body>
	<?php include_once(dirname(__FILE__)."/../include/logo.phtml")?>
	<div id="headinfo">
		<?php 
    		if( $this->user['uid'] > 0 ){
				echo "<a href=\"/mobile/user?uid=".$this->user["uid"]."\" >".$this->user["nickname"]."</a>@";
				if( (int)($this->lastcheckin['poi']['poi_id']) < 1 ){
					echo "<a href=\"/mobile/search\">".$this->lang->mobile->global->whereplace."</a>";
				}else{
					echo "<a href=\"/mobile/place?pid=".$this->lastcheckin['poi']['poi_id']."\">".$this->lastcheckin['poi']['name']."</a>";
				}
				echo "<hr/>";
			}
		?>	
	</div>
	<div id='content'>
	<?php echo "<a href=\"/mobile/setting\">".$this->lang->global->nav->setting."</a>->".$this->lang->setting->menu->avatar;?>
	<div id="avatar">
		<div id="error">
		<?php 
			if( $this->err['has_err'] && strlen($this->err['err']) )
				echo $this->err['err']."<br/>"; 
		?>
		</div>
		<?php
			if( $this->user['avatar'] ) 
				echo $this->lang->setting->avatar->have_tips;
			else
				echo $this->lang->setting->avatar->havent_tips;
		?>
		<form enctype="multipart/form-data" method='post' action='/mobile/setting/update' id=''>
    		<img src="<?php echo $this->user['avatar_normal'];?>" width="96" alt="" class="now_avatar"/><br/>
			<input type='file' name='attach' id='attach' value="<?php echo $this->lang->setting->avatar->file_tips;?>" /><br/>
			<input type='hidden' name='avatar' id='avatar' value="<?php echo $this->user['avatar'];?>" />
			<input type='hidden' name='todo' id='todo' value='avatar' />			
			<input value="<?php echo $this->lang->setting->avatar->upload_tips;?>" type="submit" id="modify" />
		</form>
		<?php if( 0 && $this->user['avatar'] ) {  ?>
		<form enctype="multipart/form-data" method='post' action='/mobile/setting/update' id=''>
			<input type='hidden' name='avatar' id='avatar' value="<?php echo $this->user['avatar'];?>" />
			<input type='hidden' name='todo' id='del_avatar' value='del_avatar' />
			<input value="<?php echo $this->lang->setting->avatar->delete_tips;?>" type="submit" id="delete" /><br/>
		</form>
		<?php }?>
		
	</div>
	</div>
	<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>
</body>
</html>
