<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta name="viewport" content="width=device-width; initial-scale=1.4; minimum-scale=1.0; maximum-scale=2.0"/>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><?php echo $this->lang->global->meta->title;?></title>
	<?php include_once(dirname(__FILE__).'/../include/textcss.phtml');?>
</head>
<body>
	<?php include_once(dirname(__FILE__)."/../include/logo.phtml")?>
	<div id="headinfo">
		<?php 
    		if( $this->user['uid'] > 0 ){
				echo "<a href=\"/mobile/user?uid=".$this->user["uid"]."\" >".$this->user["nickname"]."</a>@";
				if( (int)($this->lastcheckin['poi']['poi_id']) < 1 ){
					echo "<a href=\"/mobile/search\">".$this->lang->mobile->global->whereplace."</a>";
				}else{
					echo "<a href=\"/mobile/place?pid=".$this->lastcheckin['poi']['poi_id']."\">".$this->lastcheckin['poi']['name']."</a>";
				}
			
			}
		?>	
	</div>
	<div id='content'>
	<?php echo "<a href=\"/mobile/setting\">".$this->lang->global->nav->setting."</a>->".$this->lang->setting->menu->bedobind;?>
	<div id="error">
		<?php
			if(strlen($this->tip) ) {
				echo $this->tip."<br/>";
			} 
		?>
	</div> 
	<form method='post' action='/mobile/setting/update'>
		<div class="row">
		  <label for="bedo"><?php echo $this->lang->setting->import->bedo;?></label>
		  <div class="field">
		  	 <input type="text" style="width: 150px;" id="jid" name="jid" value="" />
		  	 <span id='err_jid' class='err'><?php echo $this->err['err_jid'];?></span>
		  </div>
		</div>
		<div class="row">
		  <label for="password"><?php echo $this->lang->setting->import->password;?></label>
		  <div class="field">
		  	  <input type="password" style="width: 150px;" id="password" name="password" value="" />
		  	  <span id='err_password' class='err'><?php echo $this->err['err_password'];?></span>
		  </div>
		  <div class="clearfix"></div>
		</div>
		   <br />
		  <input type="submit" value="<?php echo $this->lang->setting->im->button_tips;?>" class="save btn" id='btnBind' />
		  <input type='hidden' name='todo' id='todo' value='bedobind' />
		  <br/>
	</form>
	</div>
	<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>
</body>
</html>
