<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta name="viewport" content="width=device-width; initial-scale=1.4; minimum-scale=1.0; maximum-scale=2.0"/>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><?php echo $this->lang->global->meta->title;?></title>
	<?php include_once(dirname(__FILE__).'/../include/textcss.phtml');?>
</head>
<body>
	<?php include_once(dirname(__FILE__)."/../include/logo.phtml")?>
	<div id="headinfo">
		<?php 
    		if( $this->user['uid'] > 0 ){
				echo "<a href=\"/mobile/user?uid=".$this->user["uid"]."\" >".$this->user["nickname"]."</a>@";
				if( (int)($this->lastcheckin['poi']['poi_id']) < 1 ){
					echo "<a href=\"/mobile/search\">".$this->lang->mobile->global->whereplace."</a>";
				}else{
					echo "<a href=\"/mobile/place?pid=".$this->lastcheckin['poi']['poi_id']."\">".$this->lastcheckin['poi']['name']."</a>";
				}				
			}
		?>	
	</div>
	<div id='content'>
		<div id="error">
			<?php 
				if( strlen($this->err['err']) > 0 )
					//echo "<font color=\"red\">".$this->err['err']."</font><br/>";
					echo  $this->err['err'];
			?>
		</div>
		<table>
			<tr align="left"><td><a href="/mobile/setting/basic"><?php echo $this->lang->setting->menu->basic;?></a></td></tr><?php         	
	        	if($this->user['status']['source']!='IFN' and $this->user['status']['source']!='IPN'){?>
			<tr align="left"><td><a href="/mobile/setting/avatar"><?php echo $this->lang->setting->menu->avatar;?></a></td></tr><?php }?>
			<tr align="left"><td><a href="/mobile/setting/password"><?php echo $this->lang->setting->menu->password;?></a></td></tr>	
			<!-- 	
			<tr align="left"><td><a href="/mobile/setting/privacy"><?php echo $this->lang->setting->menu->privacy;?></a></td></tr>
			 -->
			<tr align="left"><td><a href="/mobile/setting/province"><?php echo $this->lang->setting->menu->city;?></a></td></tr>
			<?php if ($this->showBedoImport) {?>
			<tr align="left"><td><a href="/mobile/setting/bedoimport"><?php echo $this->lang->setting->menu->bedoimport;?></a></td></tr>
			<?php } else {?>
			<tr align="left"><td><a href="/mobile/setting/bedobind"><?php echo $this->lang->setting->menu->bedoimport;?></a></td></tr>
			<?php }?>
		</table>	
	</div>
	<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>
</body>
</html>
