<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta name="viewport" content="width=device-width; initial-scale=1.4; minimum-scale=1.0; maximum-scale=2.0"/>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><?php echo $this->lang->global->meta->title;?></title>
	<?php include_once(dirname(__FILE__).'/../include/textcss.phtml');?>
</head>
<body>
	<?php include_once(dirname(__FILE__)."/../include/logo.phtml")?>
	<div id="headinfo">
		<?php 
    		if( $this->user['uid'] > 0 ){
				echo "<a href=\"/mobile/user?uid=".$this->user["uid"]."\" >".$this->user["nickname"]."</a>@";
				if( (int)($this->lastcheckin['poi']['poi_id']) < 1 ){
					echo "<a href=\"/mobile/search\">".$this->lang->mobile->global->whereplace."</a>";
				}else{
					echo "<a href=\"/mobile/place?pid=".$this->lastcheckin['poi']['poi_id']."\">".$this->lastcheckin['poi']['name']."</a>";
				}
				echo "<hr/>";
			}
		?>	
	</div>
	<?php echo "<a href=\"/mobile/setting\">".$this->lang->global->nav->setting."</a>->".$this->lang->setting->password->title."<br/>";?>
	<div id="error">
		<?php 
			if( $this->err['has_err'] || strlen($this->err['err']) )
				echo $this->err['err']."<br/>"; 
		?>
	</div> 
	<div id="set_form">	
	   	<form method='post' action='/mobile/setting/update'>
	   		<label for="pass"><?php echo $this->lang->setting->password->new->title;?></label>
	    	<div class="field">
				<input type="password" size="30" id="pass" name="pass" class='binput' value=""/><br/>
		 		<span class="help">(<?php echo $this->lang->setting->password->new->tips;?>)</span>
			</div>
			<label for="repass"><?php echo $this->lang->setting->password->again->title;?></label>
	    	<div class="field">
		   		<input type="password" size="30" id="repass" name="repass" class='binput' value=""/><br/>		   		
			</div>
			<br>
			<input type='hidden' name='todo' id='todo' value='password' />
	    	<input type="submit" id="btnPwd" value="<?php echo $this->lang->setting->password->button_tips;?>" class="btn save"/>
		</form>
	</div>
	
	<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>
</body>
</html>
