	<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
	
	<body>
		<div class='content_wraper'><div id="list">
		<div style='width: 100%; text-align:left; background-color:#D3DCE3;'>[<a href='/admin/denounce' class='left'>举报的微博</a>] [<a href='/admin/denounce/user' class='left' style="color:#FF0000;font-weight:bold;">举报的用户</a>] [<a href='/admin/denounce/poi' class='left'>举报的POI</a>]</div>
		<div style="margin: 10px auto;">
			<form action="<?php echo $this->admin_url;?>/denounce/user" id="search_form">
			<table class='kai_table'>
			<tr><th colspan='6' class='center'>搜索</th></tr>
			<tr>
				<td>被举报人ID:</td>
				<td><input type='text' name='keyword' id='keyword' value='<?php echo $this->params['keyword'];?>' /></td>
				<td>举报人ID:</td>
				<td colspan='3'><input type='text' name='reason' id='reason' value='<?php echo $this->params['reason'];?>' /></td>
			</tr>			
			<tr>
				<td>时间范围:</td>
				<td colspan='3'>
				从 <input type='text' name='from' id='from' value='<?php echo $this->params['from'];?>' readonly='readonly' />
				到 <input type='text' name='to' id='to' value='<?php echo $this->params['to'];?>' readonly='readonly' />
				</td>

				<td>每页结果数:</td>
				<td>
				<select name='page_size' id='page_size'>
					<option value='<?php echo BETTER_PAGE_SIZE;?>' <?php echo $this->params['page_size']==BETTER_PAGE_SIZE ? ' selected="selected"' : '';?>>默认(<?php echo BETTER_PAGE_SIZE;?>)</option>
					<option value='50' <?php echo $this->params['page_size']==50 ? ' selected="selected"' : '';?>>50</option>
					<option value='100' <?php echo $this->params['page_size']==100 ? ' selected="selected"' : '';?>>100</option>
					<option value='99999999' <?php echo $this->params['page_size']==99999999 ? ' selected="selected"' : '';?>>全部</option>
				</select>
				</td>
			</tr>
			<tr>
				<td>状态:</td>
				<td colspan='10'>
					<select name='status' id='status'>
						<option value=''>所有</option>
						<option value='in_progress' <?php echo $this->params['status']=='in_progress'? "selected":"" ;?> >处理中</option>
						<option value='have_progress' <?php echo $this->params['status']=='have_progress'? "selected":"" ;?>>已处理</option>
						<option value='no_progress' <?php echo $this->params['status']=='no_progress'? "selected":"" ;?>>未处理</option>
					</select>
				</td>
			</tr>			
			<tr>
				<td colspan='6' class='center'>
					<input type='submit' value='搜索(s)' accesskey='s' />
					<input type='button' value='清空搜索结果(r)' accesskey='r'  id='btnReset' />
					<input type='hidden' name='page' id='page' value='<?php echo $this->params['page'];?>' />
					<input type='hidden' name='reload' id='reload' value='0' />
					
					<input type='hidden' name='dtype' id='dtype' value='user'>
				</td>
			</tr>
			</table>		
			</form>
		</div>

			<table cellspacing="0" class='kai_table'>	
				<tr>
					<td colspan='10' class='pager'>
					<?php echo $this->paginator();?>
					</td>
				</tr>					
				<tr>
					<th></th>
					<th class='nowrap'>举报原因</th>
					<th>被举报人</th>
					<th>举报人</th>
					<th>举报时间</th>
					<th>状态</th>
					<!-- <th class='nowrap'>处理结果</th>
					<th>处理人</th>
					<th class='nowrap'>处理时间</th> -->
				</tr>
		
				<?php if ($this->count>0) { ?>
				<?php $i = 0; ?>
				<?php foreach ($this->rows as $row) {?>
				<tr class='<?php echo fmod($i++,2)==0 ? 'light' : 'dark';?> message_row'>
					<td width='40'>
					<input type='checkbox' name='ids[]'  value='<?php echo $row['id'];?>' bid='<?php echo $row['denounce_bid'];?>'>
					</td>
					<td class='center'><?php echo $row['denounce_reason'] ;?></td>
					<td class='center'><a href='/<?php echo $row['user']['username'];?>' target='_blank'><?php echo $this->highlight($row['denounce_uid'], $this->params['keyword']).'/'.$row['user']['username'];?></a></td>
					<td class='center'><?php echo $this->highlight($row['uid'], $this->params['reason']);?></td>
					<td class='center'><?php echo date('Y-m-d H:i:s', $row['dateline']+BETTER_8HOURS);?></td>
					<td class='center'><?php echo $row['status'];?></td>
					<!-- <td class='center'><?php echo $row['act_result'];?></td>
					<td class='center'><?php echo $row['admin_uid'];?></td>
					<td class='center'><?php echo $row['act_time']? date('Y-m-d H:i:s', $row['act_time']+BETTER_8HOURS) : '';?></td>  -->
				</tr>
				<?php } ?>
				<tr>
					<td colspan='10' class='center'>
					<input type='button' id='chooseAll' name='chooseAll'  value='全选(a)' accesskey='a' />
					<input type='button' id='chooseNone' name='chooseNone' value='全不选(n)' accesskey='n' />
					<input type='button' id='chooseReverse' name='chooseReverse' value='反选(v)' accesskey='v' />
					</td>
				</tr>
				<tr><td colspan='10'>
					将状态改为：
					<select name='todo' id='todo'>
						<option value='in_progress'>处理中</option>
						<option value='have_progress'>已处理</option>
						<option value='no_progress'>未处理</option>
					</select>
					<input type='button' id='btnTodo' value='确定(d)' accesskey='d' />
					
					</td>
				</tr>	
				<?php } else {  ?>
				<tr>
					<td colspan='10' class='error center'>
					没有找到任何数据
					</td>
				</tr>				
				<?php } ?>
				<tr>
					<td colspan='10' class='pager'>
					<?php echo $this->paginator();?>
					</td>
				</tr>
			</table>	
		</div>
		</div>
		
	<?php include dirname(__FILE__).'/../include/footer.phtml';?>