	<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
	
	<body>
	<?php include_once(dirname(__FILE__).'/../include/poifunctions.phtml');?>
	<form action='<?php echo $this->admin_url;?>/poi/add' method='post'>
	<div id="list">
		<table class="kai_table">
			<tr>
				<th colspan='4' style="text-align:center;">创建POI</th>
			</tr>
			<tr>	
				<td colspan='4' align='center' style='color: red; text-align: center;'><?php echo $this->message;?></td>
			</tr>
			<tr>
				<td>名称：</td>
				<td><input type='text' id="poi_name" name='poi_name' value="" /></td>
			</tr>
			<tr>
				<td>地址：</td>
				<td colspan='3'><input type='text' size='40' id='poi_address' name='poi_address' value="" /></td>
			</tr>
			<tr>
				<td>电话：</td>
				<td colspan='3'><input type='text' id='poi_tell' name='poi_tell' value="" /></td>
			</tr>
			<tr>
				<td>分类：</td>
				<td>
					<select id="poi_cate" name="poi_cate">
						<?php
							foreach ($this->categories as $k=>$val) { ?>
							<option value="<?php echo $k;?>" <?php echo $this->poiDetail['category_id']==$k ? 'selected=\'selected\'' : '';?>><?php echo $val;?></option>
						<?php 		
							}
						?>
						
					</select>
				</td>
			</tr>
			<tr>
				<td>城市：</td>
				<td><input type='text' id="poi_city" name='poi_city' value="" /></td>
			</tr>
			<tr>
				<td>标签：</td>
				<td><input type='text' id="poi_label" name='poi_label' value="" /></td>
			</tr>
			<tr>
				<td>等级：</td>
				<td><input type='text' id="poi_level" name='poi_level' value="" /></td>
			</tr>
			<tr>
				<td>地点(经纬度)：</td>
				<td colspan='3'>
				<input type='text' id='poi_ll' name='poi_ll' />(优先级高，手动输入则拖动地图无效， 格式: 经度,纬度，之间用,隔开)<br>
					<div class="map">
						<div id="admin_create_map" style="width: 450px; height: 260px; margin: 0;border:1px solid #ddd;" class='map'></div>
						<input type="hidden" value="39.917" id="poi_lat" name='poi_lat'/>
						<input type="hidden" value="116.397" id="poi_lon"  name='poi_lon'/>
					</div>
				</td>
			</tr>
			<tr>
				<td colspan='4' style="text-align:center;">
					<input type='submit' id='btnCreate' name='create' value="创建" />
				</td>
			</tr>
		</table>
		
		<div style="margin-top: 30px;">
			<table width="100%" height='100'>
				<tr><th colspan='10' align='left'>手动开启POI</th></tr>
				<tr>
					<td align='left' width='250'>需开启的POI ID（中间用逗号（,）隔开）：</td>
					<td align='left'><input type="text" id="manu_pids" size='100'/></td>
				</tr>
				<tr>
					<td colspan='10' align='left'><input type="button" id="manu_btn" value="开启"/></td>
				</tr>
			</table>	
		</div>
		</div>
		</form>
		
		<script type="text/javascript">
		if (GBrowserIsCompatible()) {
			
			lat =  39.917;
			lon =  116.397;
			
			map = new GMap2(document.getElementById("admin_create_map"), {size:new GSize(600, 300)});
			map.setCenter(new GLatLng(lat, lon), 6);
			map.addControl(new GSmallMapControl());
			map.enableScrollWheelZoom();
			
	        marker = new GMarker(map.getCenter(), {draggable: true});
	
	        GEvent.addListener(marker, "dragend", function(){
	        	var latlon = marker.getLatLng();
				
				$("#poi_lon").val(latlon.lng());
				$("#poi_lat").val(latlon.lat());
				
	        });
	        map.addOverlay(marker);
	
		}	
		</script>
		
	<?php include dirname(__FILE__).'/../include/footer.phtml';?>