	<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
	
	<body>
		<div class='content_wraper'><div id="list">
		<?php include_once(dirname(__FILE__).'/../include/poifunctions2.phtml');?>
		<div style="margin: 10px auto;">
			<form action="<?php echo $this->admin_url;?>/poi/getpois" id="search_form">
			<table class='kai_table'>
			<tr><th colspan='6' class='center'>搜索</th></tr>
			<tr>
				<td>POI ID</td>
				<td colspan="6">
					<input type='text' name='poi_id' id='poi_id' value='<?php echo $this->params['poi_id'];?>' />
					<input type='hidden' name='seach_mode' id='seach_mode' value='1' />
				</td>
			</tr>	
			<tr>
				<td>时间范围:</td>
				<td colspan='3'>
				从 <input type='text' name='from' id='from' value='<?php echo $this->params['from'];?>' readonly='readonly' />
				到 <input type='text' name='to' id='to' value='<?php echo $this->params['to'];?>' readonly='readonly' />
				</td>
				<td>每页结果数:</td>
				<td>
				<select name='page_size' id='page_size'>
					<option value='<?php echo BETTER_PAGE_SIZE;?>' <?php echo $this->params['page_size']==BETTER_PAGE_SIZE ? ' selected="selected"' : '';?>>默认(<?php echo BETTER_PAGE_SIZE;?>)</option>
					<option value='50' <?php echo $this->params['page_size']==50 ? ' selected="selected"' : '';?>>50</option>
					<option value='100' <?php echo $this->params['page_size']==100 ? ' selected="selected"' : '';?>>100</option>
					<option value='99999999' <?php echo $this->params['page_size']==99999999 ? ' selected="selected"' : '';?>>全部</option>
				</select>
				</td>
			</tr>		
			<tr>
				<td colspan='6' class='center'>
					<input type='submit' value='搜索(s)' accesskey='s' />
					<input type='button' value='清空搜索结果(r)' accesskey='r'  id='btnResetCheck' />
					<input type='hidden' name='page' id='page' value='<?php echo $this->params['page'];?>' />
					<input type='hidden' name='reload' id='reload' value='0' />
				</td>
			</tr>
			</table>		
			</form>
		</div>
		
			<table cellspacing="0" class='kai_table'>	
				<tr>
					<td colspan='15' class='pager'>
					<?php echo $this->paginator(false);?>
					</td>
				</tr>
				<tr>
					<th width='20'></th>
					<th class='nowrap'>POI ID</th>
					<th class='nowrap'>用户ID</th>
					<th class='nowrap'>详细修改内容</th>
					<th class='nowrap' style="miax-width:8px;">修改时间</th>
					<th class='nowrap' style="min-width:50px">状态</th>
					<th class='nowrap' style="min-width:75px">操作</th>										
				</tr>
		
				<?php if ($this->count>0) { ?>
				<?php $i = 0; ?>
				<?php foreach ($this->rows as $row) {?>
				<tr class='<?php echo fmod($i++,2)==0 ? 'light' : 'dark';?> message_row'>
					<td>
						<input type='checkbox' name='poids[]'  value='<?php echo $row['id'];?>' />
					</td>
					<td class='center'><a href='/poi?id=<?php echo $row['poi_id'];?>' target='_blank'><?php echo $this->highlight($row['poi_id'], $this->params['namekeyword']);?></a></td>
					<td class='center'><?php echo $row['uid']?></td>
					<td class='left' style="width:450px;"><?php echo $row['change_content']; ?></td>	
					<td class='center'><?php echo date('Y-m-d H:i:s',$row['dateline']+8*3600)?></td>
					<td class='center'><?php echo $row['checked'];?></td>
					<td class='center'>
						<a class="viewdetail" href='<?php echo $this->admin_url;?>/poi/checkpoi?check_id=<?php echo $row['id']?>'>查看详细</a><br>
						<a class="checkSuccess" href='javascript:void(0);' onclick="checkHandler('<?php echo $row['id'];?>',1)">审核通过</a><br>
						<a class="checkSuccess" href='javascript:void(0);' onclick="checkHandler('<?php echo $row['id'];?>',2)">审核不通过</a><br>						
						<a class='checkFailure'  href='javascript:void(0);' onclick="deleteCheckHandler('<?php echo $row['id'];?>')">删除</a><br>
					</td>
				</tr>
				<?php } ?>
				<tr>
					<td colspan='15' class='center'>
						<input type='button' id='chooseAll' name='chooseAll'  value='全选(a)' accesskey='a' />
						<input type='button' id='chooseNone' name='chooseNone' value='全不选(n)' accesskey='n' />
						<input type='button' id='chooseReverse' name='chooseReverse' value='反选(v)' accesskey='v' />
					</td>
				</tr>
				<tr><td colspan='15'>
					<input type='button' id='btnCheckDel' value='删除' />
					</td>
				</tr>					
				<?php } else {  ?>
				<tr>
					<td colspan='15' class='error center'>
					没有找到任何数据
					</td>
				</tr>				
				<?php } ?>
				<tr>
					<td colspan='15' class='pager'>
					<?php echo $this->paginator(false);?>
					</td>
				</tr>
			</table>	
		</div>
		</div>
	<?php include dirname(__FILE__).'/../include/footer.phtml';?>