	<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
	
	<body>
		<div class='content_wraper'><div id="list">
		<?php if($this->params['poi_from']=="user_new" && $this->params['doubt']!=1){
					 	include_once(dirname(__FILE__).'/../include/poifunctions2.phtml');
					}else{
						include_once(dirname(__FILE__).'/../include/poifunctions.phtml');
					}?>
		<div style="margin: 10px auto;">
			<form action="<?php echo $this->admin_url;?>/poi" id="search_form">
			<table class='kai_table'>
			<tr><th colspan='7' class='center'>搜索</th></tr>
			<tr><td><input type="hidden" name="searchtype" id="searchtype" value='<?php echo $this->params['searchtype']?$this->params['searchtype']:'normal';?>' /></td></tr>
			<tr id="normalContainer">
				<td>POI ID</td>
				<td><input type='text' name='poi_id' id='poi_id' value='<?php echo $this->params['poi_id'];?>' /></td>
				<td>POI关键字:</td>
				<td><input type='text' name='namekeyword' id='namekeyword' value='<?php echo $this->params['namekeyword'];?>' /></td>
				<td>位置关键字:</td>
				<td><input type='text' name='placekeyword' id='placekeyword' value='<?php echo $this->params['placekeyword'];?>' /></td>
				<td><input type='button' name='advanceButton' id='advanceButton'  class="hide" value='高级搜索'/></td>
			</tr>	
			<tr style="display:none" id="advanceContainer">
				<td>经纬度</td>
				<td><input type='text' name='lonlatinput' id='lonlatinput' value='<?php echo $this->params['lonlatinput'];?>' /></td>
				<td>半径:</td>
				<td><input type='text' name='range' id='range' value='<?php echo $this->params['range'];?>' /></td>
				<td>创始人:</td>
				<td><input type='text' name='creatorId' id='creatorId' value='<?php echo $this->params['creatorId'];?>' /></td>
				<td><input type='button' name='normalButton' id='normalButton' value='普通搜索'/></td>
			</tr>
			<tr>
				<!--  <td>时间范围:</td>
				<td colspan='3'>
				从 <input type='text' name='from' id='from' value='<?php echo $this->params['from'];?>' readonly='readonly' />
				到 <input type='text' name='to' id='to' value='<?php echo $this->params['to'];?>' readonly='readonly' />
				</td>-->
				<td  colspan='6' style='text-align:right'>每页结果数:</td>
				<td>
				<select name='page_size' id='page_size'>
					<option value='<?php echo BETTER_PAGE_SIZE;?>' <?php echo $this->params['page_size']==BETTER_PAGE_SIZE ? ' selected="selected"' : '';?>>默认(<?php echo BETTER_PAGE_SIZE;?>)</option>
					<option value='50' <?php echo $this->params['page_size']==50 ? ' selected="selected"' : '';?>>50</option>
					<option value='100' <?php echo $this->params['page_size']==100 ? ' selected="selected"' : '';?>>100</option>
					<option value='99999999' <?php echo $this->params['page_size']==99999999 ? ' selected="selected"' : '';?>>全部</option>
				</select>
				</td>
			</tr>
			<?php if($this->params['doubt']){ ?>
			<tr>
				<td>
					POI来源：
				</td>
				<td colspan='10'>
					<select name='poi_from' id='poi_from'>
						<option value=''>所有POI</option>
						<option value='user_new' <?php echo $this->params['poi_from']=='user_new' ? ' selected="selected"' : '';?>>用户新建POI</option>
					</select>
				</td>
			</tr>
			<?php }else{?>
				<tr style='display: none;'>
					<td>
						<input type='hidden' name='poi_from' id='poi_from' value='<?php echo $this->params['poi_from']; ?>' />
					</td>
				</tr>
			<?php }?>					
			<tr>
				<td colspan='7' class='center'>
					<input type='submit' value='搜索(s)' accesskey='s' />
					<input type='button' value='清空搜索结果(r)' accesskey='r'  id='btnReset' />
					<input type='hidden' name='page' id='page' value='<?php echo $this->params['page'];?>' />
					<input type='hidden' name='reload' id='reload' value='0' />
					
					<input type='hidden' name='doubt' id='doubt' value='<?php echo $this->params['doubt'];?>'/>
				</td>
			</tr>
			</table>		
			</form>
		</div>
		
			<table cellspacing="0" class='kai_table'>	
				<tr>
					<td colspan='15' class='pager'>
					<?php echo $this->paginator(false);?>
					</td>
				</tr>					
				<tr>
					<td colspan='15'>
					<input type='button' name='selectAll'  value='全选(a)' accesskey='a' />
					<input type='button' name='selectReverse' value='反选(v)' accesskey='v' />
          |           
					<input type='button' name='btnDel' value='删除' />
					<input type='button' name='btnApproveSelected' title='批准所有已选中的POI' value='确认' />
					</td>
				</tr>					
				<tr>
					<th width='20'></th>
					<th class='nowrap'>POI ID</th>
					<th class='nowrap' width='50'>分类</th>
					<th class='nowrap'>名称</th>
					<th class='nowrap'>城市</th>
					<th class='nowrap' style="padding: 3px 30px;">地址</th>
					<th class='nowrap'>皇帝</th>
					<th class='nowrap'>创始人</th>
					<th class='nowrap'>创建时间</th>
					<th class='nowrap'>电话</th>
					<th class='nowrap'>合并POI</th>
					<!-- <th class='nowrap'>入驻次数</th>		
					<th class='nowrap'>收藏次数</th>	
					<th class='nowrap'>入驻用户数</th> -->
					<th class='nowrap' width='60'>操作</th>										
				</tr>
		
				<?php if ($this->count>0) { ?>
				<?php $i = 0; ?>
				<?php foreach ($this->rows as $row) {?>
				<tr class='<?php echo fmod($i++,2)==0 ? 'light' : 'dark';?> message_row'>
					<td><input type='checkbox' name='poids[]'  value='<?php echo $row['poi_id'];?>' /></td>
					<td class='center'><a href='/poi?id=<?php echo $row['poi_id'];?>' target='_blank'><?php echo $this->highlight($row['poi_id'], $this->params['namekeyword']);?></a></td>
					<td class='center'><?php echo $row['category_name']?></td>
					<td class='center'><?php echo $this->highlight($row['name'], $this->params['namekeyword']);?></td>	
					<td class='center'><?php echo $row['city']?></td>
					<td class='center'><?php echo $row['address'];?></td>
					<td class='center'><a href='<?php echo isset($row['major_name'])? "/".$row['major_name'] : "javascript:void(0);"; ?>'   <?php echo isset($row['major_name'])? "target='_blank'" : "" ; ?>><?php echo $row['major'];?></a></td>
					<td class='center'><a href='<?php echo isset($row['creator_name'])? "/".$row['creator_name'] : "javascript:void(0);"; ?>'   <?php echo isset($row['creator_name'])? "target='_blank'" : "" ; ?>><?php echo $row['creator'];?></a></td>
					<td class='center'><?php echo $row['create_time'] ?  date('Y-m-d H:i:s', $row['create_time']+BETTER_8HOURS) : 0;?></td>
					<td class='center'><?php echo $row['phone'];?></td>
					<td class='center'><a href='<?php echo $row['ref_id']!=0 ? '/poi?id='.$row['ref_id']: 'javascript: void(0);' ?>' <?php echo $row['ref_id']!=0 ? "target='_blank'" :'' ; ?>><?php echo $row['ref_id'];?></a></td>
					<!-- <td class='center'><a href='#' target='_blank'><?php echo $row['checkins'];?></a></td>
					<td class='center'><a href='#' target='_blank'><?php echo $row['favorites'];?></a></td>
					<td class='center'><a href='#' target='_blank'><?php echo $row['users'];?></a></td>  -->
					<td class='center'>
						<a class="xiugai" href='<?php echo $this->admin_url;?>/poi/updatepoi?id=<?php echo $row['poi_id'];?>' id="<?php echo $row['poi_id']?>">修改</a><br>
						<input type="hidden" id="<?php echo $row['poi_id'];?>_category" value='<?php echo $row['category_id']?>'>
						<input type="hidden" id="<?php echo $row['poi_id'];?>_name" value='<?php echo $row['name']?>'>
						<input type="hidden" id="<?php echo $row['poi_id'];?>_city" value='<?php echo $row['city']?>'>
						<input type="hidden" id="<?php echo $row['poi_id'];?>_address" value='<?php echo $row['address']?>'>
						<a class='search' href='<?php echo $this->admin_url;?>/poicluster?namekeyword=<?php echo $row['name'];?>&city_lat=<?php echo $row['lat'];?>&city_lon=<?php echo $row['lon'];?>&radius=50000' title='如果嫌弹出的窗口太小，可以在右键菜单中选择新标签中打开'>搜索</a><br>
            <a href="javascript: approve('<?php echo $row['poi_id']?>')" title="确认之后，此POI将不再出现在这里，并且层级自动调整为20（除非你已经调整过）">确认</a>
					</td>
				</tr>
				<?php } ?>
				<tr>
					<td colspan='15'>
					<input type='button' name='selectAll'  value='全选(a)' accesskey='a' />
					<input type='button' name='selectReverse' value='反选(v)' accesskey='v' />
          |           
					<input type='button' name='btnDel' value='删除' />
					<input type='button' name='btnApproveSelected' title='批准所有已选中的POI' value='确认' />
					</td>
				</tr>					
				<?php } else {  ?>
				<tr>
					<td colspan='15' class='error center'>
					没有找到任何数据
					</td>
				</tr>				
				<?php } ?>
				<tr>
					<td colspan='15' class='pager'>
					<?php echo $this->paginator(false);?>
					</td>
				</tr>
			</table>	
		</div>
		</div>
	<?php include dirname(__FILE__).'/../include/footer.phtml';?>
