	<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
	
	<body>
		<div class='content_wraper'><div id="list">
		<div style='width: 100%; text-align:left; background-color:#D3DCE3;'>[<a href='/admin/poi?poi_from=user_new' class='left'>新增POI</a>] [<a href='/admin/dynamicpoi' class='left'>活跃POI</a>] [<a href='/admin/poi?doubt=1&poi_from=user_new' class='left'>可疑POI</a>] [<a href='/admin/poi' class='left'>所有POI</a>][<a href='/admin/simipoi' class='left'>相似POI</a>]</div>
		<div style="margin: 10px auto;display:none">
			<form action="<?php echo $this->admin_url;?>/poi" id="search_form">
			<table class='kai_table'>
			<tr><th colspan='6' class='center'>搜索</th></tr>
			<tr>
				<td>POI关键字:</td>
				<td><input type='text' name='namekeyword' id='namekeyword' value='<?php echo $this->params['namekeyword'];?>' /></td>
				<td>位置关键字:</td>
				<td><input type='text' name='placekeyword' id='placekeyword' value='<?php echo $this->params['placekeyword'];?>' /></td>
				<td>每页结果数:</td>
				<td>
				<select name='page_size' id='page_size'>
					<option value='<?php echo BETTER_PAGE_SIZE;?>' <?php echo $this->params['page_size']==BETTER_PAGE_SIZE ? ' selected="selected"' : '';?>>默认(<?php echo BETTER_PAGE_SIZE;?>)</option>
					<option value='50' <?php echo $this->params['page_size']==50 ? ' selected="selected"' : '';?>>50</option>
					<option value='100' <?php echo $this->params['page_size']==100 ? ' selected="selected"' : '';?>>100</option>
					<option value='99999999' <?php echo $this->params['page_size']==99999999 ? ' selected="selected"' : '';?>>全部</option>
				</select>
				</td>
			</tr>	
			<tr>
				<td>皇帝ID:</td>
				<td><input type='text' name='kingId' id='kingId' value='<?php echo $this->params['kingId'];?>' /></td>
				<td>时间范围:</td>
				<td colspan='6'>
				从 <input type='text' name='from' id='from' value='<?php echo $this->params['from'];?>' readonly='readonly' />
				到 <input type='text' name='to' id='to' value='<?php echo $this->params['to'];?>' readonly='readonly' />
				</td>
			</tr>
			<?php if($this->params['doubt']){ ?>
			<tr>
				<td>
					POI来源：
				</td>
				<td colspan='10'>
					<select name='poi_from' id='poi_from'>
						<option value=''>所有POI</option>
						<option value='user_new' <?php echo $this->params['poi_from']=='user_new' ? ' selected="selected"' : '';?>>用户新建POI</option>
					</select>
				</td>
			</tr>
			<?php }else{?>
				<tr style='display: none;'>
					<td>
						<input type='hidden' name='poi_from' id='poi_from' value='<?php echo $this->params['poi_from']; ?>' />
					</td>
				</tr>
			<?php }?>					
			<tr>
				<td colspan='6' class='center'>
					<input type='submit' value='搜索(s)' accesskey='s' />
					<input type='button' value='清空搜索结果(r)' accesskey='r'  id='btnReset' />
					<input type='hidden' name='page' id='page' value='<?php echo $this->params['page'];?>' />
					<input type='hidden' name='reload' id='reload' value='0' />
					
					<input type='hidden' name='doubt' id='doubt' value='<?php echo $this->params['doubt'];?>'/>
				</td>
			</tr>
			</table>		
			</form>
		</div>
		
			<table cellspacing="0" class='kai_table'>	
				<tr>
					<td colspan='15' class='pager'>
					<?php echo $this->paginator();?>
					</td>
				</tr>					
				<tr>
					<th width='20'></th>
					<th class='nowrap'>POI ID</th>
					<th class='nowrap' width='50'>状态</th>
					<th class='nowrap'>名称</th>
					<th class='nowrap'>城市</th>
					<th class='nowrap' style="padding: 3px 30px;">地址</th>
					<th class='nowrap'>优惠内容</th>
					<th class='nowrap'>图片</th>
					<th class='nowrap'>创建时间</th>
					<th class='nowrap'>电话</th>
					<th class='nowrap'>审核</th>
					<!-- <th class='nowrap'>入驻次数</th>		
					<th class='nowrap'>收藏次数</th>	
					<th class='nowrap'>入驻用户数</th> -->
					<th class='nowrap' width='60'>操作</th>										
				</tr>
		
				<?php if ($this->count>0) { ?>
				<?php $i = 0; ?>
				<?php foreach ($this->rows as $row) {?>
				<tr class='<?php echo fmod($i++,2)==0 ? 'light' : 'dark';?> message_row'>
					<td><input type='checkbox' name='nid[]'  value='<?php echo $row['nid'];?>' /></td>
					<td class='center'><a href='/poi?id=<?php echo $row['poi_id'];?>' target='_blank'><?php echo $this->highlight($row['poi_id'], $this->params['namekeyword']);?></a></td>
					<td class='center' id='check_type_<?php echo $row['nid']; ?>'><?php echo $row['check_type']?></td>
					<td class='center'><?php echo $this->highlight($row['name'], $this->params['namekeyword']);?></td>	
					<td class='center'><?php echo $row['city']?></td>
					<td class='center'><?php echo $row['address'];?></td>
					<td class='center' id='content_<?php echo $row['nid']; ?>'><?php echo $row['content'];?></td>
					<td class='center' id='image_<?php echo $row['nid']; ?>'><?php if($row['image_url']){ ?><img src='<?php echo $row['attach_tiny'];?>'><?php }?></td>
					<td class='center'><?php echo $row['create_time'] ?  date('Y-m-d H:i:s', $row['create_time']+BETTER_8HOURS) : 0;?></td>
					<td class='center'><?php echo $row['phone'];?></td>
					<td class='center'><?php if($row['checked']==0){?><div id='doing_<?php echo $row['nid']; ?>'><input type='button' id='access_<?php echo $row['nid']; ?>' name='access_<?php echo $row['nid']; ?>'  value='通过' temppoiid='<?php echo $row['poi_id']; ?>' /><a class="xiugai" href='<?php echo $this->admin_url;?>/poi/cancelspecial?id=<?php echo $row['nid'];?>&poi_id=<?php echo $row['poi_id'];?>' id="<?php echo $row['uid']?>">不通过</a></div><?php } ?>					
					
					</td>
					<!-- <td class='center'><a href='#' target='_blank'><?php echo $row['checkins'];?></a></td>
					<td class='center'><a href='#' target='_blank'><?php echo $row['favorites'];?></a></td>
					<td class='center'><a href='#' target='_blank'><?php echo $row['users'];?></a></td>  -->
					<td class='center'>
						<a class="xiugai" href='<?php echo $this->admin_url;?>/poi/updatespecial?id=<?php echo $row['nid'];?>&poi_id=<?php echo $row['poi_id'];?>' id="<?php echo $row['uid']?>">修改</a><br>
						<input type="hidden" id="<?php echo $row['poi_id'];?>_category" value='<?php echo $row['category_id']?>'>
						<input type="hidden" id="<?php echo $row['poi_id'];?>_name" value='<?php echo $row['name']?>'>
						<input type="hidden" id="<?php echo $row['poi_id'];?>_city" value='<?php echo $row['city']?>'>
						<input type="hidden" id="<?php echo $row['poi_id'];?>_address" value='<?php echo $row['address']?>'>
						
						<a class='search' href='<?php echo $this->admin_url;?>/poi/search?id=<?php echo $row['poi_id'];?>'>搜索</a><br>
					</td>
				</tr>
				<?php } ?>
				<tr>
					<td colspan='15' class='center'>
					<input type='button' id='chooseAll' name='chooseAll'  value='全选(a)' accesskey='a' />
					<input type='button' id='chooseNone' name='chooseNone' value='全不选(n)' accesskey='n' />
					<input type='button' id='chooseReverse' name='chooseReverse' value='反选(v)' accesskey='v' />
				</td></tr>
				<tr><td colspan='15'>
				
					</td>
				</tr>					
				<?php } else {  ?>
				<tr>
					<td colspan='15' class='error center'>
					没有找到任何数据
					</td>
				</tr>				
				<?php } ?>
				<tr>
					<td colspan='15' class='pager'>
					<?php echo $this->paginator();?>
					</td>
				</tr>
			</table>	
		</div>
		</div>
	<?php include dirname(__FILE__).'/../include/footer.phtml';?>