<?php include_once(dirname(__FILE__).'/../include/meta_nothing.phtml');?>
<div class="mid">
 	
 		<div id='flash'><object id="bedo_plugin" height="741" width="1220" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000">
<param value="http://222.92.116.8:20009/site/html/flash/kai_map.swf?lat=40.09000272291728&lon=116.7074755859375&z=10" name="movie"/>
<param name = "allowScriptAccess" value = "always" /> 
<param name="wmode" value="transparent" />
<param value="high" name="quality"/><param value="Opaque" name="wmode"/>

<embed height="741" width="1220" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" wmode="transparent" src="http://222.92.116.8:20009/site/html/flash/kai_map.swf?lat=40.09000272291728&lon=116.7074755859375&z=10" name="bedo_plugin"/>

</object>
</div>
 		
 	
 	<div id='nowdoing'>
 	 	<div id="poi_doing" style='overflow: hidden;position:relative;'> </div>   
	    <div id="poi_doing_temp" class="hide" style='display:hidden'> </div>	
 	</div>
</div> <!--#content-->
<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>
</body>
</html>