<div>
<a href="http://m.360.cn/partner/kkw.wml" ><?php echo $this->lang->mobile->foot->partner->title; ?></a>
<a href="http://wap.eoemarket.com/?channel=CJVvmQCK6twJ6OISmoZ2Hg">优亿市场</a>		
<br/><a href="http://kaiqi.com/class.do?dirid=172188&q=kk" >Opera Mini 6</a>	
<a href="http://www.gfan.com/app/amarket/web095" >机锋市场</a>
<br/><a href="http://m.mumayi.com" >木蚂蚁安卓</a>
<a href="http://wap.cnmo.com" >手机中国</a>	
<br/><a href="/mobile/help/link">更多</a>
</div>