<div id="polo">
	<a href='http://wap.moad.cn/MOAD/10620/drive.aspx'><img src="/images/polo/drive.gif" border='0' /></a><br/>
	<a href='http://wap.moad.cn/MOAD/10620/newpolo.aspx'><img src="/images/polo/newred.gif" border='0' /></a><br/>
	上海大众汽车客户服务热线<br/>
	400-820-1111<br/>
	<a href='http://wap.moad.cn/MOAD/10620/'><img src="/images/polo/back2home.png" border='0' /></a><br/>
	<img src="/images/polo/wap_bottom.png" border='0' />
</div>