<style type="text/css">
#header{link:#ffffff;}
#template a:visited {color:#B4585D;text-decoration:none;}body{line-height: 18px;margin: 0px;font-size: 12px;}#template a:hover {color:#0B1DD1;text-decoration:none;}.center {text-align: center;}.center #template {margin: 0 auto;text-align: left;}td{padding: 0px;}table {border-width:0px;padding: 0px;border-spacing: 0px;}#template a:link {color:#000000;text-decoration:none;}#template {width:220px;background-color:#fafafa;}
.sy05{background-color:#f5f5f5;border: 1px solid #e7e7e7;margin-bottom: 2px;}
.error{color: red}
#footer {clear:both; color:#777777;padding:13px 0 13px 5px}
a{
	color:#00bbff;
	text-decoration:none;
}
#portalindex{
	background-color:#00BBFF;
	color:#fff;
	padding-left:5px;
}
#portalindex a{
	color:#fff;
	text-decoration:none;
	line-height:23px;	
}
#portal{
	background-color:#444444;
	color:#fff;
	padding-left:5px;
}
#portal a{
	color:#fff;
	text-decoration:none;
	line-height:23px;	
}
#footer_menu a{
	color:#fff;
	text-decoration:none;
}
#pctips a {
	color:#fff;
	text-decoration:none;
}
#category{
	background: #f0f0eb;	
	line-height:23px;
	padding-left:5px;
}
#headinfo{
	background: #00BBFF; color:#fff;
}
#headinfo a{
	color:#fff;
	text-decoration:none;
}
#activities{
	padding-left:5px;
}

#index_more a,#user_candoing a{
	color:#88cc00;
}
.timeandsource{
	color:#bbbbb6;
}

#havenotkaiacount{
	color: #BBBBB6;
	padding-left:5px;
	line-height:23px;
}

hr { height:1px;  color:#BBBBB6;}
.tline {height:1px;background-color:#E7ECF0;font-line:1px;}
#login,#place,#content,#user_candoing,#user_basic_info,#user_chengju,#search,#results,#list,#basic,#timeline{
	padding-left:5px;
}
#user_basic_info .exp_user_info{
	display: inline-block;
	width:50px;
	color:#ff6699;
}
#pctips a{
	color:#000;
	text-decoration:none;
}
</style>