	<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
	<body>
		<div class='content_wraper'><div id="list">
		<div style='width: 100%; text-align:left; background-color:#D3DCE3;'><a class="token" href='#addToken'>新增token</a></div>
		<div style="margin: 10px auto;">
			<form action="<?php echo $this->admin_url;?>/thirdpool" id="search_form">
			<table class='kai_table'>
			<tr><th colspan='6' class='center'>搜索</th></tr>
			<tr>
				<td>用户ID:</td>
				<td><input type='text' name='uid' id='uid' value='<?php echo $this->params['uid'];?>' /></td>
				<td>3rd协议:</td>
				<td>
					<select name='protocol' id='protocol' style='width:120px'></select>
					<input type='hidden' name='protocol_value' id='protocol_value' value='<?php echo $this->params['protocol'];?>' />
				</td>
				<td>每页结果数:</td>
				<td>
				<select name='page_size' id='page_size'>
					<option value='<?php echo BETTER_PAGE_SIZE;?>' <?php echo $this->params['page_size']==BETTER_PAGE_SIZE ? ' selected="selected"' : '';?>>默认(<?php echo BETTER_PAGE_SIZE;?>)</option>
					<option value='50' <?php echo $this->params['page_size']==50 ? ' selected="selected"' : '';?>>50</option>
					<option value='100' <?php echo $this->params['page_size']==100 ? ' selected="selected"' : '';?>>100</option>
					<option value='99999999' <?php echo $this->params['page_size']==99999999 ? ' selected="selected"' : '';?>>全部</option>
				</select>
				</td>
			</tr>
			<tr>
				<td colspan='6' class='center'>
					<input type='submit' value='搜索(s)' accesskey='s' />
					<input type='button' value='清空搜索结果(r)' accesskey='r'  id='btnReset' />
					<input type='hidden' name='page' id='page' value='<?php echo $this->params['page'];?>' />
					<input type='hidden' name='reload' id='reload' value='0' />
				</td>
			</tr>
			</table>
			</form>
		</div>

		<div class='hide'>
  		<div id='addToken' style="width: 280px; height: 120px; margin: 10px auto;">
  			<table class='kai_table'>
  			<tr><th colspan='2' class='center'>增加token</th></tr>
  			<tr>
  				<td width='80' nowrap>用户ID:</td>
  				<td width="100%"><input type='text' name='new_uid' id='new_uid' value='' /></td>
  			</tr>
  			<tr>
  				<td>3rd协议:</td>
  				<td><select name='new_protocol' id='new_protocol' style='width:150px'></select></td>
  			</tr>
  			<tr>
  				<td colspan='2' class='center'>
  					<input type='button' id="btnAdd" value='确定' />
  					<input type='button' id="btnCancel" value='放弃' />
  				</td>
  			</tr>
  			</table>
  		</div> 
		</div>

			<table cellspacing="0" class='kai_table'>	
				<tr>
					<td colspan='15' class='pager'>
					<?php echo $this->paginator();?>
					</td>
				</tr>					
				<tr>
					<th width='20'>&nbsp;</th>
					<th class='nowrap'>用户ID</th>
					<th class='nowrap'>3rd协议</th>
					<th class='nowrap'>3rd用户名</th>
					<th class='nowrap'>3rd密码</th>
					<th class='nowrap'>token</th>
					<th class='nowrap'>secret</th>
					<th class='nowrap'>启用时间</th>
					<th class='nowrap'>使用次数</th>
					<th class='nowrap'>&nbsp;</th>
				</tr>
		
				<?php if ($this->count>0) { ?>
				<?php $i = 0; ?>
				<?php foreach ($this->rows as $row) { ?>
				<tr class='<?php echo fmod($i++,2)==0 ? 'light' : 'dark';?> message_row'>
					<td><input type='checkbox' name='tids[]'  value='<?php echo $row['id'];?>' /></td>
					<td class='center'><?php echo $row['uid'];?></td>
					<td class='center'><?php echo $this->highlight($row['protocol'], $this->params['protocol']);?></td>	
					<td class='center'><?php echo $row['username']?></td>
					<td class='center'><?php echo $row['#password']?></td>
					<td class='center'><?php echo $row['#oauth_token']?></td>
					<td class='center'><?php echo $row['oauth_token_secret']?></td>
					<td class='center'><?php echo date('Y-m-d H:i:s', $row['dateline']+BETTER_8HOURS)?></td>
					<td class='center'><?php echo $row['total']?></td>
					<td class='center'><a href='#' class='token' onclick='removeToken("<?php echo $row['uid'];?>", "<?php echo $row['protocol']?>")'>删除</a></td>
				</tr>
				<?php } ?>
				<tr>
					<td colspan='15' class='center'>
					<input type='button' id='chooseAll' name='chooseAll'  value='全选(a)' accesskey='a' />
					<input type='button' id='chooseNone' name='chooseNone' value='全不选(n)' accesskey='n' />
					<input type='button' id='chooseReverse' name='chooseReverse' value='反选(v)' accesskey='v' />
				</td></tr>
				<tr><td colspan='15' class='center'>
  				<select name='todo' id='todo'>
  				<option value=''>请选择操作</option>
  				<option value='del_poi'>删除</option>
  				</select>
  				<input type='button' id='btnTodo' value='确定(d)' accesskey='d' />
				</td></tr>
				<?php } else {  ?>
				<tr>
					<td colspan='15' class='error center'>
					没有找到任何数据
					</td>
				</tr>				
				<?php } ?>
				<tr>
					<td colspan='15' class='pager'>
					<?php echo $this->paginator();?>
					</td>
				</tr>
			</table>	
		</div>
		</div>
	<?php include dirname(__FILE__).'/../include/footer.phtml';?>