	<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
	
	<body>
<div style="width:620px; font-size: 14px; text-align: left;">
	<div style="height: 33px; background-color: #395795; padding: 5px;">
		<img src="http://k.ai/images/email_logo.png" width="80" height="23" />
	</div>
	<div style="border: 1px solid #DCE2EA; padding: 15px;" >
		<div id="container"></div>
		<br />
		<hr style="border-bottom: 0px solid #DCE2EA; width: 80%; height: 0px;" align="left">
		<br />
		开开，基于地理位置的真实社交网络。签到，找好友，探索身边的城市 <a href='http://k.ai'>http://k.ai</a>。<br />
		此邮件来自K.ai邮件系统，请勿直接回复。
	</div>
</div>