<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title><?php echo $this->title;?></title>
<script type="text/javascript" src="http://221.224.52.81:9081/js/jquery/jquery.min.js?ver=20110513090530" charset="utf-8" ></script> 
</head>
<body>
plz post xml.
</body>
</html>
