<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>

<body id="notfinised">
<?php include_once(dirname(__FILE__).'/../include/newheader.phtml');?>	

<div id="content">
  	<div style="height: 300px; padding: 40px 290px;"><h3><?php echo $this->lang->global->not_finished; ?></h3></div>
</div> <!--#content-->

<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>

</body>
</html>