<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta name="viewport" content="width=device-width; initial-scale=1.4; minimum-scale=1.0; maximum-scale=2.0"/>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><?php echo $this->lang->global->meta->title;?></title>
	<?php include_once(dirname(__FILE__).'/../include/textcss.phtml');?>
</head>
<body>
	<?php include_once(dirname(__FILE__)."/../include/logo.phtml")?>
	<div id="headinfo">
		<?php 
    		if( $this->user['uid'] > 0 ){
				echo "<a href=\"/polo/user?uid=".$this->user["uid"]."\" >".$this->user["nickname"]."</a>@";
				if( (int)($this->lastcheckin['poi']['poi_id']) < 1 ){
					echo "<a href=\"/polo/search\">".$this->lang->mobile->global->whereplace."</a>";
				}else{
					echo "<a href=\"/polo/place?pid=".$this->lastcheckin['poi']['poi_id']."\">".$this->lastcheckin['poi']['name']."</a>";
				}
				echo "<hr/>";
			}
		?>	
	</div>
	<?php echo "<a href=\"/polo/setting\">".$this->lang->global->nav->setting."</a>->".$this->lang->setting->menu->city;?>
	
	<form method='post' action='/polo/setting/update' >	   	
	   <?php echo $this->lang->setting->basic->city->title;?>
	    <?php foreach($this->cityArray as $rows){	    ?>
	    <label><input name="live_province" type="radio"  value='<?php echo $rows['0']?>' <?php if($rows['0']==$this->user['live_province']){ echo "checked";}?>/><?php echo $rows['0']?></label>
	    <?php }?><br/>	   
	   	<input type="submit" id='btnPrivacy' value="<?php echo $this->lang->setting->privacy->button_tips;?>" class="save btn"/>
	   	<input type='hidden' name='todo' id='todo' value='province' />
	</form>
	
	<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>
</body>
</html>
