<?php 
if ($_SERVER['HTTP_HOST']==$this->config->api->host) {
	die('Forbidden');
}

$cssUrl = $this->cssUrl ? $this->cssUrl : BETTER_BASE_URL.($this->config->css->path);
$jsUrl = $this->jsUrl ? $this->jsUrl : BETTER_BASE_URL.($this->config->javascript->path);
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<base href="http://<?php echo $_SERVER['HTTP_HOST'];?>/" />
<title><?php echo $this->lang->global->meta->title;?></title>
<meta name="keywords" content="开开, 位置, 社交网络, 游戏, 签到, 掌门, 寻宝, Kai, location, SNS, check-in, Mayor, Geocaching"  />
<meta name="description" content="开开K.ai是新一代的位置网络，也是真实的白领社交网络。在开开签到，你能够找到朋友、分享贴士，并用全新的方法探索身边的城市。同时还可以争掌门、赢勋章" /> 
<meta http-equiv='X-UA-Compatible' content='IE=EmulateIE7' />

<link rel="stylesheet" type="text/css" href="<?php echo $cssUrl;?>/<?php echo $this->css;?>.css?ver=<?php echo BETTER_VER_CODE;?>" />
<link rel="shortcut icon" href="http://<?php echo $_SERVER['HTTP_HOST'];?>/favicon.ico?v=1" />
<!--[if lt IE 7]>
<script src="<?php echo $jsUrl;?>/DD_belatedPNG.js?ver=<?php echo BETTER_VER_CODE;?>" type='text/javascript'></script>
<script type='text/javascript'>
DD_belatedPNG.fix('.avatar,  .logo, .stat, .pngfix, tr td img ');
</script>
<script src="<?php echo $jsUrl;?>/iepngfix_tilebg.js" type='text/javascript'></script>
<style type="text/css">
 .zoompng{ behavior: url("<?php echo $jsUrl;?>/iepngfix.htc") }
</style>
<![endif]-->
<!--[if IE 7]>
<link rel="stylesheet" type="text/css" href="<?php echo $cssUrl;?>/ie7fix.css?ver=<?php echo BETTER_VER_CODE;?>" />
<![endif]-->
<?php 

switch (Better_Registry::get('language')) {
	case 'en':
?>
<link rel="stylesheet" type="text/css" href="<?php echo $cssUrl;?>/en.<?php echo $this->css;?>.css?ver=<?php echo BETTER_VER_CODE;?>" />
<!--[if IE 6]>
<link rel="stylesheet" type="text/css" href="<?php echo $cssUrl;?>/en.ie6fix.css?ver=<?php echo BETTER_VER_CODE;?>" />
<![endif]-->
<?php 
		break;
	default:
		?>
<!--[if IE 6]>
<link rel="stylesheet" type="text/css" href="<?php echo $cssUrl;?>/ie6fix.css?ver=<?php echo BETTER_VER_CODE;?>" />
<![endif]-->
<?php 
		break;
}
?>


<?php header('P3P: CP=CAO PSA OUR');?>


<link rel="shortcut icon" href="http://k.ai/favicon.ico?v=1" />

</head>
<body>
<div class='mid'>
	<div id='form_up'></div>
	<div id='form_center'>
		<div id='head_guide'><a href='/index'>开开首页</a>|
		<a href='<?php echo $this->thirdpage;?>'>
		<?php if(strpos($this->thirdpage,'renren.com')===false){?>微博<?php } else {?>主页<?php }?></a></div>
		<div id='content'>
			<div id='logo'><a href="/" class='logoimg'></a></div>
			<div id='guide_content'>
				<img src="/images/fromthird_aboutkai.png"  class="logo"/>
				<div id='aboutkai'>
					<?php echo $this->lang->global->login->fromthird_aboutkai;?>
				</div>
				<?php if($this->had_at_kai){?>				
				<div id='atkai'>
					<input type="checkbox" id="atkaiaccount" value="1" name="atkaiaccount" checked='checked'/>关注开开官方微博
					<input type='hidden' id='oauthatkai' value="<?php echo $this->oauthatkai;?>" />
					<input type='hidden' id='oauthkai' value="<?php echo $this->oauthurl;?>" />					
				</div>
				<?php }?>
				<input type='hidden' id='had_at_kai' value="<?php echo $this->had_at_kai;?>" />
				<div id='fromsubmit'>
					<a href='<?php echo $this->oauthatkai;?>' id='thirdurl'><img src='/images/fromthird_loginthird.png' style='vertical-align:text-bottom;' id='venue_reg_submit'/></a>
				</div>
			</div>
		</div>
	</div>
	<div id='form_down'></div>
	<div class='clearfix'></div>
</div>


<script type='text/javascript' src="<?php echo $jsUrl;?>/jquery/jquery-1.4.2.min.js" charset="utf-8"></script> 
<script type='text/javascript' src='<?php echo $jsUrl;?>/controllers/login/kai.js?ver=<?php echo BETTER_VER_CODE;?>' charset='utf-8' ></script>


</body>
</html>
