<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta name="viewport" content="width=device-width; initial-scale=1.4; minimum-scale=1.0; maximum-scale=2.0"/>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><?php echo $this->lang->global->meta->title;?></title>
	<?php include_once(dirname(__FILE__).'/../include/textcss.phtml');?>
</head>
<body>
	<?php include_once(dirname(__FILE__)."/../include/logo.phtml")?>
	<div id="headinfo">		
		<a href="/polo/place?pid=<?php echo($this->place['poi_id'])?>" ><?php echo($this->place["name"]);?></a>
		<?php echo $this->lang->mobile->global->poi_tips;?>
		<hr/>
	</div>
	<div id="content">
		<table>
			<?php for($i=0; $i < count($this->tips); $i++){?>
			<tr valign="top" >
	    			<?php
	    				echo "<td>".($this->start+$i).".</td>";
	    				echo "<td><a href=\"/polo/user?uid=".$this->tips[$i]['uid']."\">".$this->tips[$i]['nickname']."</a>:".$this->tips[$i]['message'];
			$checktype = ("checkin" == $this->tips[$i]['type'])? 0:1;
	        	if($this->tips[$i]['uid']!=$this->user['uid'])
	        	{
	           		if($checktype){
	           			echo "<a href=\"/polo/user/shout?cat=".$this->tips[$i]['type']."&upbid=".$this->tips[$i]['bid']."\">".$this->lang->javascript->global->blog->rt."</a> ";
	           			if("tips" == $this->tips[$i]['type'] && $this->tips[$i]['polled']==0){
	           				echo "<a href=\"/polo/user/poll?todo=create&option=up&status_id=".$this->tips[$i]['bid']."&poiid=".$this->place['poi_id']."\">".$this->lang->javascript->poi->tips->up."</a> ";
	           				echo "<a href=\"/polo/user/poll?todo=create&option=down&status_id=".$this->tips[$i]['bid']."&poiid=".$this->place['poi_id']."\">".$this->lang->javascript->poi->tips->down."</a> ";
	           			}
	           		}
	        	}
	       	 	else
	        	{
	           		echo "<a href=\"/polo/user/delblog?id=".$this->tips[$i]['bid']."\">".$this->lang->javascript->global->blog->delete_it."</a> ";
	        	}
	        	if($checktype) {
	           		echo "<a href=\"/polo/user/addfavorite?cat=".$this->tips[$i]['type']."&id=".$this->tips[$i]['bid']."&fid=".$this->tips[$i]['uid']."\">".$this->lang->javascript->global->favorite->title."</a> ";	       
	        	}
	    				echo "</td>";	    				
	    			?>
	      		</tr>
	      		<?php if($this->tips[$i]['attach_tiny']){?>
	               	<tr>
	               		<td></td><td><img src="<?php echo $this->tips[$i]['attach_tiny'];?>" /></td>
	               	</tr>
	            <?php }?>
			<tr>
				<td></td>
				<td><?php echo $this->checkins[$i]['poi']['city']." ".Better_Functions::compareTime($this->tips[$i]['dateline'])?></td>
			</tr>
			<?php }?>
		</table>
		<?php
			echo $this->urlNext." ".$this->urlPrev;
		?>
	</div>
	<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>
</body>
</html>