<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta name="viewport" content="width=device-width; initial-scale=1.4; minimum-scale=1.0; maximum-scale=2.0"/>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><?php echo $this->lang->global->meta->title;?></title>
	<?php include_once(dirname(__FILE__).'/../include/textcss.phtml');?>
</head>
<body>
	<?php include_once(dirname(__FILE__)."/../include/logo.phtml")?>
	<div id="headinfo">		
		<a href="/polo/place?pid=<?php echo($this->place['poi_id'])?>" ><?php echo($this->place["name"]);?></a>
		<?php echo "->".$this->lang->mobile->global->visitor_list;?>
		<hr/>
	</div>
	<div id="content">
		<table>
			<?php $i = 0; foreach($this->visitors as $visitor){?>
			<tr>
				<td><?php echo ($i+1).".";?></td><td><a href="/polo/user?uid=<?php echo $visitor['uid'];?>"><?php echo $visitor['nickname']; ?></a></td>
			</tr>
			<tr>
				<td></td>
				<td><img src="<?php echo $visitor['avatar_small']; ?>" /></td>
			</tr>
			<?php $i++; }?>
		</table>
		<?php 
		if( count($this->visitors) < 1 ){
			echo "<p>".$this->lang->global->not_checkin_yet."</p>";
		}
		  ?>
	</div>
	
	<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>
</body>
</html>