<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
<body id="setting">
<?php include_once(dirname(__FILE__).'/../include/newheader.phtml');?>	

<div id="setting_page">
 <div class="mid title">
	  <div id="setting_header_title"><span class='text'><?php echo $this->lang->global->nav->setting;?></span></div>
	   <div id="setting_header_img"><h2><?php echo $this->lang->global->setting_header_text;?></h2></div>
 </div>
 
  <div class="mid">
	<div id="setting_menu">
	    <ul id="right_menu">	   
	        <li><a href="/setting" class="off"><?php echo $this->lang->setting->menu->basic;?></a></li>
	        <li><a href="/setting/avatar" class="on"><?php echo $this->lang->setting->menu->avatar;?></a></li>
	        <li><a href="/setting/password" class="off"><?php echo $this->lang->setting->menu->password;?></a></li>
	       <li><a href="/setting/privacy" class="off"><?php echo $this->lang->setting->menu->privacy;?></a></li>  
	        <li><a href="/setting/cell" class="off"><?php echo $this->lang->setting->menu->cell;?></a></li>
	        <?php if ($this->config->msn_robot->enabled) { ?>
	        <li><a href='/setting/im' class="off"><?php echo $this->lang->setting->menu->im;?></a></li>
	        <?php } ?>	        
	        <li><a href="/setting/sync" class="off"><?php echo $this->lang->setting->menu->sync;?></a></li>
	        <li><a href="/setting/email" class="off"><?php echo $this->lang->setting->menu->email;?></a></li>
	        <?php if (!$this->config->lbs->promotion) { ?><li><a href="/tools/lbs" class="off"><?php echo $this->lang->tools->lbs->title;?></a></li><?php } ?>
	        <li><a href="/tools/share" class="off"><?php echo $this->lang->tools->share->title;?></a></li>
	         <?php if ($this->bedoUid) {?>
	        <li><a href="/setting/bedoimport" class="off"><?php echo $this->lang->setting->menu->bedoimport;?></a></li>
	        <?php } else {?>
	        <li><a href="/setting/bedobind" class="off"><?php echo $this->lang->setting->menu->bedoimport;?></a></li>
	        <?php }?>
	    </ul>
	 </div>
	 <div id="setting_content">
			<div class="setting_main">
			
  	 		<h2><?php echo $this->lang->setting->avatar->title;?></h2>
		
	    	<div class="userinfo">
	    	<div class='label'>
	    		
	    		<?php if ($this->user['avatar']) { ?>
	    		<?php echo $this->lang->setting->avatar->have_tips;?>
	    		<?php } else { ?>
	    		<?php echo $this->lang->setting->avatar->havent_tips;?>
	    		<?php } ?>
	    		
	    	</div>
	    	<form method='post' action='/setting/update' id=''>

				<div class='setting_notice hide'></div>
				
				<div id='avatarContainer'>
				<div id='myAvatar'>

		    		<img src="<?php echo $this->user['avatar_normal'];?>" width="96" alt="" class="now_avatar"/>
		
				</div>
				<div id='avatarFunc'>
					<div id='avatarForm'>

					<input type='text' name='avatar_path' id='avatar_path' readonly='readonly' value='' />
					<input type='button' name='btnFile' id='btnFile' value='<?php echo $this->lang->setting->avatar->file_tips;?>'  class='btn' />
					</div>
					<div style='margin-bottom: 15px;'>
						<span style='font-style: italic; '><?php echo $this->lang->setting->avatar->limit ; ?></span>
					</div>
	    			 <div class="field">
				  	  	<input type='button' id='btnUploadAvatar' class='btn' value='<?php echo $this->lang->setting->avatar->upload_tips;?>' style='width: 253px;' />
				  	  	<!-- <input type='button' id='btnClearAvatar' class='btn' value='<?php echo $this->lang->setting->avatar->delete_tips;?>' />  -->
				  	  	<input type='hidden' name='avatar' id='avatar' value='<?php echo $this->user['avatar'];?>' />
				  	  	<input type='hidden' name='todo' id='todo' value='avatar' />
				  	 </div>					
				</div>
				
				</div>
	    	</form>
			</div>
	    </div>
	   <div style="height:230px;"></div>
	 </div>	    
  <div class="clearfix"></div>
  </div><!--#mid-->
</div> <!--#content-->

<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>

</body>
</html>
<?php $this->Gz();?>