<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
<body id="setting">
<?php include_once(dirname(__FILE__).'/../include/newheader.phtml');?>	

<div id="setting_page">
 <div class="mid title">
	  <div id="setting_header_title"><span class='text'><?php echo $this->lang->setting->import->name;?></span></div>
	   <div id="setting_header_img"><h2><?php echo $this->lang->global->setting_header_text;?></h2></div>
 </div>
 
  <div class="mid">
	<div id="setting_menu">
	    <ul id="right_menu">	   
	        <li><a href="/setting" class="of"><?php echo $this->lang->setting->menu->basic;?></a></li>
	        <li><a href="/setting/avatar" class="off"><?php echo $this->lang->setting->menu->avatar;?></a></li>
	        <li><a href="/setting/password" class="off"><?php echo $this->lang->setting->menu->password;?></a></li>
	        <li><a href="/setting/privacy" class="off"><?php echo $this->lang->setting->menu->privacy;?></a></li> 
	        <li><a href="/setting/cell" class="off"><?php echo $this->lang->setting->menu->cell;?></a></li>
	        <?php if ($this->config->msn_robot->enabled) { ?>
	        <li><a href='/setting/im' class="off"><?php echo $this->lang->setting->menu->im;?></a></li>
	        <?php } ?>	        
	        <li><a href="/setting/sync" class="off"><?php echo $this->lang->setting->menu->sync;?></a></li>
	        <li><a href="/setting/email" class="off"><?php echo $this->lang->setting->menu->email;?></a></li>
	        <?php if (!$this->config->lbs->promotion) { ?><li><a href="/tools/lbs" class="off"><?php echo $this->lang->tools->lbs->title;?></a></li><?php } ?>
	        <li><a href="/tools/share" class="off"><?php echo $this->lang->tools->share->title;?></a></li>
	        <?php if ($this->bedoUid) {?>
	        <li><a href="/setting/bedoimport" class="on"><?php echo $this->lang->setting->menu->bedoimport;?></a></li>
	        <?php } else {?>
	        <li><a href="/setting/bedobind" class="on"><?php echo $this->lang->setting->menu->bedoimport;?></a></li>
	        <?php }?>
	    </ul>
	 </div>
	 <div id="setting_content">
			<div class="setting_main">
	    	<div class="userinfo" id="userinfo">
	    	<div class="bindTip">
	    		<h2><?php echo $this->lang->setting->import->warning;?></h2>
	    	</div>
			<form>
				<div class="row">
				  <label for="bedo"><?php echo $this->lang->setting->import->bedo;?></label>
				  <div class="field">
				  	 <input type="text" style="width: 267px;" id="jid" name="jid" value="" />
				  	 <span id='err_jid' class='err'><?php echo $this->err['err_jid'];?></span>
				  </div>
				</div>
				<div class="row">
				  <label for="password"><?php echo $this->lang->setting->import->password;?></label>
				  <div class="field">
				  	  <input type="password" style="width: 267px;" id="password" name="password" value="" />
				  	  <span id='err_password' class='err'><?php echo $this->err['err_password'];?></span>
				  </div>
				  <div class="clearfix"></div>
				</div>
				   <br />
				  <input type="button" value="<?php echo $this->lang->setting->im->button_tips;?>" class="save btn" id='btnBind' />
				  <br/>
				  <br/>
			</form>
			</div>
			<div id="import" class="hide">
				<span><?php echo $this->lang->setting->import->success?></span>
				<br />
				<a href="/setting/bedoimport" class="on"><?php echo $this->lang->setting->menu->bedoimport;?></a>
			</div>
	    </div>	  
	 </div>	    
  <div class="clearfix"></div>
  </div><!--#mid-->
</div> <!--#content-->

<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>

</body>
</html>
<?php $this->Gz();?>