<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
<body id="setting">
<?php include_once(dirname(__FILE__).'/../include/newheader.phtml');?>	

<div id="setting_page">
 <div class="mid title">
	  <div id="setting_header_title"><span class='text'><?php echo $this->lang->global->nav->setting;?></span></div>
	   <div id="setting_header_img"><h2><?php echo $this->lang->global->setting_header_text;?></h2></div>
 </div>
  <div class="mid">
	<div id="setting_menu">
	    <ul id="right_menu">
	        <li><a href="/setting" class="off"><?php echo $this->lang->setting->menu->basic;?></a></li>
	        <li><a href="/setting/avatar" class="off"><?php echo $this->lang->setting->menu->avatar;?></a></li>
	        <li><a href="/setting/password" class="off"><?php echo $this->lang->setting->menu->password;?></a></li>
	        <li><a href="/setting/privacy" class="off"><?php echo $this->lang->setting->menu->privacy;?></a></li>
	        <li><a href="/setting/cell" class="on"><?php echo $this->lang->setting->menu->cell;?></a></li>
	        <?php if ($this->config->msn_robot->enabled) { ?>
	        <li><a href='/setting/im' class="off"><?php echo $this->lang->setting->menu->im;?></a></li>
	        <?php } ?>	        
	        <li><a href="/setting/sync" class="off"><?php echo $this->lang->setting->menu->sync;?></a></li>
	        <li><a href="/setting/email" class="off"><?php echo $this->lang->setting->menu->email;?></a></li>
	        <?php if (!$this->config->lbs->promotion) { ?><li><a href="/tools/lbs" class="off"><?php echo $this->lang->tools->lbs->title;?></a></li><?php } ?>
	        <li><a href="/tools/share" class="off"><?php echo $this->lang->tools->share->title;?></a></li>
	        <?php if ($this->bedoUid) {?>
	        <li><a href="/setting/bedoimport" class="off"><?php echo $this->lang->setting->menu->bedoimport;?></a></li>
	        <?php } else {?>
	        <li><a href="/setting/bedobind" class="off"><?php echo $this->lang->setting->menu->bedoimport;?></a></li>
	        <?php }?>
	    </ul>
	 </div>
	     <div id="setting_content">
			<div class="setting_main">
			<div class="headertitle"><?php echo $this->lang->global->not_cell_validating_tips;?></div>
  	 		<h2><?php echo $this->lang->setting->cell->title;?></h2>
	 
	    
	    	
			<div id="setting_block">
	      
	    	<div class="userinfo">
	    	<form>
	    	<div id='bindCellFirstStep''>

	    	<div class="snotice hide"  id='cell_tips'>
	    	    <?php echo $this->lang->setting->cell->binded;?> <b class='red'><?php echo $this->user['cell_no'];?></b>
	    	</div>

	    		<div class="row" >
	    			<?php echo $this->lang->setting->cell->tips;?>
	    			<br/>
	    			<input type="text" size="30" id="mobile" name="mobile" class='binput' value=""/>
	    		
	    		<input type="button" id='btnBindCell' value="<?php echo $this->lang->setting->cell->btnBindCell;?>" class='btn'/> <span class='err' id='errMobile'></span>
	    		
	    		</div>
			<div class="row">
				<?php echo $this->lang->setting->cell->note1;?>
				<?php echo $this->lang->setting->cell->note2;?>
				<?php echo $this->lang->setting->cell->note3;?>
				<br />
                                1.<?php echo str_replace('{CELL_ROBOT}', '<span class="err">'.$this->robot.'</span>', $this->lang->setting->cell->note4);?>
				2.<?php echo str_replace('{CELL_ROBOT}', '<span class="err">'.$this->robot.'</span>', $this->lang->setting->cell->note5);?>
				<?php echo $this->lang->setting->cell->note6;?>
			</div>
			</div>

			</form>
			</div>
	    </div>
	   
	   </div>
	</div>
	 <div class="clearfix"></div>   
  </div><!--#mid-->
</div> <!--#content-->

<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>

</body>
</html>
<?php $this->Gz();?>
