<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
<body id="setting">
<?php include_once(dirname(__FILE__).'/../include/newheader.phtml');?>	

<div id="setting_page">
<div class="mid title">
	  <div id="setting_header_title"><span class='text'><?php echo $this->lang->global->nav->setting;?></span></div>
	   <div id="setting_header_img"><h2><?php echo $this->lang->global->setting_header_text;?></h2></div>
 </div>
 
  <div class="mid">
	<div id="setting_menu">
	    <ul id="right_menu">
	        <li><a href="/setting" class="off"><?php echo $this->lang->setting->menu->basic;?></a></li>
	        <li><a href="/setting/avatar" class="off"><?php echo $this->lang->setting->menu->avatar;?></a></li>
	        <li><a href="/setting/password" class="on"><?php echo $this->lang->setting->menu->password;?></a></li>
	        <li><a href="/setting/privacy" class="off"><?php echo $this->lang->setting->menu->privacy;?></a></li>
	        <li><a href="/setting/cell" class="off"><?php echo $this->lang->setting->menu->cell;?></a></li>
	        <?php if ($this->config->msn_robot->enabled) { ?>
	        <li><a href='/setting/im' class="off"><?php echo $this->lang->setting->menu->im;?></a></li>
	        <?php } ?>	  	        
	        <li><a href="/setting/sync" class="off"><?php echo $this->lang->setting->menu->sync;?></a></li>
	        <li><a href="/setting/email" class="off"><?php echo $this->lang->setting->menu->email;?></a></li>
	         <?php if (!$this->config->lbs->promotion) { ?><li><a href="/tools/lbs" class="off"><?php echo $this->lang->tools->lbs->title;?></a></li><?php } ?>
	        <li><a href="/tools/share" class="off"><?php echo $this->lang->tools->share->title;?></a></li>
	        <?php if ($this->bedoUid) {?>
	        <li><a href="/setting/bedoimport" class="off"><?php echo $this->lang->setting->menu->bedoimport;?></a></li>
	        <?php } else {?>
	        <li><a href="/setting/bedobind" class="off"><?php echo $this->lang->setting->menu->bedoimport;?></a></li>
	        <?php }?>
	    </ul>
	 </div>
    <div id="setting_content" >
		<div class="setting_main">
		
  	 		<h2><?php echo $this->lang->setting->password->title;?></h2>
		 
    	<div class="userinfo">
    	<form>
    	<div class="snotice hide" id='set_password_error'>
    	    <?php echo $this->lang->setting->password->error;?>
    	</div>
    	<div class="snotice hide" id='set_password_success'>
    	    <?php echo $this->lang->setting->password->success;?>
    	</div>	    	
    		<?php if ($this->fromHash==false) {?>
    		<div class="row">
    			<label for="old_pass"><?php echo $this->lang->setting->password->old->title;?></label>
    			<div class="field">
			  	     <input type="password" size="30" id="old_pass" name="old_pass" class='binput' value=""/>
			  	     <span class='err' id='err_old_pass'></span>
			  	</div>
			</div>	    	
			<?php } ?>
    		<div class="row">
    			<label for="pass"><?php echo $this->lang->setting->password->new->title;?></label>
    			<div class="field">
			  	     <input type="password" size="30" id="pass" name="pass" class='binput' value=""/>
			  	     <span class='err' id='err_pass'></span>
			  	     <span class="help">(<?php echo $this->lang->setting->password->new->tips;?>)</span>
			  	</div>
			</div>
			<div class="row">
    			<label for="repass"><?php echo $this->lang->setting->password->again->title;?></label>
    			<div class="field">
			  	     <input type="password" size="30" id="repass" name="repass" class='binput' value=""/>
			  	     <span class="help">(<?php echo $this->lang->setting->password->again->tips;?>)</span>
			  	</div>
			</div>
			<br>
    		<input type="button" id="btnPwd" value="<?php echo $this->lang->setting->password->button_tips;?>" class="btn save"/>
    		<input type='hidden' id='from_hash' value='<?php echo $this->fromHash ? '1' : '0';?>' />
		</form>
		</div>
    </div>
    <div style="height:30px;"></div>
    </div>
	 
	    
	<div class="clearfix"></div>   
  </div><!--#mid-->
</div> <!--#content-->

<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>

</body>
</html>
<?php $this->Gz();?>