<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
<body id="setting">

<?php include_once(dirname(__FILE__).'/../include/newheader.phtml');?>	

<div id="setting_page">
<div class="mid title">
	  <div id="setting_header_title"><span class='text'><?php echo $this->lang->global->nav->setting;?></span></div>
	  <div id="setting_header_img"><h2><?php echo $this->lang->global->setting_header_text;?></h2></div>
 </div>
 
  <div class="mid">
	<div id="setting_menu">
	    <ul id="right_menu">
	        <li><a href="/setting" class="off"><?php echo $this->lang->setting->menu->basic;?></a></li>
	        <li><a href="/setting/avatar" class="off"><?php echo $this->lang->setting->menu->avatar;?></a></li>
	        <li><a href="/setting/password" class="off"><?php echo $this->lang->setting->menu->password;?></a></li>
	        <li><a href="/setting/privacy" class="on"><?php echo $this->lang->setting->menu->privacy;?></a></li>
	        <li><a href="/setting/cell" class="off"><?php echo $this->lang->setting->menu->cell;?></a></li>
	        <?php if ($this->config->msn_robot->enabled) { ?>
	        <li><a href='/setting/im' class="off"><?php echo $this->lang->setting->menu->im;?></a></li>
	        <?php } ?>	  	        
	        <li><a href="/setting/sync" class="off"><?php echo $this->lang->setting->menu->sync;?></a></li>
	        <li><a href="/setting/email" class="off"><?php echo $this->lang->setting->menu->email;?></a></li>
	         <?php if (!$this->config->lbs->promotion) { ?><li><a href="/tools/lbs" class="off"><?php echo $this->lang->tools->lbs->title;?></a></li><?php } ?>
	        <li><a href="/tools/share" class="off"><?php echo $this->lang->tools->share->title;?></a></li>
	        <?php if ($this->bedoUid) {?>
	        <li><a href="/setting/bedoimport" class="off"><?php echo $this->lang->setting->menu->bedoimport;?></a></li>
	        <?php } else {?>
	        <li><a href="/setting/bedobind" class="off"><?php echo $this->lang->setting->menu->bedoimport;?></a></li>
	        <?php }?>
	    </ul>
	</div>
	 <div id="setting_content" >
		<div class="setting_main">
		
  	 		<h2><?php echo $this->lang->setting->menu->privacy;?></h2>
		   
	    	<div class="userinfo">
	    	<form>
	    	<div class="setting_notice hide" id='set_privacy_success'>
	    	   <?php echo $this->lang->setting->privacy->success;?>
	    	</div> 	    	
	    		<div class='row'>
	    			<!-- <div class='field'>
	    				<input type='checkbox' name='priv_blog' id='priv_blog' <?php if ($this->user['priv_blog']=='1') {?>checked='checked' <?php } ?>/> 
	    				<span for='priv_blog'><?php echo $this->lang->setting->privacy->msg->protect->tips;?></span>
	    			</div>
	    			 -->
	    			<div class='field'>
	    				<input type='checkbox' name='friend_sent_msg' id='friend_sent_msg' <?php if ($this->user['friend_sent_msg']=='1') {?>checked='checked' <?php } ?>/> 
	    				<span for='friend_sent_msg'>只允许好友给我发私信</span>
	    			</div>
	    			<div class='field'>
	    				<input type='checkbox' name='allow_rt' id='allow_rt' <?php if ($this->user['allow_rt']=='0') {?>checked='checked' <?php } ?>/> 
	    				<span for='allow_rt'>不允许转发我的动态</span>
	    			</div>
	    			<!-- <div class='field'>
	    				<input type='checkbox' name='sync_badge' id='sync_badge' <?php if ($this->user['sync_badge']=='1') {?>checked='checked' <?php } ?>/> 
	    				<span for='sync_badge'>当获得勋章时，自动发送同步消息</span>
	    			</div>
	    			 -->
	    			
	    		</div>
				
	    		<input type="button" id='btnPrivacy' value="<?php echo $this->lang->setting->privacy->button_tips;?>" class="save btn"/>
			</form>
			</div>
	    </div>
	    <div style="height:130px;"></div>
	 </div>
	
	    
	 <div class="clearfix"></div>
  </div><!--#mid-->
</div> <!--#content-->

<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>

</body>
</html>
<?php $this->Gz();?>