<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title><?php echo $this->title;?></title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<base href="<?php echo BETTER_BASE_URL;?>/" />
<?php echo $this->headMeta();?>
<link rel="stylesheet" type="text/css" href="css/admin.css" />
<script type='text/javascript' src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
<script type='text/javascript' language='javascript'>
var BASE_URL = '<?php echo BETTER_BASE_URL;?>';
var BETTER_ADMIN_URL = '<?php echo BETTER_BASE_URL.'/admin';?>';
var betterLang = new Object();
</script>
<?php echo $this->headLink();?>
</head>


<body style='background:#eee;'>
<table class='kai_table'>
				<tr>
					<td>
					[<a href='<?php echo $this->admin_url;?>/act/search/a/post_shout' target='act_content'>发布吼吼</a>]&nbsp;
					[<a href='<?php echo $this->admin_url;?>/act/search/a/post_tips' target='act_content'>发布贴士</a>]&nbsp;
					[<a href='<?php echo $this->admin_url;?>/act/search/a/check_in' target='act_content'>签到</a>]&nbsp;
					[<a href='<?php echo $this->admin_url;?>/act/search/a/del_blog' target='act_content'>删除微博</a>]&nbsp;
					[<a href='<?php echo $this->admin_url;?>/act/search/a/follow' target='act_content'>关注他人</a>]&nbsp;
					[<a href='<?php echo $this->admin_url;?>/act/search/a/unfollow' target='act_content'>取消关注</a>]&nbsp;
					[<a href='<?php echo $this->admin_url;?>/act/search/a/follow_request' target='act_content'>请求关注</a>]&nbsp;
					[<a href='<?php echo $this->admin_url;?>/act/search/a/block' target='act_content'>阻止他人</a>]&nbsp;
					[<a href='<?php echo $this->admin_url;?>/act/search/a/unblock' target='act_content'>取消阻止</a>]&nbsp;
					[<a href='<?php echo $this->admin_url;?>/act/search/a/signup' target='act_content'>注册</a>]&nbsp;
					[<a href='<?php echo $this->admin_url;?>/act/search/a/update' target='act_content'>修改资料</a>]&nbsp;
					[<a href='<?php echo $this->admin_url;?>/act/search/a/update_avatar' target='act_content'>修改头像</a>]&nbsp;
					[<a href='<?php echo $this->admin_url;?>/act/search/a/upload' target='act_content'>上传附件</a>]&nbsp;
					[<a href='<?php echo $this->admin_url;?>/act/search/a/direct_message' target='act_content'>发送私信</a>]&nbsp;
					[<a href='<?php echo $this->admin_url;?>/act/search/a/create_poi' target='act_content'>新建POI</a>]&nbsp;
					[<a href='<?php echo $this->admin_url;?>/act/search/a/poll_poi' target='act_content'>POI投票</a>]&nbsp;
					[<a href='<?php echo $this->admin_url;?>/act/search/a/login' target='act_content'>登陆</a>]&nbsp;
					[<a href='<?php echo $this->admin_url;?>/act/search/a/logout' target='act_content'>退出</a>]&nbsp;
					[<a href='<?php echo $this->admin_url;?>/act/search/a/friend_request' target='act_content'>好友请求</a>]&nbsp;
					[<a href='<?php echo $this->admin_url;?>/act/search/a/friend_with' target='act_content'>同意好友请求</a>]&nbsp;
					[<a href='<?php echo $this->admin_url;?>/act/search/a/reject_friend' target='act_content'>拒绝好友请求</a>]&nbsp;
					[<a href='<?php echo $this->admin_url;?>/act/search/a/unfriend_with' target='act_content'>删除好友</a>]&nbsp;
					[<a href='<?php echo $this->admin_url;?>/act/search/a/favorite' target='act_content'>收藏微博</a>]&nbsp;
					[<a href='<?php echo $this->admin_url;?>/act/search/a/unfavorite' target='act_content'>取消收藏微博</a>]&nbsp;
					</td>
				</tr>
			</table>
</body>
</html>