<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta name="viewport" content="width=device-width; initial-scale=1.4; minimum-scale=1.0; maximum-scale=2.0"/>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><?php echo $this->lang->global->meta->title;?></title>
	<?php include_once(dirname(__FILE__).'/../include/textcss.phtml');?>
</head>
<body>
	<?php include_once(dirname(__FILE__)."/../include/logo.phtml")?>
	<div id="headinfo">	
		<a href="/mobile/user?uid=<?php echo($this->userInfo["uid"])?>" ><?php echo($this->userInfo["nickname"])?></a>@
		<?php 
			if( (int)($this->lastcheckin['poi']['poi_id']) < 1 ){
				echo "<a href=\"/mobile/search\">".$this->lang->mobile->global->whereplace."</a>";
			}else{
				echo "<a href=\"/mobile/place?pid=".$this->lastcheckin['poi']['poi_id']."\">".$this->lastcheckin['poi']['name']."</a>";
			}
			
		?>
	</div>
	<?php if(strlen($this->errorinfo)>0){?>
	<div id="error"><?php echo $this->errorinfo;?></div>
	<?php }?>
	<div id='user_basic_info'>
		<table>
			<tr valign="top" >
				<td><img alt="avatar" src="<?php echo $this->userInfo["avatar_normal"]?>" /></td>				
				<td align="left">
				<?php 
				if($this->uid!=BETTER_SYS_UID){										
				?>
					<span class='exp_user_info'>
						<a href="/mobile/user/crown?uid=<?php echo $this->uid?>"><?php echo $this->lang->mobile->user->mayorship->noun."</a>".$this->userInfo['majors'];?>
					</span>
					<span class='exp_user_info'>
						<a href="/mobile/user/badge?uid=<?php echo $this->uid;?>"><?php 					
						echo $this->lang->user->badge."</a>".Better_User_Badge::getInstance($this->userInfo['uid'])->getBadgesnum();?>
					</span>
					<span class='exp_user_info'>
						<a href="/mobile/user/friend?uid=<?php echo $this->uid?>"><?php echo $this->lang->user->friends."</a>".count(Better_User::getInstance($this->userInfo['uid'])->friends);
						?>
					</span>
					<span class='exp_user_info'>
						<a href="/mobile/user/visitor?uid=<?php echo $this->uid?>"><?php echo $this->lang->mobile->user->visitor->noun."</a>".count(Better_User::getInstance($this->userInfo['uid'])->visitors);?>
					</span>
					<!-- 
					<span class='exp_user_info'>
						<a href="/mobile/user/following?uid=<?php echo $this->uid?>"><?php echo $this->lang->user->followings."</a>".$this->userInfo["followings"];?>
					</span>
					<span class='exp_user_info'>					
						<a href="/mobile/user/follower?uid=<?php echo $this->uid?>"><?php echo $this->lang->user->followers."</a>".$this->userInfo["followers"];?>
					</span>
					 -->
					<span class='exp_user_info'>
					<a href="/mobile/user/checkin?uid=<?php echo $this->uid?>"><?php echo $this->lang->user->checkins."</a>".$this->userInfo["checkins"];?>
					</span>					
					<?php if($this->isTa){?>
					<span class='exp_user_info'>
						<a href="/mobile/user/favorite?cat=poi"><?php echo $this->lang->mobile->user->favorites."</a>".$this->favoritesnum;}?>
					</span>
					<span class='exp_user_info'>	
						<a href="/mobile/user/tips?uid=<?php echo $this->uid;?>"><?php echo $this->lang->user->tips; ?></a><?php echo $this->tipsnum;?>
					</span>
					<?php 
					}
					?>
				</td>
			</tr>	
		</table>	
		</div>
		<hr>
		<div id='user_chengju'>	
		<?php 			
			echo "Karma:".intval($this->userInfo["rp"])."<br/>";			
		?>
		<?php echo $this->userInfo['self_intro'] . "<br/>"; ?>
		</div>
		<div id='user_candoing'>
		<?php 
			if($this->isTa != false){
				echo "<a href=\"/mobile/user/docheckin\">".$this->lang->javascript->global->checkin->title."</a>|<a href=\"/mobile/user/shout?cat=normal\">".$this->lang->javascript->global->shout->text."</a>";
			}else{ 
				if( !$this->isBlocked ){
					if($this->uid!=BETTER_SYS_UID){
						echo "<a href=\"/mobile/user/addfriend?uid=".$this->uid."&add=".$this->isAddFriend."\">".$this->isFriendLabel."</a>";
					}
					echo "|<a href=\"/mobile/notification/send?uid=".$this->uid."\">".$this->lang->user->message."</a>|<a href=\"/mobile/user/addblock?uid=".$this->uid."&add=".$this->isAddBlock."\">".$this->isBlockedLabel."</a>";
				}
			}?> 
		</div>	
		<div id='category'>
		<?php 
			if( !$this->isTa )
				echo $this->lang->mobile->global->footprint;
			else
				echo $this->lang->mobile->global->footprint."|<a href=\"/mobile/notification\">".$this->lang->user->notices."</a>(".$this->notificationsnum.")<br/>";
		?>
		</div>
	<div id="content">
		
		<table>
				<?php for($i=0; $i < count($this->timeline); $i++) { ?>
					<!-- author and place -->
					<tr valign="top"><td>
					<?php echo ($i+1).".";?>
					</td><td>
					
					<?php
						$author = ""; 
						if($this->timeline[$i]['type']=='todo'){
							$author = $author."<a href=\"/mobile/user?uid=".$this->timeline[$i]['uid']."\">".$this->timeline[$i]['nickname']."</a>";
							if( $this->timeline[$i]['poi']['poi_id'] ){							
								$author = $author." 想去 @<a href=\"/mobile/place?pid=".$this->timeline[$i]['poi']['poi_id']."\">".$this->timeline[$i]['poi']['name']."</a>";
							}
							if(strlen($this->timeline[$i]["message"])>0){
								$author = $author.': ';
							}
						}else{
							$author = $author."<a href=\"/mobile/user?uid=".$this->timeline[$i]['uid']."\">".$this->timeline[$i]['nickname']."</a>";
							if( $this->timeline[$i]['poi']['poi_id'] ){							
								$author = $author."@<a href=\"/mobile/place?pid=".$this->timeline[$i]['poi']['poi_id']."\">".$this->timeline[$i]['poi']['name']."</a>:";
							}else{
								$author = $author.":";
							}
						}
						echo $author;
					?>
					
	               	<?php 
	               	echo $this->timeline[$i]['message'];
	               	$checktype = ("checkin" == $this->timeline[$i]['type'])? 0:1;
	               	if($this->timeline[$i]['attach_tiny']){
	               		echo "<br/><img src=\"".$this->timeline[$i]['attach_tiny']."\"/><br/>";
	               	}
	               	?>
	               	<?php
	           			switch( $this->timeline[$i]['type'] ){
	           				case "normal":
	           					echo "[".$this->lang->mobile->user->shout->noun."]";
	           					break;
	           				case "tips":
	           					echo "[".$this->lang->mobile->user->tip->noun."]";
	           					break;
	           				case "checkin":
	           					echo "[".$this->lang->mobile->user->checkin->noun."]";
	           					break;
	           			} 
	           			?>
	           		<!-- original messge if there is -->
	           		<?php 	// original messge if there is 
	           		
	           		$upbid = $this->timeline[$i]['upbid'];
	           		$upblog = $this->retwitter[$upbid];
	           		if($this->timeline[$i]['showrt'] && $this->timeline[$i]['upbid'] && $upblog){    			
	           			
	           			if($upblog['type']=='todo'){
		           			$senderinfo = "//<a href=\"/mobile/user?uid=".$upblog['uid']."\">".$upblog['nickname']."</a>";
		           			if( $upblog['poi']['poi_id'] ){
		           				$senderinfo .= " 想去 @<a href=\"/mobile/place?pid=".$upblog['poi']['poi_id']."\">".$upblog['poi']['name']."</a>";
		           			}
	           				if(strlen($upblog['message']) >0){
								$senderinfo = $senderinfo.': ';
							}
	           			}else{
		           			$senderinfo = "//<a href=\"/mobile/user?uid=".$upblog['uid']."\">".$upblog['nickname']."</a>";
		           			if( $upblog['poi']['poi_id'] ){
		           				$senderinfo .= "@<a href=\"/mobile/place?pid=".$upblog['poi']['poi_id']."\">".$upblog['poi']['name']."</a>:";
		           			} else {
		           				$senderinfo = $senderinfo.":";
		           			}
	           			}
	           			if( strlen($upblog['message']) >0 ){
	           				$senderinfo .= $upblog['message'];
	           			}
	           			if($upblog['attach_tiny']){	           			
	               			$senderinfo .= "<br/><img src=\"".$upblog['attach_tiny']."\"<br/>";
	               		} 
	           			if( strcmp($upblog['type'], "checkin")==0 ){
	           				$senderinfo .= "[".$this->lang->javascript->global->checkin->title."]";
	           			}
	           			echo $senderinfo;
	           		    		
	           		// original end	
	           		}?> 
	           		</td></tr>     		
	           		<!-- publication time -->
	           		<tr><td></td><td>
	               	<?php echo Better_Functions::compareTime($this->timeline[$i]['dateline']); ?>
	               	<?php
	               		$source = $this->timeline[$i]['source'];
	               		if($source){
	               			echo $this->lang->user->from.Better_Functions::source($source);
	               		}
	               		if($this->timeline[$i]['uid']!=$this->user['uid'])
	           			{
	           				if($this->timeline[$i]['priv_blog']==0){
	           					echo " <a href=\"/mobile/user/shout?cat=".$this->timeline[$i]['type']."&upbid=".$this->timeline[$i]['bid']."\">".$this->lang->javascript->global->blog->rt."</a> ";
	           				}
	           			}
	           			else
	           			{
	           				echo " <a href=\"/mobile/user/delblog?id=".$this->timeline[$i]['bid']."\">".$this->lang->javascript->global->blog->delete_it."</a> ";
	           			}
	           			if($checktype) {
	           				echo " <a href=\"/mobile/user/addfavorite?cat=".$this->timeline[$i]['type']."&id=".$this->timeline[$i]['bid']."&fid=".$this->timeline[$i]['uid']."\">".$this->lang->javascript->global->favorite->title."</a> ";	       
	           			} 
	               	?>
	               	</td></tr>
	           <?php }?>           
		</table>
		<?php 
		if(strlen($this->error_info)>0){
		?>
	<div id="error"><?php echo $this->error_info;?></div>
	<?php 
		} else  if( count($this->timeline) < 1 ) {
			echo("<p>".$this->lang->mobile->global->record_none."</p>"); 
		}
		if ($this->hasMore){
	        	echo "<p><a href='/mobile/user/post?uid=".$this->uid."&page=1'>".$this->lang->global->foot->sync->more."</a></p>";
		}?>		
	</div>
		
	</div>
		
	<div id="visitors">
	</div>
	<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>
</body>
</html>