<div class='place_post' id='dlgSendMessage'>

	   <div class='now_address'>
	    	<img src="images/icon_place.png" alt=""/> <span class="address" id='place_post_address'>说点啥呢 ?
	    	</span>
	    </div>
	    	    
	    	<form name="formSendMsg" id="formSendMsg">
	    	<table cellspacing='0'>
	    		<tbody>
	    			<tr>
	    				<td>
	    				<textarea name="msg_content" id="msg_content" rows="6" ></textarea>
	    				</td></tr>
	    				<tr><td>
	    				<div style='float:right;'><input class="button btn" type="button" name="btn_send_msg" id="btn_send_msg" value="发送私信" />
	    				<input type="hidden" id="msg_receiver" name="msg_receiver" value='' />
	    				<input type="hidden"  id="msg_id" name="msg_id" value='' />
	    				</div>
	    				</td>
	    			</tr>
	    		</tbody>
	    	</table>

	    	</form>

</div>