			<table class='kai_table'>
				<tr>
				<td class='center'>
				<i>Exec Time: <?php echo $this->execTime();?> s</i>
				</td>
			</tr>	
			</table>

<div id='divFbMessage' class='hide' title=''></div>
<div id='divFbSendMessage' class='hide'>
<div id='betterMessageBox' class='hide' title='' style="overflow: visible; "></div>
<div id='betterConfirmBox' class='hide' title='' style="overflow: visible; "></div>
<div id='betterFormBox' class='hide' title='' style="overflow: visible; "></div>
<?php include_once(dirname(__FILE__).'/dmessage.phtml');?>
</div>

</body>
</html>