<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
<body id="index">

<?php include_once(dirname(__FILE__).'/../include/newheader.phtml');?>	

<div id="content">
  <div class="mid">

	  <div id="half_left">
	    <div class="big_box">
	     <!-- <div class="fill"></div>  --> 
	      <div class="updatestatus">
	      	<a class='left' href='/tools' title='<?php echo $this->lang->global->down_tips;?>'><img id='down_img' src="images/downtocell.png?v=<?php echo BETTER_VER_CODE;?>" style='margin-right: 5px; ' /></a>
	      	<a class='left' id="checkinaa" href="/pois" disable='disable'><img id='checkin_img' src="images/check-in.png?v=<?php echo BETTER_VER_CODE;?>" alt="" style="margin-right: 5px; " /></a>
	      	<a class='left' id="shouta" href="#status"><img id='shout_img' src="images/shout.png?v=<?php echo BETTER_VER_CODE;?>" alt="" /></a>
	      </div>
	    </div>
	    <?php if(Better_Registry::get('sess')->get('partner_sign_str')){?>
		  <div class='hide tip_box' id='tip_box'>
		    	<a id='close_tips' class='close' href='javascript: void(0);' title='关闭'></a>
			    <p>
			    <?php 
			    	echo Better_Registry::get('sess')->get('partner_sign_str');
			    	Better_Registry::get('sess')->set('partner_sign_str','');
			    ?>
			    </p>
		    </div>
	    <?php } else if($this->config->enable_home_tips && $this->friendsCount<=0){?>
	    <!-- 提示框 -->
	    <div class='hide tip_box' id='tip_box'>
	    	<a id='close_tips' class='close' href='javascript: void(0);' title='关闭'></a>
		    <p>
		    <?php 
		    	if($this->friendsCount<=0){
		    		echo $this->lang->global->home_tips_content;
		    	}
		    ?>
		    </p>
	    </div>
	    <?php }?>
	    
	    <div id="data">
			<div class="tabs">
	            <ul class="tabNavigation">
	                <li><a href="#followings" class='first'>好友动态</a></li>
	                <!--  <li><a href="#aroundme"><?php //echo $this->lang->home->aroundme;?></a></li> -->
	                <?php if ($this->config->rt_me) { ?><li><a href="#rtmine" ><?php echo $this->lang->home->rtmine.($this->newRtCount>0 ? "({$this->newRtCount})" : "") ;?></a></li><?php } ?>
	                <!-- <li><a href="#all"><?php echo $this->lang->home->newmajors;?></a></li>  -->
	            </ul>
	            <div id="followings">
	            	<table class="blog_table">
	            		<tbody id='tbl_followings'>
	            				<tr class='tbl_tr_ajax_loading'>
	            					<td colspan='8' class='tbl_ajax_loading'>
	            						<img src='images/ajax_loading.gif' alt='' />
	            					</td>
	            				</tr>
	            		</tbody>
	            	</table>
					<table class='pager'>
						<tr>
						<td>
							<div class="page pager" id='pager_followings'></div>
						</td>
						</tr>
					</table>	
	            </div>
	            
	            <!-- <div id="aroundme" style='display:none'>
	            	<table class="blog_table">
	            		<tbody id='tbl_aroundme'></tbody>
					</table>
					<table class='pager'>
						<tr>
						<td>
							<div class="page pager" id='pager_aroundme'></div>
						</td>
						</tr>
					</table>
	            </div>	            	


	            <div id="all" style='display:none'>
	            	<table class="blog_table">
	            		<tbody id='tbl_all'></tbody>
					</table>
					<table class='pager'>
						<tr>
						<td>
							<div class="page pager" id='pager_all'></div>
						</td>
						</tr>
					</table>
	            </div>	    
	             -->   
	                 
				<div id="rtmine" style='display:none'>
	            	<table class="blog_table">
	            		<tbody id='tbl_rtmine'></tbody>
					</table>
					<table class='pager'>
						<tr>
						<td>
							<div class="page pager" id='pager_rtmine'></div>
						</td>
						</tr>
					</table>
	            </div>	    
	        </div><!--#tabs-->
        
	  	</div><!--#data-->	
	  </div><!--#half_left-->
	  <?php include_once(dirname(__FILE__).'/../include/rightbar.phtml');?>
  </div><!--#mid-->
</div> <!--#content-->
<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>

</body>
</html>
<?php $this->Gz();?>