	<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
	
	<body>
		<div class='content_wraper'><div id="list">
		<div style='width: 100%; text-align:left; background-color:#D3DCE3;'>[<a href='/admin/picture' class='left'>所有图片</a>] [<a href='/admin/useravatar?avatar=1' class='left'>用户头像</a>] [<a href='/admin/photo?photo=1' class='left' style="color:#FF0000;font-weight:bold">用户图片</a>][<a href='/admin/useravatar?avatar=1&advance=1&view_type=2'' class='left'>掌门头像</a>]</div>
		<div style="margin: 10px auto;">
			<form action="<?php echo $this->admin_url;?>/photo" id="search_form">
			<table class='kai_table'>
			<tr><th colspan='6' class='center'>搜索</th></tr>
			<tr>
				<td width='10%'>微博关键字:</td>
				<td width='15%'><input type='text' name='keyword' id='keyword' value='<?php echo $this->params['keyword'];?>' /></td>
				<td width='10%'>用户关键字:</td>
				<td width='15%' ><input type='text' name='user_keyword' id='user_keyword' value='<?php echo $this->params['user_keyword'];?>' /></td>
				<td width='10%'>Bedo号精确查找:</td>
				<td width='15%' ><input type='text' name='bedo_no' id='bedo_no' value='<?php echo $this->params['bedo_no'];?>' /></td>
			</tr>			
			<tr>
				<td>时间范围:</td>
				<td colspan='3'>
				从 <input type='text' name='from' id='from' value='<?php echo $this->params['from'];?>' readonly='readonly' />
				到 <input type='text' name='to' id='to' value='<?php echo $this->params['to'];?>' readonly='readonly' />
				</td>

				<td>每页结果数:</td>
				<td>
				<select name='page_size' id='page_size'>
					<option value='<?php echo BETTER_PAGE_SIZE;?>' <?php echo $this->params['page_size']==BETTER_PAGE_SIZE ? ' selected="selected"' : '';?>>默认(<?php echo BETTER_PAGE_SIZE;?>)</option>
					<option value='50' <?php echo $this->params['page_size']==50 ? ' selected="selected"' : '';?>>50</option>
					<option value='100' <?php echo $this->params['page_size']==100 ? ' selected="selected"' : '';?>>100</option>
					<option value='99999999' <?php echo $this->params['page_size']==99999999 ? ' selected="selected"' : '';?>>全部</option>
				</select>
				</td>
			</tr>			
		<!-- <tr>
				<td>快捷方式:</td>
				<td colspan='5' class='left'>
				<input type='button' id='btnQuickToday' value='今天的所有微博' class='quick' />
				<input type='button' id='btnQuickPhoto' value='所有带图片的微博' class='quick' />
				</td>
			</tr>	 -->								
			<tr>
				<td colspan='6' class='center'>
					<input type='submit' value='搜索(s)' accesskey='s' />
					<input type='button' value='清空搜索结果(r)' accesskey='r'  id='btnReset' />
					<input type='hidden' name='page' id='page' value='<?php echo $this->params['page'];?>' />
					<input type='hidden' name='reload' id='reload' value='0' />
					
				</td>
			</tr>
			</table>		
			</form>
		</div>

			<table cellspacing="0" class='kai_table'>	
				<tr>
					<td colspan='10' class='pager'>
					<?php echo $this->paginator();?>
					</td>
				</tr>					
		
				<?php if ($this->count>0) { ?>
				<?php 
					$i = 0;
					$j = 1;
					$colcount = 4;//列数 
				?>
				
				<tr class='<?php echo fmod($i++,2)==0 ? 'light' : 'dark';?> message_row'>
				<?php foreach ($this->rows as $row) {
						$bbid =  str_replace('.', '_', $row['bid']);//JQuery ID选择器不支持小数点，为了后面的使用，替换成下划线
				?>
					<td class='message_col'>
					<div id="<?php echo $bbid;?>_div" class='hide'>
						<table>
							<tr>
								<td>ID</td>
								<td><?php echo $row['uid']?></td>
							</tr>
							<tr>
								<td>头像</td>
								<td><img src='<?php echo $row['avatar_thumb'];?>' width='48'  class='avatar'/></td>
							</tr>
							<tr>
								<td>Email</td>
								<td><?php echo $row['email']?></td>
							</tr>
							<tr>
								<td>用户名</td>
								<td><?php echo $row['username']?></td>
							</tr>
							<tr>
								<td>昵称</td>
								<td><?php echo $row['nickname']?></td>
							</tr>
							<tr>
								<td>姓名</td>
								<td><?php echo $row['realname']?></td>
							</tr>
							
							<tr>
								<td>自我介绍</td>
								<td><?php echo $row['self_intro']?></td>
							</tr>
							<tr>
								<td>位置描述</td>
								<td><?php echo $row['address']?></td>
							</tr>
							<tr>
								<td>发布时间</td>
								<td><?php echo date('Y-m-d H:i:s', $row['dateline']);?></td>
							</tr>
						</table>
					</div>
					<table>
						<tr>
							<td style="border: 0px;"><input type='checkbox' name='bids[]'  value='<?php echo $row['bid'];?>' /></td>
							<td style="border: 0px;" class='messages'>
								<div class='msg_row'><?php echo $this->highlight($row['message'], $this->params['keyword']);?></div>
								<div class='attach_row'>
									<a href='<?php echo $row['attach_url'];?>' class='msg_attach'><img id='<?php echo $bbid ;?>' src='<?php echo $row['attach_tiny'];?>' class="attach" /></a>
								</div>
								<!-- <div class='attach_desc'>
									<?php echo $row['filename'];?> (<?php echo $row['attach_size'];?>)  
								</div>  -->
								<a href='<?php echo BETTER_BASE_URL;?>/<?php echo $row['username'];?>' target='_blank'><?php echo $row['username'];?></a><br>
								<?php echo date('Y-m-d H:i:s', $row['dateline']+BETTER_8HOURS)?>
							</td>
						</tr>
					</table>
					
					</td>
				<?php if($j==count($this->rows) && fmod($j, $colcount)!=0 && $j>$colcount){//生成空的单元格
					for($c=0; $c<$colcount-fmod(count($this->rows),$colcount); $c++){?>
						<td>&nbsp;</td>	
				<?php }
				}?>
				
				<?php if(fmod($j++,$colcount)==0){?>
					</tr><tr class='<?php echo fmod($i++,2)==0 ? 'light' : 'dark';?> message_row'>
				<?php 	
				 } 
					}?>
				</tr>
				<tr>
					<td colspan='10' class='center'>
					<input type='button' id='chooseAll1' name='chooseAll1'  value='全选(a)' accesskey='a' />
					<input type='button' id='chooseNone1' name='chooseNone1' value='全不选(n)' accesskey='n' />
					<input type='button' id='chooseReverse1' name='chooseReverse1' value='反选(v)' accesskey='v' />
				</td></tr>
				<tr><td colspan='10' class='center'>
					<select name='todo' id='todo'>
						<option value=''>请选择操作</option>
						<option value='del'>删除所选微博</option>
						<!-- <option value='reset_place'>重置微博位置</option>  -->
						<option value='del_attach'>删除附件</option>
						<!-- <option value='reset_place2'>重置微博与用户位置</option> -->
					</select>
					<input type='button' id='btnTodo' value='确定(d)' accesskey='d' />
					</td>
				</tr>					
				<?php } else {  ?>
				<tr>
					<td colspan='10' class='error center'>
					没有找到任何数据
					</td>
				</tr>				
				<?php } ?>
				<tr>
					<td colspan='10' class='pager'>
					<?php echo $this->paginator();?>
					</td>
				</tr>
			</table>	
		</div>
		</div>
	<?php include dirname(__FILE__).'/../include/footer.phtml';?>