<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
<body id="tools">
<?php include_once(dirname(__FILE__).'/../include/header.phtml');?>
<div id="nav">
  <div class="mid">
  <form method="get" action="search.html">
  	<ul>
  		<li><a href="home">首页</a></li>
  		<li><a href="user">空间</a></li>
  		<li><a href="around">雷达</a></li>
  		<li><a href="people">找朋友</a></li>
  		<li class="on"><a href="tools">工具</a></li>
  		<li><a href="setting">设置</a></li>
  		<?php include_once(dirname(__FILE__).'/../include/headersearch.phtml');?>
  	</ul>
  </form>
  </div>
</div> <!--#nav-->

<div id="center_page">
  <div class="mid">

	<div class="tabs">
	    <ul class="tabNavigation">
	        <li><a href="/tools" >Better客户端</a></li>
	        <li><a href="/tools/lbs">驴博士插件</a></li>
	        <li><a href="/tools/flash">Flash插件</a></li>
	        <li><a href="/tools/share">分享到Better</a></li>
	        <li><a href="/api" class="selected">Better API</a></li>
	    </ul>
	    <div id="tab_content">
	    	是在网上看新闻，看图片还是看小说呢？是不是发现这个新闻很震撼，那个图片很唯美，那部小说相当吸引人？
	    	独乐乐不如众乐乐，好东西是要拿出来分享的哦。
	    	使用“分享到Better”功能就能帮你以快捷的方式把你正浏览的页面共享到Better，还等什么，一起来行动吧^_^。
	    	<br/>
	    	
			
	    </div>
	   
	</div><!--.tabs-->
  </div><!--#mid-->
</div> <!--#content-->
<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>
</body>
</html>