	<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
	
	<body>
	<form id="new_banner" enctype="multipart/form-data" action="/admin/webbanner/donewbanner" method="post">
	<div id="list">
		<table class="kai_table">
			<tr>
				<th colspan='4' style="text-align:center;">新增Banner</th>
			</tr>
			
			<tr>
				<td>Link</td>
				<td colspan='3'>
					<input type='text' name='link' />
				</td>
			</tr>
			
			<tr>
				<td>图片（480）Banner：</td>
				<td colspan='3'>
				<input type='file' name='webbanner' />
				</td>
			</tr>
			<tr>
				<td>期待排序：</td>
				<td colspan='3'>
				<input id="rank" type="text" name="rank" >
					
				</td>
			</tr>
		<tr>
				<td>开始时间：</td>
				<td colspan='3'>
				<input id="begintm" type="text" name="begintm" >
					
				</td>
			</tr>
			<tr>
				<td>结束时间：</td>
				<td colspan='3'>
					<input id="endtm" type="text" name="endtm" >
				</td>
			</tr>				
					
			<tr>
				<td colspan='4' style="text-align:center;">
					<input type='button' id='banner_new' name='banner_new' value="新增" />
				</td>
			</tr>
		</table>
		</div>
		</form>
		
	<?php include dirname(__FILE__).'/../include/footer.phtml';?>