<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>

<body id="poi">
<?php include_once(dirname(__FILE__).'/../include/newheader.phtml');?>	

<?php if(!$this->poi_closed){?>
<div id="content">
	<?php if($this->bloguser){?>	
	<div class="container">
		<div class="container11"></div>
		<div class="container12"></div>
		<div class="container13"></div>
		<div class="container21"></div>
		<div class="container22">
			<div class="top-left"><a href="/<?php echo $this->bloguser['username'];?>"><img src="<?php echo $this->bloguser['avatar_normal']?>"  style="width:65px;height:65px"/></a></div>
			<div class="top-center">
				<span class="title"><span class="checkin-icon"></span><span><a href="/<?php echo $this->bloguser['username'];?>"><?php echo $this->bloguser['nickname']?></a></span> <span class="checkin_time"></span> 在 <span><?php echo $this->poiInfo['name']?></span> </span><br />				
				<div class="title" style="color:#FF0084;margin:4px 0 0 0"><?php echo $this->currentUid>0?'欢迎回来！':'欢迎您来开开！';?></div>
				<span>开开k.ai是新一代位置网络，开开帮助你与朋友分享好地方，发现好去处~快来这里赢勋章、夺掌门！用全新的方法去探索周围的城市</span>
			</div>
			<div class="top-right"><img src="/images/loginlogo.gif" /></div>
			<div class="clearfix"></div> 
		</div>
		<div class="container23"></div>
		<div class="container31"></div>
		<div class="container32"></div>
		<div class="container33"></div>	
	</div>
	<?php }?>
	
  <div class="mid">
     <div id="half_left">
		
		<div style="margin-bottom:10px" class="left-item left-border">
			<div style="padding:2px">
				<div class="poiinfo">
					<div class='top-left'>
		    			<img src="<?php echo $this->poiInfo['logo_url'];?>" width='62' alt='' />
		    		</div>
					<div class="top-center">
						<div class="title left line-width line-height24" >
							<?php if(mb_strlen($this->poiInfo['name'],'utf-8')>15){?>
								<span class="left" title="<?php echo $this->poiInfo['name'];?>"><?php echo mb_substr(htmlspecialchars($this->poiInfo['name']),0,15,'utf-8').'...';?></span>
							<?php }else{?>
								<span class="left" title="<?php echo $this->poiInfo['name'];?>"><?php echo $this->poiInfo['name']?></span>
							<?php }?>
							<span><a id="report_this_poi" href='javascript:void(0)' class="correction"></a></span>
						</div>
						<div class="left line-width line-height21" >
							<div class="left"><?php echo $this->lang->global->poi->poi_address;?></div>
							<div class="left" title="<?php echo $this->poiInfo['address'];?>"><?php	echo Better_Cutstring::mystrcut($this->poiInfo['address'], 18);?></div>
						</div>
						<div class="left  line-width line-height21" >
							<div class="left" style="white-space: nowrap;"><?php echo $this->lang->global->poi->poi_phone;?></div>
							<div class="left"><?php echo $this->poiInfo['phone'] ? $this->poiInfo['phone'] : ' - '?></div>
						</div>
						
					</div>
					<div class="top-right">
						
						<a href="javascript: void(0);" id='todoa' ref='<?php echo $this->poiInfo['poi_id'];?>' class="todo <?php echo $this->bid?"hide":""?>"></a>
						<a href="javascript: void(0);" id='checkina' ref='<?php echo $this->poiInfo['poi_id'];?>' class="<?php echo $this->bid? "checkin-l":"checkin"?>"></a>
		  				<div style="float:right;margin:0 8px 0 0"  id="action-todo" class="title <?php echo $this->bid?"":"hide"?>">
		  					<a href="javascript:void(0)" id="havebeenhere" >我去过了</a>|
		  					<a href="javascript:void(0)" id="nottodo" >不想去了</a>	  					
		  				</div>
		  				<input type="hidden" value="<?php echo $this->bid? $this->bid:""?>" id="currentbid"/> 	  				
		  			</div>
		  			
					 <div class="clearfix"></div> 
				</div>
				<div class="map">
					<form method='post'>
						<div class="map_container" >
							<div id="map_canvas" style="width: 648px; height: 182px;" class='map'></div>
						</div>
						<input type="hidden" value="" id="location_lat" />
					   	 <input type="hidden" value="" id="location_lon" />
					</form>
				</div>
			</div>
			<?php if ($this->special['total']>0) {?>	
			<div  class="left-item">		
				<div class="activities left-border">
				<div  class="activitycontent">				
					<div id="activitytitle"><?php echo $this->specialtitle;?></div>				
			     	<div class="" id="moreactivities">  		     		
			     		<?php foreach($this->special['rows'] as $key=>$row){	?>		     		
			     		<p>
			     			<?php if($row['attach_url']){?>
			     			<span class="activityimg"><a href="<?php echo $row['attach_url'];?>" class="activityimage"><img align="top"  src='<?php echo $row['attach_url'];?>'></a>	</span>		     			
			     			<?php }?>	
			     			<span>
			     			<?php echo $row['content'];?>	</span>	 	
			     		</p>
			     		
			     		<div class="clearfix"></div>
			     		<?php } ?>	
			     	</div>
			     	<div  class="expandbtn" >
				     		<div  id="morebutton" ><a class="hide"  href="javascript:void(0);" ></a></div>
					    	<div  id="lessbutton"><a  href="javascript:void(0);" ></a></div>
				    	</div>
				</div>				
<!--				<div class="activityrighttop"></div>-->
				</div>
				
				<div class="clearfix"></div>		
				  
			</div>
			<?php } ?>
			<?php if($this->displayNums['friendsHere']>0 || $this->displayNums['todoFriends']>0){?>
				<div class="friends-here">
					<div style="float:left;width:100%;font-size:13px;font-weight:bold;padding:4px 0 1px 0;color:#575F7B;">
						<?php if($this->displayNums['friendsHere']>0){?>
						<div style="float:left;padding:0 0 0 9px;width:<?php echo 49+($this->displayNums['friendsHere']-1)*53;?>px">
						
						<span style="float:left">来过的好友</span><span class="numstyle">(<?php echo $this->fcounthere;?>)</span>
						<?php if($this->heremoreshow){?>
						<a href="/poi/viewuserlist?id=<?php echo $this->poiInfo['poi_id'];?>&type=friendshere" style="float:right;font-weight:normal;font-size:12px">更多</a>
						<?php }?>
						</div>
						<?php }?>
						<?php if($this->displayNums['todoFriends']>0 && $this->displayNums['friendsHere']>0){?>
							<div style="float:left;padding:0 0 0 20px;width:<?php echo 49+($this->displayNums['todoFriends']-1)*53;?>px">
								<span style="float:left">想来的好友</span><span class="numstyle">(<?php echo $this->fcounttodo;?>)</span>
								<?php if($this->todomoreshow){?>
								<a  href="/poi/viewuserlist?id=<?php echo $this->poiInfo['poi_id'];?>&type=friendstobe" style="float:right;font-weight:normal;font-size:12px">更多</a>
								<?php }?>
							</div>
						<?php }else if($this->displayNums['todoFriends']>0 ){?>
							<div style="float:left;padding:0 0 0 9px;width:<?php echo 49+($this->displayNums['todoFriends']-1)*53;?>px">
							<span style="float:left">想来的好友</span><span class="numstyle">(<?php echo $this->fcounttodo;?>)</span>
							<?php if($this->todomoreshow){?>
							<a href="#" style="float:right;font-weight:normal;font-size:12px">更多</a>
							<?php }?>
							</div>
						<?php }?>
					</div>
					<?php if($this->displayNums['friendsHere']>0){?>
					<div style="float:left;padding:0 0 9px 9px;width:<?php echo 49+($this->displayNums['friendsHere']-1)*53;?>px">
						<?php 
							$i=0;
						foreach ($this->friendsHere as $friendhere){?>						
						<div class="user-poi-item <?php  echo $i==0? 'first-userhere-item':'';?>">
							<a href="/<?php echo $friendhere['username']?>"><img title=""  src="<?php echo $friendhere['avatar_small']?>"/></a>
						</div>
						<?php $i++;
						}?>
					</div>
					<?php }?>
					<?php if($this->displayNums['todoFriends']>0  && $this->displayNums['friendsHere']>0){?>
					<div style="float:left;padding:0 0 9px 20px;width:<?php echo 49+($this->displayNums['todoFriends']-1)*53;?>px">								
						<?php 
							$i=0;
						foreach ($this->todoFriends as $todofriend){?>						
						<div class="user-poi-item <?php  echo $i==0? 'first-usertodo-item':'';?>">
							<a href="/<?php echo $todofriend['username']?>"><img title=""  src="<?php echo $todofriend['avatar_small']?>"/></a>
						</div>
						<?php $i++;
						}?>
					</div>
					<?php }else if($this->displayNums['todoFriends']>0){?>
					<div style="float:left;padding:0 0 9px 9px;width:<?php echo 49+($this->displayNums['todoFriends']-1)*53;?>px">								
						<?php 
							$i=0;
						foreach ($this->todoFriends as $todofriend){?>						
						<div class="user-poi-item <?php  echo $i==0? 'first-usertodo-item':'';?>">
							<a href="/<?php echo $todofriend['username']?>"><img title=""  src="<?php echo $todofriend['avatar_small']?>"/></a>
						</div>
						<?php $i++;
						}?>
					</div>
					<?php }?>
				</div>
			<?php }?>
		</div>
		
		<div class="title left-noborder">
			<div class="block-title" >贴士</div>
		</div>
		<?php if (Better_Registry::get('sess')->uid > 0){?>
		<div class=" left-item left-border poi-tips">
			<form action="" style="margin:9px 10px 6px 10px;">
				<input type="hidden" id="attach" name="attach" value="">
				<input type="hidden" id="upbid" name="upbid" value="0">
				<input type="hidden" id="real_upbid" name="real_upbid" value="0">
				<input type="hidden" id="ready_to_shout_poi" value="<?php echo $this->poiInfo['poi_id'];?>">
				<div  id="tipcontainer" class="tipcontainer">
					<div class="textinput left"><textarea class="tipinput-noimg"  id="tips_status_text"   value="写个贴士分享给大家吧">写个贴士分享给大家吧</textarea></div>
					
					<div class="previewimg hide"><img id="previewImg"></img></div>
				</div>
				<div class="upload-div">
					<div class="title" id="btnUpload"><a class="photoimg" ></a><a class="phototext" href="javascript:void(0)" >上传图片</a></div>
					
					<div style="float:left;margin: 0px 0 0 10px;line-height:24px">
					<?php if($this->site_count > 0){?>
						
						<span id="shout_checkbox">
						<input type="checkbox" name="need_sync" id="need_sync" checked/>
						<?php echo $this->lang->global->include->dmessage->share; ?>
						</span>
						<span id="shout_nopublic" class="hide">
							<?php echo $this->lang->global->include->dmessage->no_public; ?>
						</span>
						
					<?php }else{?>
						<a href="setting/sync"><?php echo $this->lang->global->include->dmessage->no_bound; ?></a>
					<?php }?>	 
					</div>
					<div id="post_tip_btn">
						<a href="javascript:void(0)"  class="title" style="">发帖士</a>
					</div>
					<div class="post_tip_count" >还可以写<span class="title red" id="tips_txtCount">140</span> 个字</div>
				</div>
			</form>
		</div>
		<?php }?>
		<div class="left-item left-border">
			  <div id="tips">
	            <form>
	            	<table class="blog_table">
	            	<tbody id="tbl_tips">
					 </tbody>
					</table>
				</form>
					<table class='pager' >
						<tr>
						<td>
							<div class="page pager hide" id='pager_tips'></div>
						</td>
						</tr>
					</table>
					<table class='pager'  >
						<tr>
						<td>
							<div class=" hide page pager ie6page" id="showalltips" style="width:650px" >
								浏览更多 <img src="images/more.gif">
							</div>
						</td>
						</tr>
					</table>
	            </div>	            
		</div>
		<!-- 
		<div class="title hide" style="width:670px;float:left;margin-bottom:5px;">
			<div style="float:left">图片</div>
			<div style="float:right"><a href="javascript:void(0)" class="showallbtn" ></a></div>
		</div>
		<div class="left-item left-border hide" style="margin-bottom:10px;background:#E6EBEF;padding-bottom:12px;">
			<?php for($i=0;$i<5;$i++){?>
			<div style="border:2px solid #DCE2EA;float:left;width:115px;height:115px;margin:12px 0 0 12px;background:#FFF"></div>
			<?php }?>
		</div>
		<div class="left-item left-border hide" style="margin-bottom:10px;background:#DCE2EA;border-radius:5px 5px 0 0 ;">
			<div style="margin:5px 0 5px 12px;" class="title">团购</div>
			<div style="padding-left:12px;background:#FFF">仅需69元，即可获得原价113元巫山烤全鱼套餐一份。(草鱼套餐，鲶鱼套餐任选一套。)煎的？烤的？炸的？煮的蒸的？炖的？如果你用这么单一的方法吃鱼的话你就Out了，现在吃鱼流行多元素的了。</div>
		</div>
		<div class="left-item left-border hide" style="background:#DCE2EA;border-radius:5px 5px 0 0 ;">
			<div style="margin:5px 0 5px 12px;" class="title">微博</div>
			<div style="padding-left:12px;background:#FFF">仅需69元，即可获得原价113元巫山烤全鱼套餐一份。(草鱼套餐，鲶鱼套餐任选一套。)煎的？烤的？炸的？煮的蒸的？炖的？如果你用这么单一的方法吃鱼的话你就Out了，现在吃鱼流行多元素的了。</div>
		</div> -->
	 </div><!--#half_left-->
	 <div id="half_right" class="small_box">
	 	<div class=" checkin-info">
		    <div class='poi_detail poi_box' >
		    <div class="white-blank"></div>
		     	<div class="info">			     	   	  
			        <div  class="box-1"  > 
						<?php if ($this->poiInfo['major']>0) { ?>
			        	  	<a href="/<?php echo $this->poiInfo['major_detail']['username'];?>"><img title='<?php echo htmlspecialchars(addslashes($this->poiInfo['major_detail']['nickname'].'  '.$this->lang->global->checkin->title.$this->major_checkin_counts.$this->lang->global->count));?>' src="<?php echo $this->poiInfo['major_detail']['avatar_normal'];?>" width='43' height='43' alt='' class='poi_major_avatar' /></a>
			        	  <?php }else{ ?>
			        	  	<a href="javascript: void(0);" >
			        	  		<img src="<?php echo BETTER_BASE_URL.'/images/noavatar.gif';?>" width='43' height='43' alt='' class='poi_major_avatar' />
			        	  	</a>
			        	  <?php } ?>
			        </div>		        	
	        	  <div class="box-2" >
	        	  	<div class="major-icon"></div>
	        	  	<div class="title grayc"  style="float: left; width: 59px;"><?php echo $this->lang->global->poi->major;?></div>
	        	  	</div>	        		
				      <div class="box-3">
				      	  	<div class="checkin-count" >
					      	  	<font id='poi_checkins' style="color:#A0A5AB;font-size: 18px;font-weight: bold;"><?php echo $this->poiInfo['checkins'];?></font>
					      	  	<br/><span class="title grayc"><?php echo $this->lang->sidebar->checkins;?></span>
				      	  	</div>
				      </div>
					  <div class="box-4" >
				      	  <div class="shou-count" >
				        	 <font id='poi_shouts' style="color:#A0A5AB;font-size: 18px;font-weight: bold;"><?php echo $this->poiInfo['posts'];?></font>
				        	 <br><span class="title grayc"><?php echo $this->lang->sidebar->shouts;?></span>
				        	</div>
			        	</div>  
	        	  <div class="clearfix"></div>
		     	</div>
		     	<div class="clearfix"></div>		
			</div>
			<div class="clearfix"></div>
			<div class="tline"></div>
			<div class="nborder owner">
				<div class="owner-con" >
					<?php if($this->poiowerdetail && $this->poiowerdetail['avatar_small']){?>
						<div class="owner-img-default" >
							<a href="<?php echo BETTER_BASE_URL?>/<?php echo $this->poiowerdetail['username'];?>" title="<?php echo $this->poiowerdetail['nickname'];?>">
								<img src="<?php echo $this->poiowerdetail['avatar_small']?>"  width='43' height='43' alt='' class='poi_major_avatar' ></img>
							</a>
				        </div>
					<?php }else{?>
						<div class="owner-img-default" >
							<a href="javascript: void(0);" >
								<img src="/images/noavatar.gif"  width='43' height='43' alt='' class='poi_major_avatar' ></img>
							</a>
				        </div>
				       <?php }?>
			        <div class="owner-text">
			        	<?php if($this->poiowerdetail){?>
			        	<div class="owner-name"><a href="<?php echo BETTER_BASE_URL?>/<?php echo $this->poiowerdetail['username'];?>" title="<?php echo $this->poiowerdetail['nickname'];?>"><?php echo $this->poiowerdetail['nickname'];?></a></div>
			        	<div class="owner-tips grayc">是这里的店长</div>
			        	<?php }else{?>
			        	<div class="owner-name grayc">暂时没有店长</div>
			        	<div class="owner-tips"><a href='/venue?id=<?php echo $this->poiInfo['poi_id'];?>'>[店长认证]</a></div>
			        	<?php }?>
			        </div>
			        <div class="owner-action">
			        	<?php if($this->isowner){?>
			        	<a href="<?php echo BETTER_BASE_URL?>/poi/owner?id=<?php echo $this->poiInfo['poi_id'];?>" class="manage-in">管理入口</a>
			        	<?php }else{?>
			        	<a href="javascript:void(0)" class="owner-logo" title="店长" ></a>
			        	<?php }?>
			        </div>
				</div>
			</div>
			<div class="tline"></div>
			<div class="nborder">
				<div style="line-height:37px;text-align:center">
				<?php if($this->checkinCount > 0 && $this->deltaTime){?>
					<span>我来过这里 <span><?php echo $this->checkinCount;?></span> 次，最近一次是 <span><?php echo $this->deltaTime;?></span></span>
					<?php }else{?>
					<span>从没有在此地签过到</span>
					<?php }?>
				</div>
			</div>
		</div>
		<div class="right-content top-border" >
			<div class="white-blank"></div>
			<?php if(count($this->aroundUsers)>0){?>
			<div class="checkin-list">
				<div class="right-title">
					<div class="right-words"><h3>60天签到排行</h3></div>
					<div ><a class="right-img" href="javascript:void(0);" id="checkin-list"></a></div>
					<div ><a class="right-img-hide" href="javascript:void(0);" id="checkin-list-hide"></a></div>
				</div>
				<div id="checkin-list-content">
					<?php foreach ($this->aroundUsers as $key=>$row){?>
					<div class="checkin-item">
						<div class="img-item"><a  href="/<?php echo $row['username']; ?>"><img title="<?php echo $row['nickname']; ?>" src="<?php echo $row['avatar_small']?>" class="avatar"  style="width:30px; height: 30px;" /></a></div>
						<div class="text-item"><a title="<?php echo $row['nickname']; ?>" class="title" href="/<?php echo $row['username']; ?>"><?php echo $row['nickname']?></a></div>
						<div class="info-item" >
							<div class="date-item" ><?php echo date('m月d日',$row['checkin_time']);?></div>
							<?php switch ($key){
								case 0:$bgc="#0F7CC5";break;
								case 1:$bgc="#3093D6";break;
								case 2:$bgc="#5BB3ED";break;
								default:$bgc="#A5BED4";break;
							}?>
							<div class="count-item"  style="background:<?php echo $bgc;?>;">
								<?php if($row['times']<10) {
												echo  $row['times'].'次';
										   }elseif($row['times']>99){
										   		echo "99+";
										   }else{ 
										   		echo $row['times'];
										   }?>
								</div>
						</div>
					</div>
					<?php }?>
					<!--<?php if(count($this->aroundUsers)>=6){?>					
					<div class="morebtn">
						<a href="javascript:void(0)" >
							<span></span>
						</a>
				</div>
					<?php }?>-->
				</div>
				<div class="clearfix"></div>
			</div>
			<div class='tline distance'></div>
			<?php }?>
			<?php if(count($this->todoUsers)>0){?>
			<div class="todo-list">
				<div class="right-title">
					<div class="right-words"><h3>TA们想去这儿</h3></div>
					<div ><a id="todo-list" class="right-img" href="javascript:void(0);"></a></div>
					<div ><a class="right-img-hide" href="javascript:void(0);" id="todo-list-hide"></a></div>
				</div>
				<div id="todo-list-content" >
					<div class="todo-user-list">
				 	<?php foreach ($this->todoUsers as $todouser){?>
				 		<div class="todo-user-list-item">
				 			<a href="/<?php echo $todouser['username']?>">
				 				<img title="<?php echo $todouser['nickname'];?>" src="<?php echo $todouser['avatar_small']?>" class="avatar" style="width:30px;height:30px"></img>
				 			</a>
				 		</div>
				 	<?php }?>
				 	</div>
				 </div>
				 <div class="clearfix"></div>
			</div>
			<div class='tline  distance'></div>
			<?php }?>
			<?php if(count($this->relatedPois)>0){?>
			<div class=" related-poi">
				<div class="right-title">
						<div class="right-words"><h3>相关地点</h3></div>
						<div ><a id="related-poi" class="right-img" href="javascript:void(0);"></a></div>
						<div ><a class="right-img-hide" href="javascript:void(0);" id="related-poi-hide"></a></div>
				</div>
				 <div id="related-poi-content" >
				 	<div>
				 	<?php foreach ($this->relatedPois as $relatedpoi){?>
					  <div><a href="/poi/<?php echo $relatedpoi['poi_id']?>"><?php echo $relatedpoi['name'];?></a></div>
					 <?php }?>
					 </div>
				  </div>
				  <div class="clearfix"></div>
			</div>
			<div class='tline distance hide'></div>
			<?php }?>
			<div class="recommend-poi hide">
			  <div class="right-title">
					<div class="right-words"><h3>其他推荐</h3></div>
					<div ><a class="right-img" id="recommend-poi" href="javascript:void(0);"></a></div>
					<div ><a class="right-img-hide" href="javascript:void(0);" id="recommend-poi-hide"></a></div>
			</div>
			
			  <div id="recommend-poi-content">
				<?php foreach ($this->relatedPois as $relatedpoi){?>
					  <div><a href="/poi/<?php echo $relatedpoi['poi_id']?>"><?php echo $relatedpoi['name'];?></a></div>
				<?php }?>
			  </div>
			</div>
			
			<div class="IEclear"></div>
	   		<div class="clearfix"></div> 
		</div>
	 </div>
	 <div class="clearfix"></div> 
	   
  </div><!--#mid-->
</div> <!--#content-->

<div id="poi_report_dlg" class="hide">
	<form style="width: 100%;">
	<input type="hidden" id="poi_id_report" value="<?php echo $this->poiInfo['poi_id'];?>"/>
	<table><tr>
		<td>
		<span><?php echo $this->lang->global->poi->report->reason->title; ?></span>		
		</td><td>		
		<select id="reason_report" style="width:145px">
			<option value="incorrect" selected><?php echo $this->lang->global->poi->report->reason->incorrect; ?></option>
			<option value="closedown"><?php echo $this->lang->global->poi->report->reason->close; ?></option>
			<option value="duplicate"><?php echo $this->lang->global->poi->report->reason->repeat; ?></option>
			<option value="other"><?php echo $this->lang->global->poi->report->reason->other; ?></option>
		</select>
			</td></tr>
	<tr class="detailreason hide">
	<td >
		<span>请输入具体原因：</span>
	</td><td>
		<textarea  style="width:145px;padding:0px"></textarea>
	</td></tr>
	<tr>
	<td colspan="2" >		
	<input style="margin-top:10px" class="button btn right" type="button" id="btn_report_poi" value="<?php echo $this->lang->javascript->report->poi->denounce;?>" />
	</td></tr>
	</table>
	</form>
</div>
<?php }else{?>
	<div id="content">
		<div class='mid' style='background-color: #fff; border: 1px solid #999;'>
	  		<div style="width: 400px; margin: 60px auto; !margin: 25px auto;">
	  			<img src='images/close_place.png' alt='' class='left' />
	  			<h3><?php echo $this->lang->global->poi_closed; ?></h3>
	  			<span><?php echo $this->lang->global->back_link;?></span>
	  			<br><br>
	  			<p><?php echo $this->lang->global->poi_closed_tip; ?></p>
	  		</div>
  		</div>
	</div>
<?php }?>

<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>

</body>
</html>
<?php $this->Gz();?>
