<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
<body id="signup">
<?php include_once(dirname(__FILE__).'/../include/newheadernonav.phtml');?>	

<div id="setting_page">
  <div class="mid">
	  <div id="setting_menu">   		
		<div class="setting_right">	 
  		<?php echo $this->langTpl('signup_step3');?>
  		<?php if(strlen($this->autoregsinasucess)>0){?>
  			<li><?php echo $this->autoregsinasucess;?></li>
		<?php }?>
  	</div>
  		
  	  </div>
  	  <div id="setting_content">
  	   <div class="setting_main">
	  	<div id="form">
	  	  <div class="headertitle"></div>
	  	 <h2><?php echo $this->lang->setting->sync->title;?></h2>
		


		    <form action='' id='form_set_sync'>
<table class="sync_table" cellspacing='0'>
	    	    	<?php 
	    	    		$sites = array( 'sina'=> '新浪微博', 
	    	    					    'qq'=> '腾讯微博', 
	    	    					    'qqsns'=> 'QQ', 
	    	    					    'msn'=> 'MSN',
	    	    					    'kaixin001'=> '开心网',
	    	    					    'renren'=> '人人网',
	    	    						'douban'=> '豆瓣',
	    	    						'fanfou'=> '饭否',
	    	    						'facebook'=> 'Facebook',
	    	    						'twitter'=> 'Twitter',
	    	    						'4sq'=> 'Foursquare',
	    	    						'sohu'=> '搜狐微博',
	    	    						'163'=> '网易微博',
	    	    						'139'=> '139说客',
	    	    						'follow5'=> 'Follow5',
	    	    						'zuosa'=> '做啥'
	    	    		);
	    	    		
	    	    		foreach($sites as $site=>$name){?>
							<!-- <?php echo $site;?> -->
				    	    <tr>
				    	    	<td class='center' width='62'>
				    	    		<img src='images/3rdSite/<?php echo $site;?>.gif'/>
				    	    	</td>
				    	    	<td width='302'>
				    	    		<span class='sync_title'><?php echo $name;?></span><br>
				    	    		<?php if(isset($this->syncSites[$site.'.com'])){?>
				    	    			<span class='sync_account' id='status_<?php echo $site;?>'>已同步<?php echo $this->syncSites[$site.'.com']['username']?></span>
				    	    		<?php }else{
				    	    			echo "<span class='sync_account' id='status_$site'>未同步</span>";
				    	    		}?>
				    	    	</td>
				    	    	<td width='116'>
				    	    		<?php if(isset($this->syncSites[$site.'.com'])){?>
				    	    			<span id='sync_<?php echo $site;?>'><input type='checkbox' ref='<?php echo $site.'.com';?>' id='sync_badge_<?php echo $site;?>' <?php echo $this->syncSites[$site.'.com']['sync_badge']==1 ? 'checked': ''; ?>>勋章同步</span>
				    	    		<?php }else{ ?>
				    	    			<span id='sync_<?php echo $site;?>' class='hide'><input type='checkbox' ref='<?php echo $site.'.com';?>' id='sync_badge_<?php echo $site;?>' <?php echo $this->syncSites[$site.'.com']['sync_badge']==1 ? 'checked': ''; ?>>勋章同步</span>
				    	    		<?php }?>
				    	    	</td>
				    	    	<td width='42'>
										<?php 
										if(isset($this->syncSites[$site.'.com'])) {
											$site == '139' ? $onclick = 'onclick="unbind()"' : $onclick = '';
										?>
										<a href='javascript: void(0);' id='cancel_<?php echo $site;?>' ref='<?php echo $site;?>' <?php echo $onclick;?>>解除</a>
										<a href='javascript: void(0);' id='restore_<?php echo $site;?>' ref='<?php echo $site;?>' class='hide'>放弃</a>
										<?php 
											
											if($site=='qq'){
												$href = '/setting/sync?target=qq';
											}else if($site=='douban'){
												$href = '/setting/sync?target=douban';
											}else if($site=='qqsns'){
												$href = '/setting/sync?target=qqsns';
											}else if($site=='facebook'){
												$href = '/setting/sync?target=facebook';
											}else if($site=='163'){
												$href = '/setting/sync?target=163';
											}else if($site=='renren'){
												$href = '/setting/sync?target=renren';
											}else if($site=='4sq'){
												$href = '/setting/sync?target=4sq';
											}else if($site=='139'){
												$onclick = 'onclick="login()"';
												$href = 'javascript: void(0);';
											}else{
												$href = 'javascript: void(0);';
											}
										
										?>
										<a href='<?php echo $href;?>' <?php echo $onclick ? $onclick : '';?> id='bind_<?php echo $site;?>' ref='<?php echo $site;?>' class='hide'>同步</a>
										<?php 
										} else {
											 
										?>
										<a href='javascript: void(0);' id='cancel_<?php echo $site;?>' ref='<?php echo $site;?>' class='hide'>解除</a>
										<a href='javascript: void(0);' id='restore_<?php echo $site;?>' ref='<?php echo $site;?>' class='hide'>放弃</a>
										<?php 
										
											if($site=='qq'){
												$href = '/setting/sync?target=qq';
											}else if($site=='douban'){
												$href = '/setting/sync?target=douban';
											}else if($site=='qqsns'){
												$href = '/setting/sync?target=qqsns';
											}else if($site=='facebook'){
												$href = '/setting/sync?target=facebook';
											}else if($site=='163'){
												$href = '/setting/sync?target=163';
											}else if($site=='renren'){
												$href = '/setting/sync?target=renren';
											}else if($site=='4sq'){
												$href = '/setting/sync?target=4sq';
											}else if($site=='139'){
												$onclick = 'onclick="login()"';
												$href = 'javascript: void(0);';
											}else{
												$href = 'javascript: void(0);';
											}
										
										?>
										<a href='<?php echo $href;?>' <?php echo $onclick ? $onclick : '';?> id='bind_<?php echo $site;?>' ref='<?php echo $site;?>'>同步</a>
									<?php }?>
									
				    	    	</td>
				    	    </tr>
				    	    <tr id='func_<?php echo $site;?>' class='sync_input hide'>
				    	    	<td colspan='4'>
				    	    	<span>
				    	    		<?php 
				    	    			if($site=='facebook'){
				    	    				echo '<span class="err">绑定Facebook 需要你的浏览器同时可以访问 Facebook 和 开开 网站&nbsp;&nbsp;&nbsp; </span>';
				    	    				echo '<a href="/setting/sync?target=facebook" id="new_bind_facebook">绑定</a>';
				    	    			}else{ ?>
				    	    				<?php echo $this->lang->setting->sync->service->account;?><input type='text' id='username_<?php echo $site;?>' value=''  size='16' />
							    	    	<?php echo $this->lang->setting->sync->service->password;?><input type='password' id='password_<?php echo $site;?>' value='' size='10' />
							    	    	<?php if ($site=='sina'): ?>
							    	    	<input type="checkbox" name="followkai" id="followkai" checked="checked" />关注开开
						    	    		<?php endif;?>
						    	    		<input type='button' id='btn_<?php echo $site;?>' value='<?php echo $this->lang->setting->sync->service->bind;?>'  class='btn'/>
						    	    		<br>
						    	    		<?php 
						    	    			if($site=='digu'){
						    	    				$tips = $this->lang->setting->sync->service->digu->tips;
						    	    			}else if($site=='zuosa'){
						    	    				$tips = $this->lang->setting->sync->service->zuosa->tips;
						    	    			}else{
						    	    				$tips = '';
						    	    			}
						    	    		?>
						    	    		<span id='err_<?php echo $site;?>' class='err <?php echo !$tips ? 'hide': '';?>'><?php echo $tips;?></span>
				    	    		<?php }?>
					    	    	
				    	    	</span>
				    	    	</td>
				    	    </tr>	    	    			
	    	    		<?php }
	    	    	?>
	    	    	<tr>
		    	    	<td colspan='4' align='center'>
		    	    	
		    	    	<input style="text-align: center;" type="button" id='step3_confirm_btn' class="btn" value="<?php echo $this->lang->global->begin;?>"/>
		    	    	
		    	    	</td>
		    	    </tr>
		    	    <tr>
		    	    	<td colspan='4' >&nbsp;</td>
		    	    </tr>
	    		</table>
			</form>
	    </div>
	</div>
	  
	  </div>
	  <div class="clearfix"></div>
</div> <!--#content-->
</div>
<div id='sssss'></div>
<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>

</body>
</html>
<?php $this->Gz();?>