<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
<body id="signup">
<?php include_once(dirname(__FILE__).'/../include/newheadernonav.phtml');?>	

<div id="setting_page">
  <div class="mid">
	  <div id="setting_menu">   		
		<div class="setting_right">	 
  		<?php echo $this->langTpl('signup_step4');?>
</div>
  		
  	  </div>
  	  <div id="setting_content">
  	   <div class="setting_main">
	  	<div id="form">
	  	  <div class="headertitle"></div>
	  	 <h2><?php echo $this->lang->global->step4;?></h2>
		

		  <form method='post'>
	                  <table class="find_table friends_table" width='550'>
	                  <tr>
						 <?php
						 $i=1; 
						 foreach($this->aroundUsers as $user){ ?>
						 		<td width="20%">
						 			<table width='100%' cellspacing='0' style='line-height: 100%;text-align:center;'>
						 				<tr>
						 					<td align='center'><img src="<?php echo $user['avatar_small'];?>" alt="" class="avatar" width="50" height="50" /></td>
						 				</tr>
						 				<tr>
						 				<td align='center' style='padding: 2px;'><a href="/<?php echo $user['username'];?>" style='color:darkblue;'><?php echo $user['nickname'];?></a></td>
						 				</tr>
						 				<tr>
						 					<td align='center'>
						 					<input type='checkbox' id='au_<?php echo $user['uid'];?>' name='tusers[]' checked='checked' value='<?php echo $user['uid'];?>' />
						 				<label for='au_<?php echo $user['uid'];?>'>
						 				<?php echo $this->lang->javascript->global->follow->title;?>
						 				</label>
						 					</td>
						 				</tr>
						 			</table>

						 		</td>
						 		
						 	<?php if($i%5==0){?>
						 		</tr><tr>
						 	<?php } ?>

						 <?php 
						 	$i++;
						 }?>
						 </tr>
						 <tr>
						 	<td colspan='5'>&nbsp;</td>
						 </tr>
						 <tr>
						 	<td colspan='5' align='center'>
						 	<input style="text-align: center;width:200px;" type="submit" id='step4_btn' class="save btn" value="<?php echo $this->lang->global->begin;?>"/>
						 	</td>
						 </tr>						 
		    	    <tr>
		    	    	<td colspan='5' >&nbsp;</td>
		    	    </tr>						 
					 </table></form>
	   </div>
	</div>
	  
	  </div>
	  <div class="clearfix"></div>
</div> <!--#content-->
</div>
<div id='sssss'></div>
<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>

</body>
</html>
<?php $this->Gz();?>