<div class="footer">
	<hr/>
	<div id="portal">
		<a href="/polo" ><?php echo $this->lang->global->nav->homepage;?></a>
		<a href="/polo/signup" ><?php echo $this->lang->index->signup?></a>
		<a href="/polo/tools" ><?php echo $this->lang->mobile->foot->tools->title;?></a>		
		<a href="/polo/about"><?php echo $this->lang->global->foot->aboutus->aboutus; ?></a>	
	</div> 
	<div id="copyright">
		<span class='time'><?php echo(gmdate("Y-m-d H:i"))?> <br/></span> 
		<?php echo "©".$this->lang->global->nav->title." ".$this->lang->global->foot->icp_no; ?><br/>
		乙测资字32005055<br/>
	</div>
	<div id="pctips">
	
		<?php echo $this->lang->mobile->global->pc_user_tipcs; ?> 
	</div>
</div>