<style type="text/css">
#header{link:#ffffff;}
#template a:visited {color:#B4585D;text-decoration:none;}body{line-height: 18px;margin-right: 0px;font-size: 12px;margin-left: 2px;margin-bottom: 0px;margin-top: 0px;}#template a:hover {color:#0B1DD1;text-decoration:none;}.center {text-align: center;}.center #template {margin: 0 auto;text-align: left;}td{padding: 0px;}table {border-width:0px;padding: 0px;border-spacing: 0px;}#template a:link {color:#000000;text-decoration:none;}#template {width:220px;background-color:#fafafa;}
.sy05{background-color:#f5f5f5;border: 1px solid #e7e7e7;margin-bottom: 2px;}
#error{color: red}
.error{color: red}
#footer {clear:both; background: #395795; padding:13px 0 13px 8px}
#headinfo{}
#polo{
	float:left;
	text-align: center;
}
</style>