<h3>Foxmail</h3></h3>
<p>Select "Address Book" -> "Tools" -> "Export" -> Specify a location, file name and file format (CSV preferred) -> Click OK in the remaining steps to finish exporting</p>
<h3>Microsoft Outlook</h3>
<p>Select "File" -> "Import and Export " -> Select "Export to file" -> Select "Comma Separated Values" -> Highlights "Contacts" -> Specify a location and file name -> Click "Finish" </p>
<h3>
Outlook Express</h3><p>
Select "File" -> Select "Import and Export" -> "Address Book " -> Select "Text File (Comma Separated Values)" -> Click "Export" -> Type a file name in the "Save exported file as" input box -> Click "next" -> Optionally select the fields you wish to export and click "Finish"
</p><h3>
Mozilla Thunderbird</h3><p>
Click "Tools" -> "Address Book" -> "Export Address Book" -> Specify a location, file name and file format (CSV preferred) -> Click OK in the remaining steps to finish exporting.</p>