<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;K.ai(http://k.ai) is a location-based social networking service in China.  It provides useful data on many points of interest and is already available on many mobile phones, including iPhone, Android, Symbian and Windows Mobile.</p>

<h3>K.ai helps you enjoy a new life on the move.</h3>

<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Share your life with your friends from anywhere: restaurants, shopping areas, entertainment venues… just "check-in" on your mobile phone!</p>

<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Find interesting "tips" for nearby places from K.ai’s social network.</p>

<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Win special badges, like mayor and super user, with your check-ins!</p>

<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Use "Shout," like Twitter’s tweet, to share your thoughts on Twitter and other micro-blogs in China (eg. Sina)</p>

<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;For more fun, go treasure hunting in K.ai with your friends and get more prizes!</p>

<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;K.ai transforms you and your urban life!</p>
