<h3>What is K.ai?</h3>
<p>K.ai is a cross between a friend-finder, a social city-guide, and an exploration game with actual consumer rewards.  Check-in to K.ai and your friends can see what you’re up to anywhere in the city.  Share tips with others so that you’re always up-to-date on what’s fun around town.  And, using K.ai is its own reward: the more you participate by checking in and writing tips, the more karma and badges you get.  This translates to getting coupons, free samples, and notices on special offers to your favorite places.  With K.ai on your phone, you can keep up with the places your friends go and challenge yourself to explore your city space in new ways.</p>
<h3>How do I get it on my phone?</h3>
<p>We have apps available for the <a href="/tools/iphonedownload">iPhone</a>, <a href="/tools/androiddownload">Android</a>，<a href="/tools/wmdownload">Windows Mobile</a> and <a href="/tools/s60download">Symbian S60</a>. If you don't have one of these phones, you can always use our mobile website.</p>
<h3>Where is K.ai available?</h3>
<p>You can use K.ai anywhere in the world. Check-in at the Statue of Liberty in NYC, the Golden Gate Bridge in SF, the Petronas Towers in Kuala Lumpur, or at the Arc de Triomphe in Paris! </p>
<h3>What is a check-in?</h3>
<p>When you tell K.ai where you are, that's called "checking-in." You can check-in from parks, bars, museums, restaurants... really anywhere. When you check-in, we'll let your friends know where they can find you and award you Karma and badges based on your adventurousness. Please only check-in once to where you are at a given  time. K.ai is meant to be a social utility that helps you connect with friends and experience your city in a new way, with a bit of fun thrown in. Please play fair!
</p>

<h3>What is "The Mayor" all about?</h3>
<p>If you've been to a place more than anyone else we'll crown you the "The Mayor" of that place. Some bars and cafes are now offering "Mayor Specials" - a free coffee, appetizer, or even a special discount to the mayors of their venues. Watch out, though - if someone else comes along who has checked in more days than you, they will steal the "Mayor" title back from you.</p>
<p>(Hint: if you want to become mayor, you need to have uploaded a profile photo)</p>

<h3>What are badges?</h3>
<p>Badges are little rewards you earn for particularly special check-ins, such as check-ins that have you staying out 4 nights in a row, or that log you frequenting many karaoke bars. We're constantly adding new badges and would love to hear your suggestions.</p>
<p>A lot of our badges are tied to venue "tags". People use tags to describe places on K.ai (e.g. jukebox, pool table, fireplace, pizza, etc) Without giving away too much, here are a few suggested tags you can add to your favorite places to help unlock badges : airport, college, douche bag, food truck, frat, gallery, gym, karaoke, movie theater, photo booth, pizza, playground, socialite, sorority, tourist, etc.</p>
<h3>How do I earn Karma?</h3>
<p>Most K.ai check-ins will earn you Karma. You can earn Karma for your first check-in at a certain place or by adding new tips on places. The idea is that the more you experience, the more places you visit, etc. the higher your Karma score for that week.</p>


 

