			<img src="images/en.lbslogo.png" class="pngfix"/><br/>
	    	K.ai depends on <a href="http://www.lbs.org.cn" class='blank'>LBS(lbs.org.cn)</a> to provide its location services.<br/>
	    	After the LBS plugin is installed, K.ai will automatically retrieve your current location when you access Internet via WIFI. <br/>
	    	Currently, LBS plugin can only work with IE or browsers built with IE kernel, such as Maxthon, GreenBrowser, TheWorld, Tencent TT, Mini IE, Avant Browser etc.
	    	<br/>
	    	<a href="http://lbs.org.cn/api/PepLocation(10051401).exe">Download and install LBS plugin</a>