<h3>1. Put "Share to Kai" into mouse right click menu</h3>
	    	    <div class='shareContent'>Click here to run script <a href='/html/share.reg'>Share to Kai</a>, or download the <a href='/html/share.zip'>zip</a> format file.</div>
	    	    <h3>2. Add "Share to Kai" to your browser</h3>
	    	    <div class='shareContent'>
	    	    <a href="javascript:var d=document,w=window,f='{BETTER_BASE_URL}/share',l=d.location,e=encodeURIComponent,p='?status_text='+e(w.getSelection?w.getSelection().toString():d.getSelection?d.getSelection():d.selection.createRange().text);a=function(){if(!w.open(f+p,'sharer','toolbar=0,status=0,resizable=0,width=550,height=250'))l.href=f+p};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else{a()}void(0)"><img src='images/kailogo.png' alt='Share to Kai' /></a>
	    	  <br />  Internet Explorer: Right click this button, then choose "Add to favorites"<br />
	    	    Firefox: Right click this button, then choose "Add this link to favoritse"<br />
	    	    Chrome & Firefox: Left click and drag this button to the favorites bar
	    	    </div>
	    	    <h3>3. Add "Share to Kai" on your personal blog</h3>
	    	    <div class='shareContent'>
	    	   	 You are free to share your post with friends on K.ai by pasting the following code in your blog (template).
	    	    <div class='shareIcons'>
	    	    <div class='label'>Icon</div>
		    	    <div class='shareIcon'>
		    	    	<a href="javascript:var d=document,w=window,f='{BETTER_BASE_URL}/share',l=d.location,e=encodeURIComponent,p='?status_text='+e(w.getSelection?w.getSelection().toString():d.getSelection?d.getSelection():d.selection.createRange().text);a=function(){if(!w.open(f+p,'sharer','toolbar=0,status=0,resizable=0,width=550,height=250'))l.href=f+p};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else{a()}void(0)"><img src='images/kailogo.png' alt='Share to Kai' class="pngfix" /></a>
		    	    </div>
		    	    <div class='shareLinks'>
		    	    	<input type='text' class='iShareLink' value="&lt;a href=&quot;javascript:var d=document,w=window,f='{BETTER_BASE_URL}/share',l=d.location,e=encodeURIComponent,p='?status_text='+e(w.getSelection?w.getSelection().toString():d.getSelection?d.getSelection():d.selection.createRange().text);a=function(){if(!w.open(f+p,'sharer','toolbar=0,status=0,resizable=0,width=550,height=250'))l.href=f+p};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else{a()}void(0)&quot;&gt;&lt;img src='{BETTER_BASE_URL}/images/kailogo.png' alt='Share to Kai' /&gt;&lt;/a&gt;" class="pngfix" />
		    	    </div>
	    	    
	    	    <div class='label'>Text Link:</div>
		    	    <div class='shareIcon'>
		    	    	<a href="javascript:var d=document,w=window,f='{BETTER_BASE_URL}/share',l=d.location,e=encodeURIComponent,p='?status_text='+e(w.getSelection?w.getSelection().toString():d.getSelection?d.getSelection():d.selection.createRange().text);a=function(){if(!w.open(f+p,'sharer','toolbar=0,status=0,resizable=0,width=550,height=250'))l.href=f+p};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else{a()}void(0)">Share to Kai</a>
		    	    </div>
		    	    <div class='shareLinks'>
		    	    	<input type='text' class='iShareLink' value="&lt;a href=&quot;javascript:var d=document,w=window,f='{BETTER_BASE_URL}/share',l=d.location,e=encodeURIComponent,p='?status_text='+e(w.getSelection?w.getSelection().toString():d.getSelection?d.getSelection():d.selection.createRange().text);a=function(){if(!w.open(f+p,'sharer','toolbar=0,status=0,resizable=0,width=550,height=250'))l.href=f+p};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else{a()}void(0)&quot;&gt;Share to Kai&lt;/a&gt;" />
		    	    </div>
	    	    
	    	    <div class='label'>Icon with text:</div>
		    	    <div class='shareIcon'>
		    	    	<a href="javascript:var d=document,w=window,f='{BETTER_BASE_URL}/share',l=d.location,e=encodeURIComponent,p='?status_text='+e(w.getSelection?w.getSelection().toString():d.getSelection?d.getSelection():d.selection.createRange().text);a=function(){if(!w.open(f+p,'sharer','toolbar=0,status=0,resizable=0,width=550,height=250'))l.href=f+p};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else{a()}void(0)"><img src='images/kailogo.png' alt='Share to Kai' class="pngfix" />Share to Kai</a>
		    	    </div>
		    	    <div class='shareLinks'>
		    	    	<input type='text' class='iShareLink' value="&lt;a href=&quot;javascript:var d=document,w=window,f='{BETTER_BASE_URL}/share',l=d.location,e=encodeURIComponent,p='?status_text='+e(w.getSelection?w.getSelection().toString():d.getSelection?d.getSelection():d.selection.createRange().text);a=function(){if(!w.open(f+p,'sharer','toolbar=0,status=0,resizable=0,width=550,height=250'))l.href=f+p};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else{a()}void(0)&quot;&gt;&lt;img src='{BETTER_BASE_URL}/images/kailogo.png' alt='Share to Kai' /&gt;Share to Kai&lt;/a&gt;" class="pngfix" />
		    	    </div>
	    	     <div class='clearfix'></div>
	    	     
	    	    <div class='label'>Logo:</div>

	    	    	<div class='shareIcon'>
						<a href="javascript:var d=document,w=window,f='{BETTER_BASE_URL}/share',l=d.location,e=encodeURIComponent,p='?status_text='+e(w.getSelection?w.getSelection().toString():d.getSelection?d.getSelection():d.selection.createRange().text);a=function(){if(!w.open(f+p,'sharer','toolbar=0,status=0,resizable=0,width=550,height=250'))l.href=f+p};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else{a()}void(0)"><img src='images/en.share-button1.png' alt='Share to Kai' class="pngfix" /></a>
					</div>
		    	    <div class='shareLinks'>
		    	    <input type='text' class='iShareLink' value="&lt;a href=&quot;javascript:var d=document,w=window,f='{BETTER_BASE_URL}/share',l=d.location,e=encodeURIComponent,p='?status_text='+e(w.getSelection?w.getSelection().toString():d.getSelection?d.getSelection():d.selection.createRange().text);a=function(){if(!w.open(f+p,'sharer','toolbar=0,status=0,resizable=0,width=550,height=250'))l.href=f+p};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else{a()}void(0)&quot;&gt;&lt;img src='{BETTER_BASE_URL}/images/en.share-button1.png' alt='Share to Kai' /&gt;&lt;/a&gt;" />
		    	    </div>	    	 	 <br />
		    	    	<div class='shareIcon'>
						<a href='javascript:window.open("{BETTER_BASE_URL}/{USERNAME}");void(0);''><img src='{BETTER_BASE_URL}/images/en.share-button2.png' alt='Follow me on Kai' /></a>
					</div>
		    	    <div class='shareLinks'>
		    	    	<input type='text' class='iShareLink' value="&lt;a href='javascript:window.open(&quot;{BETTER_BASE_URL}/{USERNAME}&quot;);void(0);''&gt;&lt;img src='{BETTER_BASE_URL}/images/en.share-button2.png' alt='Follow me on Kai' /&gt;&lt;/a&gt;" />
		    	    </div>	        	    	    	    
	    	    </div>
	    	    
	    	    <div class='clearfix'></div>
			</div>