<h2 class='signup_tips_title'><span class='small_signup_tips_title'>&gt;&gt;</span>Tips</h2>
 <hr class="onepxline" color="#dce2ea">
<div class='signup_tips_content'>
<ul>
	<li>Thanks for choosing Kai.We have created one account with the same user name locally for your convenience. 
</li>	
	<li>Real photo will allow for easy recognition by your friends</li>
	<li>Providing rich information will make you more attractive</li>
	<li>Of course, you can choose to do these later via "Settings"</li>
</ul>
</div>