<p style='margin-top:10px;!margin-top:5px;'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;K.ai is a new generation  LBS (location-based service) social network. K.ai helps you share your location with friends, exchange ideas, and using a new way to explore the city in a new way.</p>

<p style='margin-top:10px;!margin-top:5px;'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;By checking-in to K.ai, you can share your current position with friends, and let them know where to find you and/or give you a variety of tips and suggestions. You can also use the tips to share your feelings here and now. K.ai's Badges also bring you surprises as you explore the city. Go treasure hunting on K.ai and find partners to watch out for you, ( as well as the opportunity to convert it into a real baby). If you become the mayor of a place, the shopkeeper may even give you a mystery gift.</p>

<p style='margin-top:10px;!margin-top:5px;'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;K.ai is developed and operated by Suzhou Bedo Technologies Co.Ltd. We are devoting our accumulated years of professional experience in the LBS and SNS fields to the development of K.ai. All efforts were made to bring you the best experience as you explore the city. We cannot continue to develop and improve without your support and suggestions, so please feel free to share your opinion with us. Our email is: contact@k.ai</p>


<p style='margin-top:10px;!margin-top:5px;'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;苏州贝多科技有限公司Suzhou Bedo Technologies Co. Ltd. 成立于2005年6月，公司股东包括世界500强美国高通(Qualcomm)及法国电信(Orange)等战略投资者，以及中新创投(CSVC)、愈奇投资(Mustang Ventures)等具有政府或国际背景的风险投资基金。</p>
<p style='margin-top:10px;!margin-top:5px;'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;苏州贝多科技有限公司是国内领先的手机应用软件开发商之一，致力开发基于位置的无线互联网服务。公司主要产品包括新一代位置网络(开开www.k.ai)，基于位置的手机社交网络服务（贝多www.bedo.cn），以及网络定位服务平台（驴博士www.lbs.org.cn）。公司及旗下产品曾先后获得硅谷红鲱鱼杂志2008年私有未上市最有潜力的科技全球百强公司（2008 Red Herring Global 100）、2008中国手机客户端软件十强、中国移动互联网应用十佳、索尼爱立信金枝奖最佳Mobile 2.0应用等多项业内荣誉。</p>
<p style='margin-top:10px;!margin-top:5px;'>我们的详细联络方式是：</p>
<p>苏州贝多科技有限公司</p>
<p>江苏苏州工业园区金鸡湖大道1355号</p>
<p>国际科技园151A，215021</p>
