<h2 class='signup_tips_title'><span class='small_signup_tips_title'>&gt;&gt;</span>Tips</h2>
 <hr class="onepxline" color="#dce2ea">
<div class='signup_tips_content'>
<ul>
	<li>Congrats, you have signed up successfully!</li>
	<li>Your account on K.ai is {EMAIL}</li>
	<li>Feel free to make any of the following adjustments via “Settings”:</li>	
	<li>Sign in with your mobile number once you register it online</li>
	<li>Upload a real photo to allow for easy recognition by your friends</li>
	<li>Provide more detailed information that will help you stand out</li>	
</ul>
</div>