<h2 class='signup_tips_title'><span class='small_signup_tips_title'>&gt;&gt;</span>Tips of Synchronization</h2>
 <hr class="onepxline" color="#dce2ea">
<div class='signup_tips_content'>
<ul>
	<li>By linking with other third-party applications, your statuses can be followed by more friends</li>
	<li>Your own account on 3rd app. is necessary for binding </li>
	<li>If you choose to ignore it for now, you can update the binding anytime in the future via "Settings"</li>
</ul>
</div>