<h3>K.ai License Agreement</h3> 
<p>
This K.ai License Agreement ("this Agreement") is a legal agreement between you, the user of K.ai, and Suzhou Bedo Tech. Co.,Ltd with respect to the use of the K.ai. </p><br/>
<p>
Please carefully read and understand all the rights and restrictions provided in this Agreement first. Only after you unconditionally accept all the provisions herein do you have the right to use K.ai. Upon installing, duplicating, or using K.ai in other ways, you have accepted the restraints of this Agreement. 
</p>
<h3>1. Provisions Concerning Protection and Usage License of K.ai Products</h3> 
<p>
(1) K.ai includes, but is not limited to, the software which is distributed by Bedo and used for network communication, the relevant written or electronic documents, trademark, logo, application procedure contact surface, and any related amended procedure, renewal and updating thereof in the future. 
</p>
<p>
(2) K.ai is subject to the protection of the Copyright Law of the People's Republic of China, Universal Copyright Convention and other intellectual property laws and conventions. All the copyrights, patents, trademarks, business secrets and other property rights or rights relating to K.ai shall be owned by Bedo. 
</p>
<p>
(3) This Agreement grants you a limited, individual, non-commercial, non-exclusive right, by which you can download, install and use K.ai with your computer. 
</p>
<p>
(4) You may not delete or modify any information concerning the copyright of the original K.ai and/or any copy thereof or conduct any reverse engineering, disassembling or de-compilation on K.ai. 
</p>
<h3>2. Restrictions on Usage of K.ai </h3>
<p>
(1) You may not in any way use K.ai in any activity which is illegal or in violation of any term or purpose of this Agreement. 
</p>
<p>
(2) You may not use K.ai in any activity such as unauthorized sale and resale or use it for any other commercial purpose. 
</p>
<p>
(3) You may not utilize K.ai to conduct any activity disturbing other network services or normal usage of the software by other users. 
</p><p>
(4) You agree to abide by the relevant laws and regulations of the People’s Republic of China during your usage of K.ai, and are liable for any behavior and consequence thereof by using the services in any form. Bedo shall not be liable for the activity, behavior or transaction concerning the use of K.ai products by the users. 
</p><p>
(5) You shall earnestly observe the provisions of this Agreement and relevant laws and regulations. In the case that Bedo firmly believes that the user has violated the provision of this Agreement or any law, Bedo may end the usage of the user's account and password at any time. 
</p><p>
(6) If you do not use a registered K.ai account for a long time, Bedo maintains the right to reverse it, clear the user's information and provide this account to other users for registration and usage. To avoid your registered account being reversed, you must use it at least once in three months. 
</p>
<h3>3. Risk Bearing</h3> 
<p>
(1) The risks of using K.ai shall be borne by the users themselves. Within the scope permitted by law, Bedo shall not be liable for indemnification of any special, accidental, direct or indirect losses suffered by the users by using or being unable to use the K.ai, even though Bedo has been informed the possibility of such damages in advance. 
</p><p>
(2) When using K.ai, if there is any risk from others, including threats, disgustful or illegal contents or behavior, or anonymous or false information infringing any other person’s right, you shall bear such risk. 
</p><p>
(3) Bedo and its cooperation companies do not make any guarantee to the services of K.ai and, therefore, shall not be liable for any of the direct, indirect, accidental, or special damages caused by the customer's false or illegal use of the services.  
</p>
<h3>4. Utilization License and Protection</h3> 
<p>
(1) License of Utilizing Your Computer 
</p><p>
In order to acquire the services provided by K.ai, you license K.ai to utilize your computer's processor, mobile terminal and bandwidth for the limited purpose of network communication between you and other users of K.ai.</p> 

<p>(2) License of Utilizing Your Provided Personal Information</p> 

<p>Once you fill in your personal information in K.ai, it indicates that you have agreed that all such information can be made public to all K.ai users and that the K.ai website is licensed to cite and/or wholly publish such information. If you do not want to disclose your personal information, you don’t have to fill out your personal information in K.ai, which will not affect your normal installation, copying and usage of K.ai.</p> 

<p>(3) Protection of Your Computer Resources</p> 

<p>You acknowledge that K.ai will put forth reasonable effort to protect your computer resources and the privacy and integrity of your communications, provided that you understand and agree that K.ai can not provide any guarantee for such protection.</p> 

<p>(4) Updating License</p> 

<p>Upon accepting K.ai updates, you are agreeing with this Agreement.</p> 

<h3>5. The Usage and Safekeeping of the Account and Password </h3>
<p>
(1) You shall be responsible for appropriately keeping the account and password that you acquired when you registered and use K.ai, and be liable for all the actions or activities which are started after the system is logged in through such account and password. 
</p><p>
(2) You shall not leak, lend or transfer the account and password to any other person for use. Otherwise, you shall be liable for any consequence incurred. 
</p><p>
(3) If you want to use the account and password which you acquired when you registered K.ai to log in to the K.ai website (http://www.k.ai), please first read the K.ai Website Services Clauses carefully and understand all the rights and restrictions provided in the provisions thereof. Only when you unconditionally accept the K.ai Website Services Clauses do you have the right to log in and use the K.ai website. Once logged in to the K.ai website, it means you have agreed to be bound by the K.ai web Services Clauses. 
</p>
<h3>6. The Amendment and Intermission of the Services</h3> 
<p>
(1) In order to keep the initiative to develop and adjust the company’s operation, Bedo has the right to amend or suspend the services at any time without the responsibility of informing the users thereabout. When exercising its right of the amendment and intermission of the services, Bedo shall not bear any liability to the users or any other third party. 
</p><p>
(2) When using K.ai, there may be risks, such as the the service being intermitted or the inability of satisfying users’ requirement due to force majeure, computer virus or hacker attack, system instability or any other problems with regard to the technology, network, communication circuits, etc. You shall bear the aforementioned risks and may not require Bedo to be liable for any indemnification or compensation there from. </p>

<h3>7. Compensation for Breach of Contract</h3> 
<p>
You agree to guarantee and maintain the interests of Bedo and other users. In the event that you violate any provision of the relevant laws, regulations or this Agreement and bring any losses to Bedo or any other third party, you agree to be liable for the damages thereof. 
 </p>
<h3>8. Governing Law</h3> 
<p>
(1) The conclusion, performance, explanation and resolution of disputes of this Agreement shall be governed by laws of the People's Republic of China. </p> 
<p>
(2) In the event of any dispute between you and Bedo, such dispute shall be resolved based on friendly consultation first. If the Parties fail to reach an agreement on the resolution, you agree the dispute shall be submitted to Suzhou Arbitration Commission for arbitration, in accordance with its then-effective arbitration rules. The arbitration shall be conducted in Suzhou, and the language used during arbitration shall be Chinese. The arbitration ruling shall be final and binding on both Parties. </p>
