<h2 class='signup_tips_title'><span class='small_signup_tips_title'>&gt;&gt;</span>Tips of Get Friends</h2>
 <hr class="onepxline" color="#dce2ea">
<div class='signup_tips_content'>
<ul>
	<li>Following these active guys nearby will be good idea for beginner</li>
	<li>Maybe you will even meet them on the street today</li>
	<li>They will guide you to find more fun around you</li>
	<li>Of course, you can invite more friends via "Friend" later</li>
	<li>Everything is ready, let's get started!</li>
	<li>Wish you discover a more wonderful world via K.ai</li>
</ul>
</div>