<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
<body id="tools">
<?php include_once(dirname(__FILE__).'/../include/newheader.phtml');?>	

<div id="content">
  <div class="mid" style="height:46px;">
	<div id="setting_header_title"><?php echo $this->lang->tools->client->title->normal;?></div>
	<div id="setting_header_img"><h2><?php echo $this->lang->global->setting_header_text;?></h2></div>
  </div>
  <div id="setting_page">
    <div class="mid">
    <div id="setting_content">
	    <div class="setting_main"> 
	    <h2><span class='left'><?php echo $this->lang->tools->client->title->bb;?></span><span class='right' style='font-size: 12px; font-weight: normal;'><a href='/tools'><?php echo $this->lang->tools->download_by_phone;?></a></span></h2>
			<table width='100%'>
				<tbody>
					<tr>
						<td id="platform_img">
							<img src="images/down_bb.png" alt=""/><br>
							<?php echo '最新版本'.': '.$this->postver;?><br />
							<?php echo $this->lang->tools->client->version->publishdate.': '.$this->postdate;?>
						</td>
						<td id="platform_note">
						<span>1. <?php echo $this->lang->tools->client->download_to_local;?></span><br><br>
							<a href='<?php echo $this->v50download;?>'><?php echo $this->lang->tools->bb->v50->title;?></a><br>						
							<?php echo str_replace('{V50URL}',$this->v50download,$this->lang->tools->bb->v50->productlist);?>
	    					<br><br>
	    					
	    					
	    					<a href='<?php echo $this->v46download;?>'><?php echo $this->lang->tools->bb->v46->title;?></a><br>
	    					<?php echo str_replace('{V46URL}',$this->v46download,$this->lang->tools->bb->v46->productlist);?>
	    					<br><br>
	    					
	    					<a href='<?php echo $this->v45download;?>'><?php echo $this->lang->tools->bb->v45->title;?></a><br>
	    					<?php echo str_replace('{V45URL}',$this->v45download,$this->lang->tools->bb->v45->productlist);?>
	    					<br><br>	    					
	    					
						<span> 2. <?php echo $this->lang->tools->client->downloadbb->tip2;?></span><br>
						<img src='images/Blackberry-chart.bmp' width="230" height="230"/>
	    				<br>
						<span> 3. <?php echo $this->lang->tools->client->downloadbb->tip3;?></span><br><br>
	    		
						</td>
					</tr>
					
				</tbody>
			</table>
		</div>
	<div class="clearfix"></div>
	</div><!--#seeting_content-->
	<?php 
		$platform = 'blackberry';
		include_once(dirname(__FILE__).'/down_menu.phtml');
	?>
	<div class="clearfix"></div>
	</div>
  </div><!--#setting_page-->
</div> <!--#content-->
<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>
</body>
</html>
<?php $this->Gz();?>