<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
<body id="tools">
<?php include_once(dirname(__FILE__).'/../include/newheader.phtml');?>	

<div id="content">
  <div class="mid" style="height:46px;">
	<div id="setting_header_title"><?php echo $this->lang->tools->client->title->normal;?></div>
	<div id="setting_header_img"><h2><?php echo $this->lang->global->setting_header_text;?></h2></div>
  </div>
  <div id="setting_page">
    <div class="mid">
    <div id="setting_content">
	    <div class="setting_main"> 
	    <h2><span class='left'><?php echo $this->lang->tools->client->title->iphone;?></span><span class='right' style='font-size: 12px; font-weight: normal;'><a href='/tools'><?php echo $this->lang->tools->download_by_phone;?></a></span></h2>
			<table width='100%'>
				<tbody>
					<tr>
						<td id="platform_img">
							<img src="images/down_iphone.png" alt=""/><br>
							<?php echo '最新版本'.': 1.4.0';?><br />
							<?php echo $this->lang->tools->client->version->publishdate.': 2010-08-20';?>
						</td>
						<td id="platform_note">
						<span>1. <?php echo $this->lang->tools->client->cell_to_app_store;?></span><br>
	    		<span>2. <?php echo $this->lang->tools->client->to_app_store;?><br />
	    		<a href="http://itunes.apple.com/cn/app/id371900584?mt=8
">http://itunes.apple.com/cn/app/id371900584?mt=8</a></span>						
						</td>
					</tr>
					
				</tbody>
			</table>
		</div>
	<div class="clearfix"></div>
	</div><!--#seeting_content-->
	<?php 
		$platform = 'iphone';
		include_once(dirname(__FILE__).'/down_menu.phtml');
	?>
	<div class="clearfix"></div>
	</div>
  </div><!--#setting_page-->
</div> <!--#content-->
<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>
</body>
</html>
<?php $this->Gz();?>