<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
<body id="tools">
<?php include_once(dirname(__FILE__).'/../include/newheader.phtml');?>	

<div id="content">
  <div class="mid" style="height:46px;">
	<div id="setting_header_title"><?php echo $this->lang->tools->client->title->normal;?></div>
	<div id="setting_header_img"><h2><?php echo $this->lang->global->setting_header_text;?></h2></div>
  </div>
  <div id="setting_page">
    <div class="mid">
    <div id="setting_content">
	    <div class="setting_main"> 
	    <h2><span class='left'><?php echo $this->lang->tools->client->title->wm;?></span><span class='right' style='font-size: 12px; font-weight: normal;'><a href='/tools'><?php echo $this->lang->tools->download_by_phone;?></a></span></h2>
			<table width='100%'>
				<tbody>
					<tr>
						<td id="platform_img">
							<img src="images/down_ppc.png?ver=<?php echo BETTER_VER_CODE;?>" alt=""/><br>
							<?php echo '最新版本'.': '.$this->postver;?><br />
							<?php echo $this->lang->tools->client->version->publishdate.': '.$this->postdate;?>
						</td>
						<td id="platform_note">
							<span>1. <?php 
							$download = $this->lang->tools->client->wm->download_to_local;
	    					$download = str_replace('{URL}',$this->wmdownload,$download);	    					
	    					echo $download;
							?></span><br><br>
	    					<span>2. <?php echo $this->lang->tools->client->download_to_cell;?></span><br>
	    					<br>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	<div class="clearfix"></div>
	</div><!--#seeting_content-->
	<?php 
		$platform = 'windows';
		include_once(dirname(__FILE__).'/down_menu.phtml');
	?>
	<div class="clearfix"></div>
	</div>
  </div><!--#setting_page-->
</div> <!--#content-->
<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>
</body>
</html>
<?php $this->Gz();?>