<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
<body id="invitation">
<?php include_once(dirname(__FILE__).'/../include/newheader.phtml');?>	

<div id="content">
  <div class="mid border" style="background-color: #fff;">
	
	<div class='small_mid' style='min-height:440px;'>
		<div class='title_large'>
			<div class="left"><img src="images/add.png" class="pngfix" /></div>
			<div class="left text"><?php echo $this->lang->global->people->find_people;?></div>
		</div>

	<div class="tabs">
	    <ul class="tabNavigation">
	        
	        <li><a href="/invitation/find"  ><?php echo $this->lang->global->people->kai;?></a></li>	        
	        <li><a href="/invitation/mailaddressbook"><?php echo $this->lang->global->people->emailfriend;?></a></li>
	        <li><a href="/invitation"><?php echo $this->lang->global->invitation->im;?></a></li>
	        <li><a href="/invitation/sendmail"><?php echo $this->lang->global->invitation->sendmail;?></a></li>
	        <li><a href="/invitation/clientaddressbook" class="selected first"><?php echo $this->lang->global->invitation->clientaddressbook;?></a></li>	           
	     </ul>	
	    <div id="tab_content" class='m300' style="!padding:0 5px 0 20px">
	    	 
	    	    <div class='pfElements'>
	            <form method='post' action='/invitation/uploadclientbook' id=''>
				<div id='avatarFunc'>
					<div id='avatarForm'>

					<input type='text' name='avatar_path' id='avatar_path' readonly='readonly' value='' />
					<input type='button' name='btnFile' id='btnFile' value='<?php echo $this->lang->setting->avatar->file_tips;?>'  class='btn' />
					</div>
	    			 <div class="field">
				  	  	<input type='button' id='btnUploadAvatar' class='btn2' value='<?php echo $this->lang->signup->button_tips;?>' />
				  	  	
				  	  	<input type='hidden' name='avatar' id='avatar' value='<?php echo $this->user['avatar'];?>' />
				  	  	<input type='hidden' name='todo' id='todo' value='avatar' />
				  	 </div>					
				</div>
				<div class='clearfix'>&nbsp;</div>
				</form>
				</div>

	    	
	    	 <div id="clientbook_howtodo"><?php echo $this->LangTpl($this->lang->global->invitation->clientbook->howtodo->content);?></div>
	                  <div id='email_result' class='hide result_box'>
	                 <h2><?php echo $this->lang->global->people->emailfriend_in_id;?></h2>
	                 
	                  <table class="find_table friends_table">
	                  	<tbody id='tbl_findEmail'>

					    </tbody>
					 </table>
					 
					 <h2><?php echo $this->lang->global->people->emailfriend_notin_id;?></h2>
					 <table class="find_table">
	                  	<tbody id='tbl_revertEmail'>
							
					    </tbody>
					 </table>
					 
	                </div>
	    </div>
	   
	</div><!--.tabs-->
	</div><!-- .small_mid  -->
  </div><!--#mid-->
</div> <!--#content-->
<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>
</body>
</html>
<?php $this->Gz();?>