<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
<body id="invitation">
<?php include_once(dirname(__FILE__).'/../include/newheader.phtml');?>	

<div id="setting_page">
 <div class="mid title">
	  <div id="setting_header_title"><span class='text'><?php echo $this->lang->global->nav->find_people;?></span></div>
	  <div id="setting_header_img"><h2><?php echo $this->lang->global->setting_header_text;?></h2></div>
 </div>
 
  <div class="mid">    
		  <div id="setting_content">
		  	<div id='find_better' class="setting_main">  
		  	 <div class="headertitle">
		    	<?php echo $this->lang->global->people->invite_people_tip;?>
		    </div>
		    <div id="tab_content" class="setting_block">	   
		   
		    <h2><?php echo $this->lang->global->invitation->im;?></h2>
		   
		    <form>
		    	   <?php echo $this->lang->global->invitation->im_content;?><br/>
		    	   <textarea  style="height: 50px; width: 450px;" rows="3" cols="70"  id='friend_email' class='button'><?php echo $this->imsignupurl?></textarea>
		    	   <INPUT id="" class='btn' onclick='copyToClipboard()' type=button value=<?php echo $this->lang->global->invitation->copy_button;?> name="" style="height:58px;width:51px;"> 
		    </form>  
		    <br/> 
		    </div>
		   
		    <div id="tab_content" class="setting_block">
		    <h2><?php echo $this->lang->global->invitation->sendmail;?></h2>
		
		    	   <?php echo $this->lang->global->invitation->sendmail_content;?><br/>
		    	    <div style="margin: 0 0 20px;">
		                <form action="/invitation/dosendmail" method="post" id="invitation_sendmail">	                
		               <?php  echo $this->lang->global->invitation->friend_mail;?><br>
		               <textarea  style="width: 450px; height: 50px;" rows="3" cols="60" id='invitation_email' class='button' /></textarea>
		                <input type="button" id='btnSendMail' class="btn" value="<?php echo $this->lang->resetpwd->button_tips;?>" style="height:58px;width:51px;" />
		               <br/>		               
		                <span class='err hide' id='errinfo'></span>
		                (<?php  echo $this->lang->global->invitation->sendmail_remark;?>)
		              
		              
		                </form>
		    	</div>
		     </div>
		     <div id="tab_content" class="setting_block">
		    	<h2><?php echo $this->lang->global->people->invite_by_group;?></h2>
		    
		    	<span><?php echo $this->lang->global->people->invite_by_email_book;?></span>
		    	
		    	<div class='pfElements' style="padding-bottom: 20px;">
		            <form method='post' action='/invitation/uploadclientbook' id=''>
					<div id='avatarFunc' style="margin: 0;">
						<div id='avatarForm' style="float:left;">
	
						<input type='text' size="45" name='avatar_path' id='avatar_path' readonly='readonly' value='' />
						<input type='button' name='btnFile' id='btnFile' value='<?php echo $this->lang->setting->avatar->file_tips;?>'  class='btn' style="background: #ddd;color:#000"/>
						</div>
		    			 <div class="field" style="float:left;padding:0 0 0 3px;">
					  	  	<input type='button' id='btnUploadAvatar' class='btn' value='<?php echo $this->lang->signup->button_tips;?>' />
					  	  	
					  	  	<input type='hidden' name='avatar' id='avatar' value='<?php echo $this->user['avatar'];?>' />
					  	  	<input type='hidden' name='todo' id='todo' value='avatar' />
					  	 </div>					
					</div>
					<div class='clearfix'>&nbsp;</div>
					</form>
				</div>
				<form>
				 <div id='email_result' class='hide result_box'>
		                 <h2><?php echo $this->lang->global->people->emailfriend_in_id;?></h2>
		                 
		                  <table class="find_table friends_table">
		                  	<tbody id='tbl_findEmail'>
	
						    </tbody>
						 </table>
						 
						 <h2><?php echo $this->lang->global->people->emailfriend_notin_id;?></h2>
						 <table class="find_table">
		                  	<tbody id='tbl_revertEmail'>
								
						    </tbody>
						 </table>
						 
		          </div>
		          </form>
		          
		         <a href="javascript: void(0);" id="addressbook_help"><?php echo $this->lang->global->people->how_to_addressbook; ?></a>
				 <div id="clientbook_howtodo" class="hide">
				   
				 	<?php 
				 
				 	echo $this->LangTpl($this->lang->global->invitation->clientbook->howtodo->content);?>
				 </div>
		   </div>
		  
		   </div>
		  
		  </div>
		  <div id="setting_menu">
		  	 <ul id="right_menu"> 
		        <li> <a href="/invitation/find" class="off"><?php echo $this->lang->global->people->find;?></a> </li> 
		         <li> <a href="/invitation" class="on"><?php echo $this->lang->global->people->invite;?></a> </li> 
		  	 </ul>
		  	 
		 </div>
		 <div class='clearfix'>&nbsp;</div>
     </div>  
</div> <!--#content-->
<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>
</body>
</html>
<?php $this->Gz();?>