<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
<body id="invitation">
<?php include_once(dirname(__FILE__).'/../include/newheader.phtml');?>	

<div id="content">
  <div class="mid border" style="background-color: #fff;">
	
	<div class='small_mid' style='min-height:440px;'>
		<div class='title_large'>
			<div class="left"><img src="images/add.png" class="pngfix" /></div>
			<div class="left text"><?php echo $this->lang->global->people->find_people;?></div>
		</div>

	<div class="tabs">
	    <ul class="tabNavigation">
	        
	         <li><a href="/invitation/find"  ><?php echo $this->lang->global->people->kai;?></a></li>	        
	        <li><a href="/invitation/mailaddressbook"><?php echo $this->lang->global->people->emailfriend;?></a></li>
	        <li><a href="/invitation"><?php echo $this->lang->global->invitation->im;?></a></li>
	        <li><a href="/invitation/sendmail" class="selected first"><?php echo $this->lang->global->invitation->sendmail;?></a></li>
	        <li><a href="/invitation/clientaddressbook"><?php echo $this->lang->global->invitation->clientaddressbook;?></a></li>	   	        
	     </ul>	   <div id='find_better' class="no_border">
	    <div id="tab_content" class='m300' style="padding:10px 10px 0 20px;!padding:0 5px 0 20px;">
	    	   <?php echo $this->lang->global->invitation->sendmail_content;?><br/>
	    	    <div class='pfElements'>
	                <form action="/invitation/dosendmail" method="post" id="invitation_sendmail">	                
	               <?php  echo $this->lang->global->invitation->friend_mail;?><textarea  rows="3" cols="60 value=""  id='friend_email' class='button' /></textarea><br/>
	               
	                <span class='err hide' id='errinfo'></span>
	                (<?php  echo $this->lang->global->invitation->sendmail_remark;?>)
	                <br>
	               <input type="button" id='btnSendMail' class="btn2" value="<?php echo $this->lang->resetpwd->button_tips;?>" />
	                </form>
	    	</div>
	   </div>
	</div><!--.tabs-->
	</div><!-- .small_mid  -->
  </div><!--#mid-->
</div> <!--#content-->
<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>
</body>
</html>
<?php $this->Gz();?>