<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
<body id="index">

<?php include_once(dirname(__FILE__).'/../include/newheader.phtml');?>	

<div id="content">
  <div class="mid">

	  <div id="half_left">
	    <div class="big_box">
	     <!-- <div class="fill"></div>  --> 
	      <div class="updatestatus">
	      	<a href='/tools' title='<?php echo $this->lang->global->down_tips;?>'><img src="images/trans.gif" alt="" class='left pngfix' <?php if(Better_Registry::get('language')=='en'){?> style="margin: 10px 8px 0 10px;" <?php }else{?> style="margin: 10px 55px 0 24px;" <?php }?>  id="downtocell"/></a>
	      	<a id="checkina" href="#checkindlg" disable='disable'><img src="images/check-in.png" alt="" style="margin-right: 2px;" /></a>
	      	<a id="shouta" href="#status"><img src="images/trans.gif" alt="" id="shoutapng"/></a>
	      </div>
	    </div>
	    <div id="data">
			<div class="tabs">
	            <ul class="tabNavigation">
	                <li><a href="#followings" class='first'><?php echo $this->lang->home->my_followings;?></a></li>
	                <li><a href="#aroundme"><?php echo $this->lang->home->aroundme;?></a></li>
	                <?php if ($this->config->rt_me) { ?><li><a href="#rtmine" ><?php echo $this->lang->home->rtmine;?></a></li><?php } ?>
	                <li><a href="#all"><?php echo $this->lang->home->newmajors;?></a></li>
	            </ul>
	            <div id="followings">
	            	<table class="blog_table"><tbody id='tbl_followings'><tr class='tbl_tr_ajax_loading'><td colspan='8' class='tbl_ajax_loading'><img src='images/ajax_loading.gif' alt='' /></td></tr></tbody></table>
					<table class='pager'>
						<tr>
						<td>
							<div class="page pager" id='pager_followings'></div>
						</td>
						</tr>
					</table>	
	            </div>
	            
	            <div id="aroundme" style='display:none'>
	            	<table class="blog_table">
	            		<tbody id='tbl_aroundme'></tbody>
					</table>
					<table class='pager'>
						<tr>
						<td>
							<div class="page pager" id='pager_aroundme'></div>
						</td>
						</tr>
					</table>
	            </div>	            	

	            <div id="all" style='display:none'>
	            	<table class="blog_table">
	            		<tbody id='tbl_all'></tbody>
					</table>
					<table class='pager'>
						<tr>
						<td>
							<div class="page pager" id='pager_all'></div>
						</td>
						</tr>
					</table>
	            </div>	    
				<div id="rtmine" style='display:none'>
	            	<table class="blog_table">
	            		<tbody id='tbl_rtmine'></tbody>
					</table>
					<table class='pager'>
						<tr>
						<td>
							<div class="page pager" id='pager_rtmine'></div>
						</td>
						</tr>
					</table>
	            </div>	    
	        </div><!--#tabs-->
        
	  	</div><!--#data-->	
	  </div><!--#half_left-->
	  <?php include_once(dirname(__FILE__).'/../include/rightbar.phtml');?>
  </div><!--#mid-->
</div> <!--#content-->
<!-- Feedback button-->
<a id='feedbackbutton' href='/feedback'><img src="/images/<?php echo $this->Images('feedback.png');?>" alt="" /></a>
<div id="footer">
  <div class="mid">
    <div class="inmid">
	    <div class="col">
	        <h2><?php echo $this->lang->global->foot->site->title;?></h2>
			<ul>
	  		<li><a href="/home"><?php echo $this->lang->global->nav->homepage;?></a></li>
	  		<li><a href="/user"><?php echo $this->lang->global->nav->user;?></a></li>
	  		<li><a href="/poi"><?php echo $this->lang->global->nav->around;?></a></li>
	  		<li><a href="/people/find"><?php echo $this->lang->global->nav->find_people;?></a></li>
				<li><a href="/mobile?force_redirect=1" title="<?php echo $this->lang->global->foot->aboutus->wapsite;?>"><?php echo $this->lang->global->foot->aboutus->wapsite;?></a></li>		
		  	</ul>
		</div>
		<div class="col">
	        <h2><?php echo $this->lang->global->foot->tools->title;?></h2>
			<ul>
				<li><a href="/tools/iphonedownload" title="<?php echo $this->lang->global->foot->tools->iphone;?>"><?php echo $this->lang->global->foot->tools->iphone;?></a></li>
				<li><a href="/tools/s60download" title="<?php echo $this->lang->global->foot->tools->symbian;?>"><?php echo $this->lang->global->foot->tools->symbiam;?></a></li>
		        <li><a href="/tools/androiddownload" title="<?php echo $this->lang->global->foot->tools->android;?>"><?php echo $this->lang->global->foot->tools->android;?></a></li>
		        <li><a href="/tools/wmdownload" title="<?php echo $this->lang->global->foot->tools->wm;?>"><?php echo $this->lang->global->foot->tools->wm;?></a></li>
		        <li><a href="/tools/blackberrydownload" title="<?php echo $this->lang->global->foot->tools->bb;?>"><?php echo $this->lang->global->foot->tools->bb;?></a></li>
				<li><a href="http://www.lbs.org.cn" target="_blank" title="<?php echo $this->lang->global->foot->tools->lbs;?>"><?php echo $this->lang->global->foot->tools->lbs;?></a></li>
		  	</ul>
		</div>
		<div class="col">
	        <h2><?php echo $this->lang->global->foot->sync->title;?></h2>
			<ul>
				<li><a href="/setting/sync#twitter" title="<?php echo $this->lang->global->foot->sync->twitter;?>"><?php echo $this->lang->global->foot->sync->twitter;?></a></li>
				<li><a href="/setting/sync#4sq" title="<?php echo $this->lang->global->foot->sync->foursqaure;?>"><?php echo $this->lang->global->foot->sync->foursqaure;?></a></li>
				<li><a href="/setting/sync#sina" title="<?php echo $this->lang->global->foot->sync->sina;?>"><?php echo $this->lang->global->foot->sync->sina;?></a></li>
				<li><a href="/setting/sync#sohu" title="<?php echo $this->lang->global->foot->sync->sohu;?>"><?php echo $this->lang->global->foot->sync->sohu;?></a></li>
				<li><a href="/setting/sync#9911" title="<?php echo $this->lang->global->foot->sync->_9911;?>"><?php echo $this->lang->global->foot->sync->_9911;?></a></li>
				<li><a href="/setting/sync#kaixin" title="<?php echo $this->lang->global->foot->sync->kaixin;?>"><?php echo $this->lang->global->foot->sync->kaixin;?></a></li>

				<!-- <li><a href="/setting/sync" title="<?php echo $this->lang->global->foot->sync->more;?>"><?php echo $this->lang->global->foot->sync->more;?></a></li>  -->
		  	</ul>
		</div>
		<div class="col">
	        <h2><?php echo $this->lang->global->foot->help->title;?></h2>
			<ul>
				<li><a href="/kai" title="<?php echo $this->lang->global->foot->aboutus->news;?>"><?php echo $this->lang->global->foot->aboutus->news;?></a></li>
				<li><a href="http://blog.k.ai/" title="<?php echo $this->lang->global->foot->aboutus->blog;?>"><?php echo $this->lang->global->foot->aboutus->blog;?></a></li>				
		        <li><a href="/signup/aboutus" class='blank' title="<?php echo $this->lang->global->foot->aboutus->aboutus;?>"><?php echo $this->lang->global->foot->aboutus->aboutus;?></a></li>
				<li><a href="/signup/terms" class='blank' title="<?php echo $this->lang->global->foot->aboutus->tos;?>"><?php echo $this->lang->global->foot->aboutus->tos;?></a></li>				
				<li><a href="/help/learnmore" title="<?php echo $this->lang->global->foot->aboutus->learnmore;?>"><?php echo $this->lang->global->foot->aboutus->learnmore;?></a></li>	  
		  	</ul>
		</div>
		
		<div class="clearfix"></div>
		
         <div class='icp'><br/>
  苏州贝多科技有限公司　<a href='http://www.miibeian.gov.cn' target='_blank'>苏ICP备09008736号</a>  增值电信业务经营许可证：苏B2-20090144 苏B2-20090233
  </div> 
    		
    </div>

  </div>

</div> <!--#footer-->
 
<div id='divFbMessage' class='hide' title=''></div>
<div id='divFbSendMessage' class='hide'>
<?php include_once(dirname(__FILE__).'/dmessage.phtml');?>
</div>
<div id='betterMessageBox' class='hide' title='' style="overflow: visible; "></div>
<div id='betterConfirmBox' class='hide' title='' style="overflow: visible; "></div>
<div id='betterFormBox' class='hide' title='' style="overflow: visible; "></div>
<?php include_once(dirname(__FILE__).'/../include/script.phtml');?>
<?php if (APPLICATION_ENV!='production') { ?><!-- Exec Time: <?php echo $this->execTime();?> s --><?php } ?>

<!-- Feedback button-->
<a id='feedbackbutton' href='/feedback'><img src="/images/<?php echo $this->Images('feedback.png');?>" alt="" /></a></body>
</html>