<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>

<body id="accountbanned">
<?php include_once(dirname(__FILE__).'/../include/newheader.phtml');?>	

<div id="content">
	<div class='mid' style='background:#fff; border: 1px solid #999;'>
  		<div style="height: 100px; width: 500px; margin: 150px auto;">
  		<table>
  			<tr>
  				<td><img src='images/ban.png' alt='' class='left' /></td>
  				<td>
  				<h3><?php echo $this->lang->global->account_banned; ?></h3>
  				<p><?php echo $this->lang->global->account_banned_tip; ?></p>
  				<span><?php echo $this->lang->global->back_link;?></span>
  				</td>
  			</tr>
  		</table>
  			
  		</div>
  	</div>
</div>

<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>

</body>
</html>
<?php $this->Gz();?>