<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
<body id="alert">

<?php include_once(dirname(__FILE__).'/../include/newheadernonav.phtml');?>


<div id="content">
  <div class="mid" style="background: #fff;">
  	<div class='new_titile'>
  	 <div id="setting_header_title"><span class='text'><?php echo $this->lang->global->help->learnmore->know_kaikai;?></span></div>
	   <div id="setting_header_img"><h2><?php echo $this->lang->global->setting_header_text;?></h2></div> 
  	
  	</div>
  	<div class='small_mid' style='height:400px;background-color:#eee;'>
		<?php echo $this->LangTpl($this->lang->global->help->learnmore->content);?>
    </div>
  </div><!--#mid-->
</div> <!--#content-->

<?php include_once(dirname(__FILE__).'/../include/footer.phtml');?>

</body>
</html>
<?php $this->Gz();?>