<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns:lift="http://liftweb.net" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
    <meta content="width=320" name="viewport" />   
    <title><?php echo $this->lang->global->meta->title;?></title>
    <?php include_once(dirname(__FILE__).'/../include/textcss.phtml');?>
</head>
<body>
    <?php include_once(dirname(__FILE__)."/../include/logo.phtml")?>
	
	<div id="content">
		<?php echo $this->lang->signup->term->title;?>
		<?php echo $this->LangTpl($this->lang->signup->term->content);?>
	</div>
	
	<?php include_once(dirname(__FILE__).'/../include/loginfooter.phtml');?>
</body>
</html>  
  