	<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
	
	<body>
		<div class='content_wraper'><div id="list">
		
		<div style="margin: 10px auto;">
			<form action="<?php echo $this->admin_url;?>/banlog" id="search_form">
			<table class='kai_table'>
			<tr><th colspan='6' class='center'>搜索</th></tr>
			<tr>
				<td width='25%'>管理员:</td>
				<td width='25%'><input type='text' name='admin_uid' id='admin_uid' value='<?php echo $this->params['admin_uid'];?>' /></td>
				<td>每页结果数:</td>
				<td>
				<select name='page_size' id='page_size'>
					<option value='<?php echo BETTER_PAGE_SIZE;?>' <?php echo $this->params['page_size']==BETTER_PAGE_SIZE ? ' selected="selected"' : '';?>>默认(<?php echo BETTER_PAGE_SIZE;?>)</option>
					<option value='50' <?php echo $this->params['page_size']==50 ? ' selected="selected"' : '';?>>50</option>
					<option value='100' <?php echo $this->params['page_size']==100 ? ' selected="selected"' : '';?>>100</option>
					<option value='99999999' <?php echo $this->params['page_size']==99999999 ? ' selected="selected"' : '';?>>全部</option>
				</select>
				</td>
			</tr>			
			<tr>
				<td>时间范围:</td>
				<td colspan='3'>
				从 <input type='text' name='from' id='from' value='<?php echo $this->params['from'];?>' readonly='readonly' />
				到 <input type='text' name='to' id='to' value='<?php echo $this->params['to'];?>' readonly='readonly' />
				</td>
			</tr>	
			<tr>
				<td>用户ID</td>
				<td colspan='10'><input type='text' name='uid' value='<?php echo $this->params['uid'];?>' /></td>
			</tr>		
			<tr>
				<td colspan='6' class='center'>
					<input type='submit' value='搜索(s)' accesskey='s' />
					<input type='button' value='清空搜索结果(r)' accesskey='r'  id='btnReset' />
					<input type='hidden' name='page' id='page' value='<?php echo $this->params['page'];?>' />
					<input type='hidden' name='reload' id='reload' value='0' />
				</td>
			</tr>
			</table>		
			</form>
		</div>

			<table cellspacing="0" class='kai_table'>	
				<tr>
					<td colspan='10' class='pager'>
					<?php echo $this->paginator();?>
					</td>
				</tr>					
				<tr>
					<th>管理员ID</th>
					<th>用户ID</th>
					<th>原状态</th>
					<th>现状态</th>
					<th>操作类型</th>
					<th>原因</th>
					<th>操作时间</th>
				</tr>
		
				<?php if ($this->count>0) { ?>
				<?php $i = 0; ?>
				<?php foreach ($this->rows as $row) {?>
				<tr class='<?php echo fmod($i++,2)==0 ? 'light' : 'dark';?> message_row'>
					<td><?php echo $this->highlight($row['admin_uid'], $this->params['admin_uid']);?></td>
					<td class='center'><a href="<?php echo $this->admin_url;?>/banlog?uid=<?php echo $row['uid'];?>"><?php echo $this->highlight($row['uid'], $this->params['uid']);?></a></td>
					<td class='center'><?php echo $row['old_state'];?></td>	
					<td class='center'><?php echo $row['now_state'];?></td>
					<td class='center'><?php echo $row['act_type'];?></td>
					<td class='center' class='messages'><?php echo $row['reason'];?></td>
					<td width='80' class='center' ><?php echo date('Y-m-d H:i:s', $row['dateline']+BETTER_8HOURS);?></td>
				</tr>
				<?php } ?>
			
				<?php } else {  ?>
				<tr>
					<td colspan='10' class='error center'>
					没有找到任何数据
					</td>
				</tr>				
				<?php } ?>
				<tr>
					<td colspan='10' class='pager'>
					<?php echo $this->paginator();?>
					</td>
				</tr>
			</table>	
		</div>
		</div>
	<?php include dirname(__FILE__).'/../include/footer.phtml';?>