<div id='hasflash'>
<div id='orange'>他们已经送出了给Ta的中秋祝福</div>
<div id='flash'><object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,19,0" width="850" height="400">
  <param name="movie" value="/images/maf/spreaditout.swf?ver=<?php echo BETTER_VER_CODE;?>" />
  <param name="quality" value="high" />
  <embed src="/images/maf/spreaditout.swf?ver=<?php echo BETTER_VER_CODE;?>" quality="high" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" width="850" height="400" wmode="transparent"></embed>
</object></div>
</div>