<div class='hide'>
<div id='divFbMessage' class='hide' title=''></div>
<div id='divFbSendMessage' class='hide'>
<?php include_once(dirname(__FILE__).'/dmessage.phtml');?>
</div>
<div id='betterMessageBox' class='hide' title='' style="overflow: visible; "></div>
<div id='betterConfirmBox' class='hide' title='' style="overflow: visible; "></div>
<div id='betterFormBox' class='hide' title='' style="overflow: visible; "></div>
<?php include_once(dirname(__FILE__).'/../include/script.phtml');?>
</div>
