<div class='place_post' id='dlgSendMessage'>

	    	<form name="formSendMsg" id="formSendMsg">
	    	<table cellspacing='0'>
	    		<tbody>
	    			<tr>
	    				<td id="messgae_td">
	    					
	    				</td></tr>
	    				<tr><td>
	    				<div style='float:right;'><input class="button btn" type="button" name="btn_send_msg" id="btn_send_msg" value="<?php echo $this->lang->global->include->dmessage->btn_send_msg;?>" />
	    				<input type="hidden" size="20" id="msg_receiver" name="msg_receiver" value='' /></div>
	    				</td>
	    			</tr>
	    		</tbody>
	    	</table>

	    	</form>

</div>

<!-- 举报对话框 -->
<div id='dlgDenounce'>
	<form id="formDenounce">
	<table>
		<tr>
			<td><?php echo $this->lang->global->include->dmessage->denounce_reason;?></td>
			<td>
				<select id='denounce_reason'>
					<option><?php echo $this->lang->global->include->dmessage->denounce_option_reaction;?></option>
					<option><?php echo $this->lang->global->include->dmessage->denounce_option_sex;?></option>
					<option><?php echo $this->lang->global->include->dmessage->denounce_option_akperson;?></option>
					<option><?php echo $this->lang->global->include->dmessage->denounce_option_unad;?></option>
				</select>
			</td>
		</tr>
		<tr>
			<td><?php echo $this->lang->global->include->dmessage->denounce_content;?></td>
			<td><textarea class='denounce_content' id='denounce_content'></textarea></td>
		</tr>
	</table>
	<input type="hidden" id="denounce_receiver" name="denounce_receiver" value='' />
	<input class="button btn right" type="button" id="btn_denounce" value="<?php echo $this->lang->global->include->dmessage->btn_denounce;?>" />
	</form>
</div>


<!-- 吼吼, 贴士, 我想去 -->
<div style="display: none;">
<div id="status" style="width: 500px;" shoutbox='shoutbox'>
	<form>
	<input type='hidden' id='attach' name='attach' value='' />
	<input type='hidden' id='upbid' name='upbid' value='0' />
	<input type='hidden' id='real_upbid' name='real_upbid' value='0' />
	<input type='hidden' id='dlg_type'  value='shout_dlg' />
	
	<div class="left" style="margin-left:10px; margin-top:4px;!margin-top:2px;">

		<img src="images/hou.gif" alt="" class="hide" id="shoutformicon" />
		<img src="images/tips.gif" alt="" class="hide" id="tipsformicon"/>
	</div>
	<div class='dialog_title' id='shout_title'><?php echo $this->shout_title;?></div>
	<a href="javascript:void(0);" id="close_shout" style="float: right; display: block; margin-top: 8px;!margin-top:4px;"><img src="images/close_button.png" /></a>
	<div>
		 <span class="right"  style="margin-right: 50px;">
			<?php 
			$thisinfo = $this->lang->post->noping->words_left_info;
			$thisinfo = str_replace("{WORDNUM}","<label id='txtCount' class='green b f16'></label>&nbsp;",$thisinfo);		
			echo $thisinfo;
			?>	  		 
 		</span>
	</div>
	<div class='clearfix'></div>
	
	<textarea id="status_text" style="width: 400px; height: 70px; overflow-y:auto; float: left;" ></textarea>
	<div class="right" id="btnUpload_img"><a href="javascript: void(0);"><img id='btnUpload' src="images/photo.png"  width='80' /></a></div>
	<div class='clearfix'></div>
	
	<!-- <div class='upload hide right' id='divFileDesc'>
	   <span id='fileDesc' ></span>
	</div>
	<div class='clearfix'></div> 
	-->
<?php if(!$this->inTrace){?>					
	<div class="location_bar" style="background-color:#fff8bd;" id='shout_poi_list'>
		<a href='javascript:void(0);' id='disable_shout_poi' title='<?php echo $this->lang->global->shout_without_poi;?>'><img src="images/close_button2.png" style="margin: 9px 7px;" class="left" /></a>

		
		<table cellpadding="0" cellspacing="0" border='0' height="40" style="line-height:20px; margin-top:2px;margin-top:1px;" class="left">
			<tr>
				<td>
				<div style="width:450px;text-overflow: ellipsis; white-space:nowrap; overflow:hidden;">
				<span style="font-size: 14px; font-weight: bold;" id=ready_to_shout_span'>
				<span id='ready_to_shout_at' class='hide'>@</span> 
				<span id='ready_to_shout_city' class='hide'><?php echo $this->user['city'];?></span> 
				<span id='ready_to_shout_poi_name' class='hide'><?php echo $this->user['poi']['name'];?></span>

				<span id='ready_to_shout_not_checkined'><?php echo $this->lang->global->not_checkin_yet;?></span>

				</span>
				</div>
				</td>
			</tr>
			<tr>
				<td><div style="width:450px;text-overflow: ellipsis; white-space:nowrap;overflow:hidden;"><span style="color: #a4afbf;" id='ready_to_shout_address'><?php echo $this->user['address'];?></span></div></td>
			</tr>
		</table>

		<?php if (!$this->inPoi) { ?>
		<div class="white_btn right" id='div_change_poi'>
			<a id="change_place_shout" href="javascript: void(0);"><?php echo $this->lang->global->include->dmessage->change_place_shout;?></a>
		</div>
		<?php } ?>
	</div>
	<div class='clear_fix'></div>
		
	<div id='rt_tips'>
		<table cellpadding="0" cellspacing="0" border='0' height="40" style="line-height:20px; margin-top:2px;!margin-top:1px;" class="left" id='tbl_rt'>
			<tr>
				<td><div style="width:490px; height: 20px; text-overflow: ellipsis; white-space:nowrap; overflow:hidden;"><div style="font-size: 14px; font-weight: bold;"><?php echo $this->lang->global->include->dmessage->forward.' ';?><span id='rt_content'></span></div></div></td>
			</tr>
			<tr>
				<td><div style="width:490px;text-overflow: ellipsis; white-space:nowrap; overflow:hidden;"><span style="color: #a4afbf;" id='rt_location'></span></div></td>
			</tr>
		</table>
		<div class='clear_fix'></div>
	</div>	
	
	
	<div class="poi_div hide">
		<div class="search_div">
			<input type="text" name="shout_keyword" id='shout_poi_keyword' value="<?php echo $this->lang->javascript->global->checkin->poi_search->tips;?>" class="left"/>
				<select name='range' id='shout_poi_search_range' class="left" style="margin:2px 0 0 5px;">
					<option value='5000'><?php echo $this->lang->global->checkin->range->name;?></option>
					<option value='5000' selected='selected'>5Km</option>
					<option value='10000'>10Km</option>
					<option value='50000'>50Km</option>
					<option value='100000'>100Km</option>
					<option value='99999999'><?php echo $this->lang->global->checkin->range->all;?></option>
				</select>			
			<a id='shout_search_poi' class="right" href="javascript: void(0);"><?php echo $this->lang->people->search->button_tips;?></a>
		</div>
		
		<div class='clearfix'></div>
		
		<div class="poi_list" id='shout_poi_list'></div>
	</div>
	
	<div style="margin-top: 12px;">
	<!-- <div class="left" style="margin-left: 32px;!margin-left:16px;"  id='shout_priv'>
		<input type="radio" name="privacy" value="public" checked="checked" id='privacy_public'><?php echo $this->lang->global->include->dmessage->privacy_public;?>
		<input type="radio" name="privacy" value="friend" id='privacy_protected'><?php echo $this->lang->global->include->dmessage->privacy_protected;?>
		<input type="radio" name="privacy" value="private" id='privacy_private'><?php echo $this->lang->global->include->dmessage->privacy_private;?>
	</div>
	
	<div class="left">
		<input type="checkbox" name="need_sync" id="need_sync" checked="checked" />
	</div>  -->

	 <div class="select_priv left" id='shout_priv'>
		<span id="priv_sel_shout" priv="public" class="priv_sel"><?php echo $this->lang->global->include->dmessage->privacy_public;?></span>
		<div class="drop_priv hide" id="drop_priv_shout">
			<span priv="public" id="shout_public"><?php echo $this->lang->global->include->dmessage->privacy_public;?></span>
			<div class="xu_line"></div> 
			<!-- <span priv="protected"><?php echo $this->lang->global->include->dmessage->privacy_protected;?></span>
			<div class="xu_line"></div>
			-->
			<span priv="private"><?php echo $this->lang->global->include->dmessage->privacy_private;?></span>
		</div>
	</div>
	
	<div class="check_sync left" id="check_sync">
	<?php if($this->site_count > 0){?>
		
		<span id="shout_checkbox">
		<input type="checkbox" name="need_sync" id="need_sync" checked="checked" />
		<?php echo $this->lang->global->include->dmessage->share; ?>
		</span>
		<span id="shout_nopublic" class="hide">
			<?php echo $this->lang->global->include->dmessage->no_public; ?>
		</span>
		
	<?php }else{?>
		<a href="setting/sync"><?php echo $this->lang->global->include->dmessage->no_bound; ?></a>
	<?php }?>	 
	</div>
	  
	<div class="right hide" style="margin-right: 30px; font-size: 14px;!margin-right:15px;">
		<a id='cancel_shout' href="javascript: void(0);" style="color:#0f7cc5;"><?php echo $this->lang->javascript->global->action->confirm->btn_cancel;?></a>
	</div>

	<div class="right">
		<a href="javascript: void(0);" class="blue_btn" style="width: 130px; height: 39px;" id="post_btn" accesskey='s'><?php echo $this->shout_text;?></a>
		<input type='hidden' id='ready_to_shout_poi' value='<?php echo $this->user['last_checkin_poi'];?>' />
	</div>

	</div>
<?php }?>
	</form>
</div>
</div>



<!-- 签到 -->
<div style="display: none;" id='global_checkin_div'>
<div id="checkindlg" style="width: 500px;" checkinbox='checkinbox'>

<input type='hidden' id='checkin_attach' name='checkin_attach' value='' />

	<form>
	<div class="left" style="margin-left:10px;">
		<img src="images/checkin.gif" alt=""  />
	</div>
	<div class='dialog_title'><?php echo $this->lang->global->include->dmessage->checkin;?></div>
	<a href="javascript:void(0);" id="close_check" style="float: right; display: block; margin-top: 8px;"><img src="images/close_button.png" /></a>

	 <div>
		 <span class="right"  style="margin-right: 50px;">
			<?php 
			$thisinfo = $this->lang->post->noping->words_left_info;
			$thisinfo = str_replace("{WORDNUM}","<label id='checkin_txtCount' class='green b f16'></label>&nbsp;",$thisinfo);		
			echo $thisinfo;
			?>	  		 
 		</span>
	</div>
	
	<div class='clearfix'></div>
	
	<textarea id="checkin_status_text" style="width: 400px; height: 70px; overflow-y:auto; float: left;" ></textarea>
	<div class="right"><a href="javascript: void(0);"><img id='checkin_btnUpload' src="images/photo.png"  width='80' /></a></div>
	<div class='clearfix'></div>
	
	<div class='hide'' id='scode' style='margin:2px 0 0 0;' >
		<input type='text' id='code' name='code' value='' class="left" style="width:60px;"/>
		<input type='hidden' id='height_fb' name='height_fb' value='' />
		<img id="img_code" src='/Scode?<?php echo rand(100000,999999);?>' class="left" style='margin-left:10px;'/>
		<div id="switch_scode" class="left"><?php echo $this->lang->signup->change_scode;?></div>
	</div>	
	<div class='clearfix'></div>
		   
	<div style="height: 42px; background-color:#dee5ee; margin-top: 8px; padding-left: 20px;">
		<table cellpadding="0" cellspacing="0" border='0' height="40" style="line-height:20px; margin-top:2px; display:none;" class="left" id='tbl_checkined'>
			<tr>
				<td><div style="width:340px;text-overflow: ellipsis; white-space:nowrap;overflow:hidden;"><span style="font-size: 14px; font-weight: bold;">@ <span id='ready_to_checkin_city'></span> <span id='ready_to_checkin_poi_name'></span></span></div></td>
			</tr>
			<tr>
				<td><div style="width:340px;text-overflow: ellipsis; white-space:nowrap;overflow:hidden;"><span style="color: #a4afbf;" id='ready_to_checkin_address'></span></div></td>
			</tr>
		</table>
		<table cellpadding="0" cellspacing="0" border='0' height="40" style="line-height:20px; margin-top:2px;" class="left" id='tbl_not_checkined'>
			<tr>
				<td><span style="font-size: 14px; font-weight: bold;"><?php echo $this->lang->global->include->dmessage->notcheckin;?></span></td>
			</tr>
			<tr>
				<td><span style="color: #a4afbf;"></span></td>
			</tr>
		</table>	
		

		<div class="white_btn right">
			<a id="change_place_checkin" href="/pois"><?php echo $this->lang->global->include->dmessage->change_place_checkin;?></a>
		</div>

		
	</div>

	
	<div style="margin-top: 12px;">
	<div class="select_priv left">
		<span id="priv_sel" priv="public" class="priv_sel"><?php echo $this->lang->global->include->dmessage->privacy_public;?></span>
		<div class="drop_priv hide" id="drop_priv">
			<span priv="public" id="checkin_public"><?php echo $this->lang->global->include->dmessage->privacy_public;?></span>
			<div class="xu_line"></div>
			<span priv="private"><?php echo $this->lang->global->include->dmessage->privacy_private;?></span>
		</div>
	</div>
	
	<div class="check_sync left">
	<?php if($this->site_count > 0){?>
		
		<span id="checkin_checkbox">
		<input type="checkbox" name="checkin_need_sync" id="checkin_need_sync" checked="checked" />
		<?php echo $this->lang->global->include->dmessage->share; ?>
		</span>
		<span id="checkin_nopublic" class="hide">
			<?php echo $this->lang->global->include->dmessage->no_public; ?>
		</span>
		
	<?php }else{?>
		<a href="setting/sync"><?php echo $this->lang->global->include->dmessage->no_bound; ?></a>
	<?php }?>
	</div> 
	
	<div class="right hide" style="margin-right: 30px; font-size: 14px;!margin-right: 15px;">
		<a id='cancel_checkin' href="javascript: void(0);" style="color:#0f7cc5;"><?php echo $this->lang->javascript->global->action->confirm->btn_cancel;?></a>
	</div> 

	<div class="right">
		<a href="javascript: void(0);" class="blue_btn"  id="checkin_btn" accesskey='s'><?php echo $this->lang->global->include->dmessage->btn_checkin;?></a>
		<input type='hidden' id='ready_to_checkin_poi' value='<?php echo $this->user['last_checkin_poi'];?>' />
		<input type='hidden' id='ready_to_checkin_ab_poi' value='0' />
	</div>
	</div>
	
	
	</form>
</div>
</div>
<!-- 邀请好友一起去 -->

	<div id="invitefriends" style="width:570px">
		<div class='dialog_title' style="width:auto">邀请好友一起去<span id='title_poi_name'></span></div>
			<a href="javascript:void(0);" id="close_todo" style="float: right; display: block; margin-top: 8px;"><img src="images/close_button.png" /></a>
		<div class='clearfix'></div>
		<div class="invite-content">	
			<div class="has-invited left"><span class="left">我要邀请</span><span class="left" id="invitation-count">0</span><span class="left">个好友：</span><span id="invitation-names"></span></div>
			<div class="filter-friends">
				<div class="search-box"><input value="输入好友姓名快速查找" style="width:230px;height:20px;color:#999" id="keyword-input"></input></div>
				<div class="choose-box">
					<a href="javascript:void(0)" id="chooseAll">全选</a>
					<a href="javascript:void(0)" id="resetAll">重选</a>
				</div>
			</div>
			<ul id="ulcontainer">			
			</ul>
			
			<div class="invite-page">
				<div id="pager-container">
					<span style="width:15px;height:15px;margin:3px 0 0 15px">
						<a href="javascript:void(0)" id="lastpage"></a>
					 </span>
					 <span id="currentpage" style="margin-left:15px"></span><span>/</span><span id="pagecount" ></span>
					 <span style="width:15px;height:15px;margin:3px 0 0 15px">
						 <a href="javascript:void(0)" id="nextpage"></a>
					</span>
				</div>
				<div class="clearfix"></div>
			</div>
			<div class="clearfix"></div>
		</div>
		<div id="cachecontainer"></div>
		<div><textarea style="width:560px;height:25px;color:#999" id="invite-email"  value="通过Email邀请好友一起去。(填写多个Email时，请用空格、分号、回车分割)">通过Email邀请好友一起去。(填写多个Email时，请用空格、分号、回车分割)</textarea></div>
		<div style="margin:10px 0 0 0"><textarea style="width:560px;height:50px;color:#999" id="msg_content"  value="我想去这儿看看，哪天有时间一起去吧？">我想去这儿看看，哪天有时间一起去吧？</textarea></div>
		<div class="right" style="margin-top:10px">
			<input type="hidden" value=',' name="fuids" id="fuids"/>
			<input type="hidden" value="" name='alluids' id="alluids"/>
			<input type="hidden" value="" name="allusernames" id="allusernames"/>
			<input type="hidden" id="poiid_invitation_todo" value=""/>
			<input type="hidden" id="poiname_invitation_todo" value=""/>
			<input type="hidden" id="bid_invitation_todo" value="175623.2680"/>
			<a href="javascript: void(0);" class="blue_btn"  id="invitation_btn" accesskey='s'>确定</a>
		</div>
	</div>


<div style='display:none;'>
<a href='#status' id='shouta'><?php echo $this->lang->global->include->dmessage->shouta;?></a>
<a href='#checkindlg' id='hideCheckina'><?php echo $this->lang->global->include->dmessage->checkina;?></a>
<a href='#invitefriends' id="invitefriends_btn">邀请好友</a>
</div>
