<li class="search">
				<div id='top_search_block'>
				<input type="text" name="search_text" id="search_text" value="输入您要找的地名/人名" style='color: #999;' autocomplete="off" />
				<input type='hidden' id='global_search_range' name='search_range' value='poi' />
				<input type="submit" value="搜索" id="search_button" style='height: 24px; line-height: 20px; padding: 0 5px; margin-top: -2px;' />
				<!-- <ul class="dropdown" id='range_dropdown'>
					<li id='global_search_poi'><?php echo $this->lang->global->include->header_search_poi;?></li>
					<li id='global_search_blog'><?php echo $this->lang->global->include->header_search_shout;?></li>
					<li class="last" id='global_search_user'><?php echo $this->lang->global->include->header_search_user;?></li>
				</ul>  -->
				</div>				
</li>