<div class="box">
	  	  <h3><?php echo $this->lang->sidebar->share2bedo->title;?></h3>
	  	  <div class="cbox">
	  	    <div class="share">
	  	        <img src="images/share.png" class="share"/>
  	  	  		<div><?php echo $this->lang->sidebar->share2bedo->tips;?></div>
  	  	  		<div class="clearfix"></div>
  	  	  	</div>
  	  	  	<div class="share">
		  	  	<ul>
	  	  	  		<li><img src="images/sms.png" alt=""/> <?php echo $this->lang->sidebar->share2bedo->send_sms;?> 13675182068</li>
	  	  	  		<li><img src="images/mms.png" alt=""/> <?php echo $this->lang->sidebar->share2bedo->send_mms;?> mms@peptalk.cn</li>
	  	  	  		<!-- <li><img src="images/import.png" alt=""/> 自动导入其他社区内容</li> -->
		  	  	</ul>
	  	  	</div>
	  	  </div>
	  	</div>