<div style='background:#eee;' >
<table>
				<tr>
					<td>
					[<a href='<?php echo $this->admin_url;?>/userrank/index/act_type/del_blog' target='content'>删除微博排行</a>]&nbsp;
					[<a href='<?php echo $this->admin_url;?>/userrank/index/act_type/del_attach' target='content'>删除附件排行</a>]&nbsp;
					[<a href='<?php echo $this->admin_url;?>/userrank/index/act_type/del_avatar' target='content'>删除用户头像排行</a>]&nbsp;
					[<a href='<?php echo $this->admin_url;?>/userrank/index/act_type/reset_place' target='content'>重置微博位置排行</a>]&nbsp;
					[<a href='<?php echo $this->admin_url;?>/userrank/index/act_type/reset_user_place' target='content'>重置用户位置排行</a>]&nbsp;
					[<a href='<?php echo $this->admin_url;?>/userrank/index/act_type/reset_user_realname' target='content'>重置用户姓名排行</a>]&nbsp;
					[<a href='<?php echo $this->admin_url;?>/userrank/index/act_type/reset_user_selfintro' target='content'>重置用户自我介绍排行</a>]&nbsp;
					</td>
				</tr>
</table>
</div>
