	<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
	
	<body>
		<div class='content_wraper'><div id="list">
		<div style='width: 100%; text-align:left; background-color:#D3DCE3;'>[<a href='/admin/picture' class='left highlight'  style="color:#FF0000">所有图片</a>] [<a href='/admin/useravatar?avatar=1' class='left'>用户头像</a>] [<a href='/admin/photo?photo=1' class='left'>用户图片</a>][<a href='/admin/useravatar?avatar=1&advance=1&view_type=2'' class='left'>掌门头像</a>]</div>
		<div style="margin: 10px auto;">
			<form action="<?php echo $this->admin_url;?>/picture" id="search_form">
			<table class='kai_table'>
			<tr><th colspan='6' class='center'>搜索</th></tr>
			<tr>
				<td>Bedo号精确查找:</td>
				<td><input type='text' name='bedo_no' id='bedo_no' value='<?php echo $this->params['bedo_no'];?>' /></td>


				<td>每页结果数:</td>
				<td>
				<select name='page_size' id='page_size'>
					<option value='<?php echo BETTER_PAGE_SIZE;?>' <?php echo $this->params['page_size']==BETTER_PAGE_SIZE ? ' selected="selected"' : '';?>><?php echo BETTER_PAGE_SIZE;?></option>
					<option value='50' <?php echo $this->params['page_size']==50 ? ' selected="selected"' : '';?>>默认(50)</option>
					<option value='100' <?php echo $this->params['page_size']==100 ? ' selected="selected"' : '';?>>100</option>
					<option value='99999999' <?php echo $this->params['page_size']==99999999 ? ' selected="selected"' : '';?>>全部</option>
				</select>
				</td>
			</tr>			
			
			<tr>
				<td colspan='4' class='center'>
					<input type='submit' value='搜索(s)' accesskey='s' />
					<input type='button' value='清空搜索结果(r)' accesskey='r'  id='btnReset' />
					<input type='hidden' name='page' id='page' value='<?php echo $this->params['page'];?>' />
					<input type='hidden' name='reload' id='reload' value='0' />
					<input type='hidden' name='type' id='type' value='' />
					<input type='hidden' name='uid' id='uid' value='<?php echo $this->params['uid'];?>' />
				</td>
			</tr>
			</table>		
			</form>
		</div>

		<table cellspacing="0" class='kai_table'>	
				<tr>
					<td colspan='10' class='pager'>
					<?php echo $this->paginator();?>
					</td>
				</tr>					
		
				<?php if ($this->count>0) { ?>
				<?php 
					$i = 0;
					$j = 1;
					$colcount = 4;//列数 
				?>
				
				<tr class='<?php echo fmod($i++,2)==0 ? 'light' : 'dark';?> message_row'>
				<?php foreach ($this->rows as $row) {
						$bbid =  str_replace('.', '_', $row['id']);//JQuery ID选择器不支持小数点，为了后面的使用，替换成下划线
				?>
					<td class='message_col'>
					<table>
						<tr>
							<td style="border: 0px;"><input type='checkbox' name='ids[]'  value='<?php echo $row['id'];?>' /><br/>删除
							</td>
							<td style="border: 0px;" class='messages'>
								<div class='attach_row'>
									<a href='<?php echo $row['picture'];?>' class='msg_attach'><img width='80' height='80' id='<?php echo $bbid ;?>' src='<?php echo $row['picture'];?>' class="attach" /></a>
								</div>
								
								<a href='JavaScript: void(0);' onClick="Delpic_Ban('<?php echo $row['id'];?>', <?php echo $row['uid'];?>)"><?php echo $row['uinfo'];?></a><br>
								<?php echo date('Y-m-d H:i:s', $row['dateline']+BETTER_8HOURS)?>
							</td>
						</tr>
					</table>
					
					</td>
				<?php if($j==count($this->rows) && fmod($j, $colcount)!=0 && $j>$colcount){//生成空的单元格
					for($c=0; $c<$colcount-fmod(count($this->rows),$colcount); $c++){?>
						<td>&nbsp;</td>	
				<?php }
				}?>
				
				<?php if(fmod($j++,$colcount)==0){?>
					</tr><tr class='<?php echo fmod($i++,2)==0 ? 'light' : 'dark';?> message_row'>
				<?php 	
				 } 
					}?>
				</tr>
				<tr>
					<td colspan='10' class='center'>
					<input type='button' id='chooseAll1' name='chooseAll1'  value='全选(a)' accesskey='a' />
					<input type='button' id='chooseNone1' name='chooseNone1' value='全不选(n)' accesskey='n' />
					<input type='button' id='chooseReverse1' name='chooseReverse1' value='反选(v)' accesskey='v' />
				</td></tr>
				<tr><td colspan='10' class='center'>
					
					<input type='button' id='btnCheck' value=' 已 审 ' />
					</td>
				</tr>					
				<?php } else {  ?>
				<tr>
					<td colspan='10' class='error center'>
					没有找到任何数据
					</td>
				</tr>				
				<?php } ?>
				<tr>
					<td colspan='10' class='pager'>
					<?php echo $this->paginator();?>
					</td>
				</tr>
			</table>	
			<div id='delandban_account' style="display: none;" title='对<?php echo $this->params['uid'];?>进行封号'>
				<div style="height: 275px; width: 300px; text-align: left;">
				<h4>请输入封号原因：</h4>
				<textarea cols='40' rows='10' id='ban_reason_textarea'></textarea><br><br>
				<input type="button" id='ban_btn' value='确定'>
						
				</div>
			</div>
		</div>
		</div>
	<?php include dirname(__FILE__).'/../include/footer.phtml';?>