	<?php include_once(dirname(__FILE__).'/../include/meta.phtml');?>
	
	<body>
		<div class='content_wraper'><div id="list">
		
		<div style="margin: 10px auto;" class="hide">
			<form action="<?php echo $this->admin_url;?>/administrator" id="search_form">
			<table class='kai_table'>
			<tr><th colspan='6' class='center'>搜索</th></tr>
			<tr>
				<td>用户ID关键字:</td>
				<td><input type='text' name='keyword' id='keyword' value='<?php echo $this->params['keyword'];?>' /></td>
				<td>用户名关键字:</td>
				<td><input type='text' name='user_keyword' id='user_keyword' value='<?php echo $this->params['user_keyword'];?>' /></td>
				<td>每页结果数:</td>
				<td>
				<select name='page_size' id='page_size'>
					<option value='<?php echo BETTER_PAGE_SIZE;?>' <?php echo $this->params['page_size']==BETTER_PAGE_SIZE ? ' selected="selected"' : '';?>>默认(<?php echo BETTER_PAGE_SIZE;?>)</option>
					<option value='50' <?php echo $this->params['page_size']==50 ? ' selected="selected"' : '';?>>50</option>
					<option value='100' <?php echo $this->params['page_size']==100 ? ' selected="selected"' : '';?>>100</option>
					<option value='99999999' <?php echo $this->params['page_size']==99999999 ? ' selected="selected"' : '';?>>全部</option>
				</select>
				</td>
			</tr>			
				
			<tr>
				<td colspan='6' class='center'>
					<input type='submit' value='搜索(s)' accesskey='s' />
					<input type='button' value='清空搜索结果(r)' accesskey='r'  id='btnReset' />
					<input type='hidden' name='page' id='page' value='<?php echo $this->params['page'];?>' />
					<input type='hidden' name='reload' id='reload' value='0' />
				</td>
			</tr>
			</table>		
			</form>
		</div> 
		
		<div style="margin: 10px auto;">
			<form action="" id="add_form">
			<table class='kai_table'>
			<tr><th colspan='6' class='center'>添加管理员</th></tr>
			<tr>
				<td width='15%'>用户ID:</td>
				<td><input type='text' name='uid' id='uid' value='' /></td>
				<td width='15%'>用户名:</td>
				<td><input type='text' name='username' id='username' value='' /></td>
				<td width='15%'>密码:</td>
				<td>
					<input type='password' name='pwd' id='pwd' value='' />
				</td>
			</tr>			
				
			<tr>
				<td colspan='6' class='center'>
					<input type='button' id="btnAdd" value='添加'/>
					<input type='reset' value='重置'/>
				</td>
			</tr>
			</table>		
			</form>
		</div> 
		
		<div style="margin: 30px auto;" class="hide" id="update_div">
			<form action="" id="update_form">
			<input type="hidden" id="adid" />
			<table class='kai_table'>
			<tr><th colspan='6' class='center'>更新</th></tr>
			<tr>
				<td width='15%'>用户ID:</td>
				<td><input type='text' name='uid_update' id='uid_update' value='' /></td>
				<td width='15%'>用户名:</td>
				<td><input type='text' name='username_update' id='username_update' value='' /></td>
				<td width='15%'>密码:</td>
				<td>
					<input type='text' name='pwd_update' id='pwd_update' value='' />
				</td>
			</tr>			
				
			<tr>
				<td colspan='6' class='center'>
					<input type='button' id="btnUpdate" value='更新'/>
					<input type='button' id="btnfangqi" value='放弃'/>
				</td>
			</tr>
			</table>		
			</form>
		</div> 

			<table cellspacing="0" class='kai_table'>	
				<tr>
					<td colspan='10' class='pager'>
					<?php echo $this->paginator();?>
					</td>
				</tr>					
				<tr>
					<th></th>
					<th>ID</th>
					<th>用户名</th>
					<th>密码</th>
					<th>&nbsp;</th>
				</tr>
		
				<?php if ($this->count>0) { ?>
				<?php $i = 0; ?>
				<?php foreach ($this->rows as $row) {?>
				<tr class='<?php echo fmod($i++,2)==0 ? 'light' : 'dark';?> message_row'>
					<td><input type='checkbox' name='bids[]'  value='<?php echo $row['uid'];?>' /></td>
					<td class='center'><?php echo $row['uid']?></td>
					<td class='center'><?php echo $row['username']?></td>
					<td class='center'><?php echo $row['password']?></td>
					<td class='center'><a href="#" id="<?php echo $row['uid'];?>">修改</a>
						<input type="hidden" id="<?php echo $row['uid'];?>_id" value='<?php echo $row['uid']?>'>
						<input type="hidden" id="<?php echo $row['uid'];?>_username" value='<?php echo $row['username']?>'>
						<input type="hidden" id="<?php echo $row['uid'];?>_pwd" value='<?php echo $row['password']?>'>
					</td>		
				</tr>
				<?php } ?>
				<tr>
					<td colspan='10' class='center'>
					<input type='button' id='chooseAll' name='chooseAll'  value='全选(a)' accesskey='a' />
					<input type='button' id='chooseNone' name='chooseNone' value='全不选(n)' accesskey='n' />
					<input type='button' id='chooseReverse' name='chooseReverse' value='反选(v)' accesskey='v' />
				</td></tr>
				<tr><td colspan='10' class='center'>
					<input type='button' id='btnDel' name='btnDel' value='删除所选(d)' accesskey='d' />
					</td>
				</tr>					
				<?php } else {  ?>
				<tr>
					<td colspan='10' class='error center'>
					没有找到任何数据
					</td>
				</tr>				
				<?php } ?>
				<tr>
					<td colspan='10' class='pager'>
					<?php echo $this->paginator();?>
					</td>
				</tr>
			</table>	
		</div>
		</div>
	<?php include dirname(__FILE__).'/../include/footer.phtml';?>